### ISSUE TITLE
Crash when cloning implicitly held cell

### ISSUE THREAD

**Issue by infernosblade** [tahoma2d/tahoma2d#1011]
### Bug Description

Minor bug. Crash when cloning implicitly held cell. 

### Steps to reproduce

Crash when cloning implicitly held cell

### Software Version

1.3

### Operating System

win10

**Comment by artisteacher** [comment]
I get a crash as well on macOS. This happens on all 3 level types. Doesn't matter if there's a stop hold or if the scene is saved.
[clone-crash.txt](https://github.com/tahoma2d/tahoma2d/files/9049554/clone-crash.txt)
