### ISSUE TITLE
AppImage doesn't open 

### ISSUE THREAD

**Issue by ruiznick** [tahoma2d/tahoma2d#1021]
### Bug Description

Tahoma2D 1.3 fails to open on Linux Mint 19.3 (Ubuntu 18.04). Version 1.2 worked fine.

### Relevant logs/screenshots

./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Tahoma2D.AppImage)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_gapi.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_ml.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_stitching.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_videoio.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libtnzstdfx.so)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_imgcodecs.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_flann.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_imgproc.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libopencv_core.so.4.5)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libtoonzqt.so)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libtoonzlib.so)
./Tahoma2D.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_TahomaAUXqm5/usr/bin/../lib/libtnzcore.so)

### Software Version

1.3

### Operating System

 Linux Mint 19.3 (Ubuntu 18.04)

**Comment by manongjohn** [comment]
T2D 1.3 is compiled on Ubunutu 18.04. Your system may not necessarily have the most recent libs or parts may be missing?

To see what you currently support, open terminal and run the following:

```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
```

A quick search on-line shows someone who had the same error message (for a different application), resolved it as follows:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9
sudo apt install libstdc++6
```

**Comment by ruiznick** [comment]
I just upgraded to Ubuntu 20 and T2D 1.3 opened just fine with no extra steps. So unfortunately I can't test these steps. Thanks for the response, I hope it would be helpful to others that stumble upon this issue.
