### ISSUE TITLE
Can't save anything

### ISSUE THREAD

**Issue by xky-xky-xky** [tahoma2d/tahoma2d#1025]
### Bug Description

I just downloaded Tahoma2D, ran it, but I can't save anything. I also tried making a new project, running it as an administrator, and restarting my computer. Am I missing something?

### Relevant logs/screenshots

![tahoma_cant_save](https://user-images.githubusercontent.com/111027331/184050491-261f4a19-a92c-418f-8fe3-b3b06e55e20c.png)
![cant2](https://user-images.githubusercontent.com/111027331/184050493-cab0666c-598e-48f1-92e4-c6a0ddef7818.png)
![cant3](https://user-images.githubusercontent.com/111027331/184050570-085a28aa-d377-45af-b834-1e3a09369ffe.png)

### Software Version

1.3

### Operating System

Windows 10, Version 21H2, Build 19044.1889

### Drawing Tablet

Wacom Cintiq

**Comment by artisteacher** [comment]
In T2D, we can either Save-All, or save scenes, levels & etc. separately. Does this happen with all of the different saving options? If you make a project in a different location, does that make a difference?

**Comment by xky-xky-xky** [comment]
@artisteacher Thanks for the reply. I opened a new project on my Desktop and I still get the error trying to Save-All:
![tahodesktop](https://user-images.githubusercontent.com/111027331/184254614-515b17ea-4edd-48de-a5a4-15ee77792482.png)
![saveall2](https://user-images.githubusercontent.com/111027331/184254675-593f3396-d4b7-4e2f-963b-45b23960c289.png)
![saveall3](https://user-images.githubusercontent.com/111027331/184254674-c39feb7b-588d-44ce-b257-77a8497f866a.png)

Still errors when saving the scene only:
![sceneonly](https://user-images.githubusercontent.com/111027331/184254824-ab39dc29-e527-4683-9f7c-519dfa928539.png)

And I could not find the option to save the level only, this is what my save menu looks like:
![save options](https://user-images.githubusercontent.com/111027331/184254880-66f2c6cd-7e97-4a71-84b5-b63195b760ce.png)

I should mention I also have OpenToonz installed, is that an issue?

**Comment by manongjohn** [comment]
Does your username have special characters in it?

**Comment by xky-xky-xky** [comment]
@manongjohn Like in the directory path? Nope, purely alphabetic characters

**Comment by manongjohn** [comment]
Save Level can be found under `Level` menu option.

Running Anti virus? Try temporarily turning it off and see if you can save?

Normally if it was a permission issue, running as Administrator would show that was the issue since it would be able to save as Admin.  If its not Anti virus, I'm not sure what else could be blocking you.

**Comment by xky-xky-xky** [comment]
Yep, it was the anti virus! Thanks a bunch :) I'm so excited to use Tahoma2D!
