### ISSUE TITLE
Linux : Tahoma2d can't be installed alongside Opentoonz because of conflicting files

### ISSUE THREAD

**Issue by ABelliqueux** [tahoma2d/tahoma2d#1032]
### Bug Description

On Manjaro/Arch Linux, when trying to install Opentoonz alongside Tahoma2d, the package manager fails with : 

```
error: failed to commit transaction (conflicting files)
opentoonz: /usr/bin/lzocompress exists in filesystem (owned by tahoma2d)
opentoonz: /usr/bin/lzodecompress exists in filesystem (owned by tahoma2d)
opentoonz: /usr/bin/tcleanup exists in filesystem (owned by tahoma2d)
opentoonz: /usr/bin/tcomposer exists in filesystem (owned by tahoma2d)
opentoonz: /usr/bin/tconverter exists in filesystem (owned by tahoma2d)
opentoonz: /usr/bin/tfarmcontroller exists in filesystem (owned by tahoma2d)
opentoonz: /usr/bin/tfarmserver exists in filesystem (owned by tahoma2d)
```

Shouldn't these T2D specific versions be renamed so that both versions can cohabit ? 

Or are these files untouched from Opentoonz, i.e they are the same, and can safely be overwritten ? If so, is there some guarantee that this will stay the same in the future ?

### Steps to reproduce

 On a Linux installation : 
  * Install Tahoma2d via package manager
  * Install Opentoonz via package manager
  * Install should fail because of conflicting files

### Software Version

1.3

### Operating System

Manjaro Linux 21.3.7

### Graphics Card

Nvidia GTX 1050

### Drawing Tablet

Wacom

**Comment by jointri** [comment]
From the sound of it, you're trying to install Tahoma2D from AUR even if you have OpenToonz installed. T2D is a fork of opentoonz, so it's going to use a lot of stuff from OT. This isn't at all a bug with OpenToonz or Tahoma2D. It's not that uncommon for package conflicts with AUR if two or more packages both install certain components.

**Comment by manongjohn** [comment]
T2D's components should be considered unique to T2D as there might be changes to "common" executables/libraries with OT. They should not be used interchangeably.

Additonally, T2D is currently packaged and released as a Portable, but someone has decided to unpackage it and create a system installation version. I am not responsible for that particular packaging and will not modify anything related to that form of installation at this time.

That being said, I have a PR to create system installer versions for Windows and MacOS, but have not done that for Linux. Due to the various flavors of linux and different stores and what not, I am not sure if i can easily do that.

**Comment by ABelliqueux** [comment]
Hi, thanks for your answers, 
I realize it's not a bug of Tahoma2d per se, and that package managers should take the necessary steps to avoid such conflicts when possible. 

However, if those executables are to be considered as unique and are destined to a different evolution than the originals, why not rename them now and avoid possible future issues ? The main executable was after all renamed from `opentoonz` to `tahoma2d`.

Wouldn't suffixing them with something like "t2d_" be advisable to avoid possible future conflicts ?

**Comment by FabioLolix** [comment]
>  but someone has decided to unpackage it and create a system installation version

Tahoma2d on AUR which @ABelliqueux is using is build from source

> I am not responsible for that particular packaging and will not modify anything related to that form of installation at this time.

I'm fine with it, I'll add the conflict with opentoonz which I've missed

**Comment by ABelliqueux** [comment]
Ok, then feel free to close this issue as it's not really a bug. My aim was to be able to test if an issue I might encounter in tahoma2d was not already exisiting in opentoonz. 

Before I switch to the appimage version, can you give me an estimate of how trivial it would be to alter the sources in order to change these exec names, and possibly a pointer to where to look at in the sources for a start ? I might give it a try :)

**Comment by jointri** [comment]
@ABelliqueux You don't need to modify the source code itself, just modify the correct CMake files. Lines containing something like `add_executable(tfarmserver` would be what the name of the output binary is, there is a similar CMake function if doing a library. Just change tfarmserver to tdfarmserver or anything different to avoid conflict.

**Comment by ABelliqueux** [comment]
Ok, I've come up with [a few sed commands](https://gist.github.com/ABelliqueux/11dbefdb0c386c5de88f78ef196cf5c6#file-pkgbuild-L36-L45) that replace the occurrences in the cmakefiles and it builds fine and results in the new binaries names. I have not tried to `make install` yet, as I'm in the middle of an animation project, but will confirm the resulting build works fine ASAP.

An experimental PKGBUILD I have yet to test  is available here :  

https://gist.github.com/ABelliqueux/11dbefdb0c386c5de88f78ef196cf5c6

**Comment by ABelliqueux** [comment]
I made the PR, should I close this issue ?
