### ISSUE TITLE
Could you guys add correction or smoothness like on open toonz please?

### ISSUE THREAD

**Issue by Cheeseburgerz** [tahoma2d/tahoma2d#1038]

**Comment by artisteacher** [comment]
T2D has the same smoothness settings as OT. 

The mypaint brushes are handled differently from the vector/standard smart raster level brushes and don't have a smoothness option in the the tool options bar. I believe there is an equivalent setting in the brush settings though. This is exactly the same in OT.

**Comment by manongjohn** [comment]
Added in #1465 and will be in 1.5 release
