### ISSUE TITLE
I can't open shortcut of Tahoma2D (Linux)

### ISSUE THREAD

**Issue by Raiguri** [tahoma2d/tahoma2d#1040]
### Bug Description

Tahoma2D not runable through .desktop file

### Steps to reproduce

I tried to create .desktop file manually and also with [appimagelauncher](https://github.com/TheAssassin/AppImageLauncher).
Then I tried to run Tahoma2D

### Relevant logs/screenshots

![image](https://user-images.githubusercontent.com/50903186/190045962-130450af-263e-4434-ae6a-f2094172dca3.png)

### Software Version

1.3

### Operating System

KDE neon 5.25 x86_64

### Graphics Card

NVIDIA GTX 1050-TI

**Comment by olddesklamp** [comment]
It's because the AppImage can't see the folders in its directory for whatever reason when you run it through a .desktop file. You can get around this by making a .desktop file in your Tahoma2D directory and making a second .desktop file elsewhere linking to the one you made previously.

**Comment by Raiguri** [comment]
> It's because the AppImage can't see the folders in its directory for whatever reason when you run it through a .desktop file. You can get around this by making a .desktop file in your Tahoma2D directory and making a second .desktop file elsewhere linking to the one you made previously.

Oh, strange solution, but I will try. Would be nice if it work without strange .desktop file linking

**Comment by olddesklamp** [comment]
I got symlinks and .desktop files confused, a much better solution is to set the .desktop's working path to your Tahoma2D directory. 

<details><summary>Screenshot for reference</summary>
<p>

![image](https://user-images.githubusercontent.com/74428438/190295958-4396eb50-9d7c-40f1-8989-1b02e96d53a6.png)

</p>
</details>

**Comment by manongjohn** [comment]
You can run through a .desktop file if you set the command as follows:

Exec=bash -c 'cd pathtoTahoma2DFolder && ./Tahoma2D.AppImage'

**Comment by Raiguri** [comment]
It would be much better if this software was in flatpak.

**Comment by Raiguri** [comment]
> I got symlinks and .desktop files confused, a much better solution is to set the .desktop's working path to your Tahoma2D directory.
> 
> Screenshot for reference
> ![image](https://user-images.githubusercontent.com/74428438/190295958-4396eb50-9d7c-40f1-8989-1b02e96d53a6.png)

Im working with different disrtos. And, sadly in gnome file manager there is no Work Path feature
