### ISSUE TITLE
Failed to save Plastic Level after applying Autorenumber option to frames in plastic column.

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#1042]
### Bug Description

I managed to reproduce one of the annoying glitches that cause frames to disappear in Plastic Levels.

### Steps to reproduce

1. Create a new level (the type doesn't matter) and draw some shape. (You can save the scene, by the way)
2. Apply the Plastic Tool to the drawn shape, as a result a new Plastic Level will be formed.
3. Move the first frame in the plastic mesh column down (or up if you didn't create the level in the first frame)
4. Apply Autorenumber to the moved plastic mesh frame. Note that in the Level Strip, the frame has also changed its number (as it should), and an asterisk has appeared next to the level name, which indicates that the level has changed.
5. Try to apply "Save All" or "Save Level" and you will get a warning window about an error in saving the level. If you ignore it and close the scene, then after restarting the scene, the mesh frame will be red.
If you return the frame to its original position and apply Autorenumber again, the level can be saved.

### Software Version

Nightly (Specify below)

### Software Version Information

Built: Jun 7 2022

### Operating System

windows 8.1

### Graphics Card

NVIDIA GeForce 9500 GT

### Drawing Tablet

Huion KAMVAS PRO 20 (2019)

**Comment by manongjohn** [comment]
Strange. Trying to duplicate this, but I crash on step 3 when I click on the mesh frame cell to move it.  Same thing happens for me in OT.

**Comment by manongjohn** [comment]
> Strange. Trying to duplicate this, but I crash on step 3 when I click on the mesh frame cell to move it. Same thing happens for me in OT.

Ah...seems I was low on memory since it was running some other stuff that hogged up the memory and T2D/OT crashed when it tried to create the mesh icon.  Closed the other application and no longer crash.  Need to look into that....

Crash issue aside, I can't seem to reproduce this issue.

**Comment by beeheemooth** [comment]
Ok, I'll wait for the pre-release and see if the bug is still there. It is possible that the bug with the inability to save the mesh level is not directly related to Autorenumber, several times I got an error without resorting to renumbering.

**Comment by beeheemooth** [comment]
I was able to reproduce the glitch with the mesh level saving error also by removing the mesh frames from the Level Strip (apparently the reason is not only in Autorenumber).
Next steps:
1. Create a level with three drawings and save the scene.
2. Select these three frames on the Timeline/Xsheet and apply the Plastic Tool (create a mesh).
3. Remove the second mesh frame from the Level Strip
4. Save the scene.
5. Undo the mesh frame deletion.
6. Save the scene again.
7. Delete the mesh frame again.
8. Try saving the scene again. At this step, I already have a warning window about the inability to save the mesh level.

**Comment by manongjohn** [comment]
I just relooked at this and was finally able to reproduce the original bug and determined the cause.

The problem is when the mesh was created it immediately created the mesh level files in the `+extras` folder. Renumbering it in T2D doesn't immediately renumber the original file so when it tries to save, it fails to find the file under the new name and starts throwing errors.

Will look to fix.
