### ISSUE TITLE
Implicit Hold Issues

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#1055]
### Bug Description

I'm loving implicit holds but have noticed a couple issues:

1. Playback markers & output range don't update automatically. Not sure if this part is a bug or a deliberate decision. Either way, I think it would be more helpful for actions like reframing & adding keyframes to automatically adjust the playback range & output range - unless they've been manually set.
2. Sub-scenes ignore implicit hold frames and only generate the correct number of frames if a drawing exists on the last frame

### Steps to reproduce

For 1:
1. Create a level & draw on a couple frames
2. Use the reframe command set to 2's (or etc.) -> playback markers & output range don't update

or
1. Create a level with a single drawing
2. Add keyframes with the animate tool on several different frames (ie. 1, 10, 50 or etc.) -> playback markers & output range don't update 

For 2:
1. Collapse a couple layers with single drawings & multiple keyframes into a sub-scene 

### Relevant logs/screenshots

Inside a sub-scene:
<img width="547" alt="Screen Shot 2022-11-01 at 10 24 57 PM" src="https://user-images.githubusercontent.com/21159116/199381099-58ceb29a-0c9d-4572-b917-b8a19708e9b2.png">
The result of collapsing the layers:
<img width="293" alt="Screen Shot 2022-11-01 at 10 25 22 PM" src="https://user-images.githubusercontent.com/21159116/199381175-78019ff8-ecd1-4ce6-a314-54b7dfc47547.png">

### Software Version

Nightly (Specify below)

### Software Version Information

June 21st 2022

### Operating System

macOS Monterey

**Comment by manongjohn** [comment]
> 1. Playback markers & output range don't update automatically.

I can't seem to reproduce this.  When I reframe, the markers and output range update accordingly.

> 2. Sub-scenes ignore implicit hold frames and only generate the correct number of frames if a drawing exists on the last frame

When you initially collapse, the frames exposed are based on actual frames. For now, the only work around is to put a stop marker at the last frame in the subscene.  You can still expose subscene frames after the last actual frame and it will show what's there.  Currently the frame appear as if it's missing (red text), but I will be fixing that shortly.

**Comment by artisteacher** [comment]
> I can't seem to reproduce this. When I reframe, the markers and output range update accordingly.

That definitely doesn't happen on macOS. This is particularly an issue when making an animation with just the plastic tool or skeleton tools. My students keep forgetting to update the playback markers and the output settings.

**Comment by artisteacher** [comment]
Never mind, the nightly build seems fine as far as reframing goes. It's just when adding keyframes with the animate tool, plastic tool or skeleton tool that the playback markers/output setting doesn't update. Personally, I think they should.
