### ISSUE TITLE
Smart Raster Smoothing

### ISSUE THREAD

**Issue by adamearle** [tahoma2d/tahoma2d#1103]
**Is your feature request related to a problem? Please describe**
The default pallet swatch in vector and smart raster has smoothing.

**Describe the solution you'd like**
Smart Raster is great Tool for detailing out your flat colors or even shadows. Smooth option here would be great

This setting applied to the Smart Raster tool
![image](https://user-images.githubusercontent.com/16330340/205529028-623d7f92-641c-4d7a-a0b7-bc37c788c3b1.png)

**Comment by manongjohn** [comment]
Added in #1465 and will be in 1.5 release
