### ISSUE TITLE
Download for windows downloads an mac-os image (dmg)

### ISSUE THREAD

**Issue by gonzalovsilva** [tahoma2d/tahoma2d#1106]
### Bug Description

![image](https://user-images.githubusercontent.com/77069600/207095233-328c13f0-d3bc-4cdd-a4db-7ca507914dde.png)

### Steps to reproduce

Go to https://tahoma2d.org/ from a Windows machine and click the Download For Windows button.

### Software Version

1.3

### Operating System

Windows 11

**Comment by manongjohn** [comment]
Apparently we corrected 1 set of links but not another.

It should be fixed now.

Sorry about that.

**Comment by gonzalovsilva** [comment]
Thank you.
