### ISSUE TITLE
 Changing Rooms

### ISSUE THREAD

**Issue by go2t** [tahoma2d/tahoma2d#1109]
### Bug Description

whenever I go to File/preferences/interface, there is no rooms dialog to change my rooms and I need to change my rooms.

### Steps to reproduce

in File/preferences/interface, can you place a rooms option?

### Software Version

1.3

### Operating System

Windows 11 10.0.22000 Build 22000

### Graphics Card

High performance

**Comment by go2t** [comment]
I really need to change my room

**Comment by manongjohn** [comment]
T2D currently only comes with the Default set of rooms, unlike OT which has 2, so there isn't another set of rooms to change to.

While this option may be available in a future release, you have 2 options for now:

1. Add/modify your existing rooms to suit your needs.
2. If you have a room set from somewhere else, do the following:
    - Close down T2D
    - Go to folder `Tahoma2D\tahomastuff\profiles\users\layouts\Default`
    - Backup (preferred) or remove everything in the Default folder
    - Drop the other room set in the Default folder
    - Restart T2D
