### ISSUE TITLE
Return icons in the menu?

### ISSUE THREAD

**Issue by MonSeneor** [tahoma2d/tahoma2d#1110]
I noticed that unlike OpenToonz, Tahoma2D does not have icons in the menu, instead there is an empty space.

I could assume that this was done for convenience or something similar, but I think the version with icons was perceived much better. So can we return the display of icons and the ability to disable them in the settings if necessary?

OpenToonz:
![image](https://user-images.githubusercontent.com/120468377/208056041-e6c35962-c797-421d-a2dc-f08226bff1b1.png) ![image](https://user-images.githubusercontent.com/120468377/207332534-b40190e6-c236-4606-86e4-34da3a43bb91.png)

Tahoma2D:
 ![image](https://user-images.githubusercontent.com/120468377/208056122-23766352-3f83-4c1d-8019-73a80058a74f.png) ![image](https://user-images.githubusercontent.com/120468377/207332981-16521c16-3786-41df-95ff-fc7d205601b7.png)

**Comment by artisteacher** [comment]
I think the checkboxes are better in terms of consistency. They also make it very clear what is checked. 

On the other hand, the icons might make the purpose of each check just a bit clearer.

**Comment by manongjohn** [comment]
The lack of menu icons is a stylistic choice. I find all those icons make the menus look unnecessarily busy.  The lack of icons makes it seems simpler and pleasant looking jn my opinion. Stuff that needs to stand out just do, like the checkboxes.  Other applications that I use are similar. They have very few to 0 menu icons.

Fret not...I am currently working on a new Preference to `Show Advanced Preferences and Options`.  This will unhide a number of preferences and UI controls that are normally visible in OT. Included in that is the preference to show icons in menus (off by default). 🙂
