### ISSUE TITLE
Crash when importing video 

### ISSUE THREAD

**Issue by Marirarius89** [tahoma2d/tahoma2d#1132]
### Bug Description

The software crashes when I try to import a video for reference while rotoscoping. I imported a regular mp4 video.

### Steps to reproduce

I tried in several different projects and the bug appeared every time. 

### Software Version

1.3

### Operating System

Windows 11

### Graphics Card

3080 mobile

**Comment by manongjohn** [comment]
Are you able to provide the mp4, either here or privately if preferred, so we can see what might be causing it?

If there is a crash log/dump file that might have been created would be useful as well.

**Comment by Marirarius89** [comment]
Thank you for replying so quickly. I do not know how to retrieve the dump file. The error message said something about it not being able to write memory. How do I share the video with you? I just recorded a walk cycle on YouTube with OBS. Regular screen recording. Edited it a little in KDenlive and exported as mp4 1920x1080 resolution.

**Comment by artisteacher** [comment]
Does it actually crash or does it just hang?  The processing capabilities of the computer seem to have a big impact on video loading into T2D. Some computers definitely handle it better than others. 

On the old computers at work (which were replaced), there could be a significant delay when loading video into T2D. The video always loaded eventually - if I was willing to wait long enough. Sometimes the wait was crazy long. The newer computers have better processing so this hasn't really been an issue recently.

**Comment by Marirarius89** [comment]
The program crashes and closes down. I have a pretty new laptop with a 3080
GPU and i7 CPU, so it should be able to handle it. I am able to import
video into OpenToonz without issue. Really enjoy Tahoma though, clean
interface and just a very nice experience, so would love it if we could
figure out what causes it. I have tried with several videos now and the
same bug occurs. I thought I might try some different video formats to see
if that has an impact, but have not had the chance to do that yet.

ons. 15. feb. 2023, 04:15 skrev artisteacher ***@***.***>:

**Comment by manongjohn** [comment]
> How do I share the video with you?

If you dont have an issue sharing it publically, you can post it in a comment in this thread. May need to zip it up. If cant upload here, you can provide a link to download it from somewhere. If you need to share privately, you can always hop onto the Tahoma2D Discord and DM me the video or a link to it.

**Comment by manongjohn** [comment]
Oh...you can find the crashdump file in the following location: C:\Users\yourusername\AppData\Local\Tahoma2D\Tahoma2D\cache\crashrpt\xxxx\crashdump.dmp

**Comment by Marirarius89** [comment]
[crashdump.zip](https://github.com/tahoma2d/tahoma2d/files/10745803/crashdump.zip)


[crashdump.zip](https://github.com/tahoma2d/tahoma2d/files/10745802/crashdump.zip)

[walk.zip](https://github.com/tahoma2d/tahoma2d/files/10745785/walk.zip)

**Comment by Marirarius89** [comment]
I updated OBS, recorded a new video and imported it into Tahoma 2D. With
the new video, after updating OBS, Tahoma did not crash. I will do some
more tests and keep you posted.

ons. 15. feb. 2023 kl. 07:16 skrev manongjohn ***@***.***>:

**Comment by manongjohn** [comment]
Ok...I don't know the exact cause yet, but using "Load" works fine but crashes when I try "Import".   Likely because the file is being copied first to the Project\extras folder, T2D may be trying to access it when it hasn't been fully released by the OS.

Once it's in the extras folder, you can use Load Level to load the mp4 without a problem.

There was a change to the way ffmpeg runs in v1.3 that I believe might be causing this.  I can "Import" the file in v1.2 without issue, though it is slower.  I'll need to figure out why it's doing this.

**Comment by Marirarius89** [comment]
I see. Thank you. I did try load, but then the bug appeared next time I tried to open the project with the mp4. The project would not load for me at all after that.

**Comment by artisteacher** [comment]
For now, you could try loading the level and then merge it with a blank raster level with the same number of frames. Then delete the video from the timeline & "remove unused levels" from the scene cast.

**Comment by Marirarius89** [comment]
Thank you. That worked well for me. The issue is solved on my end. Love
working with Tahoma 2D! Keep up the great work :-)

ons. 15. feb. 2023, 23:26 skrev artisteacher ***@***.***>:

**Comment by Marirarius89** [comment]
I have been doing some more testing and I am sorry to say that the program always crashes when I try to open a project where I imported an mp4. Hope this gets fixed soon...

**Comment by artisteacher** [comment]
That's why I'm suggesting merging the mp4 with a raster level (after you load the mp4) & then completely removing the mp4 from the scene. As long as you can merge without a crash and remove the mp4 from both timeline and scene cast, you should be able to reopen the scene without issue.

**Comment by Marirarius89** [comment]
That worked. Thank you!
