### ISSUE TITLE
Build dec 2022 doesn't recognize my DSLR camera even though in build August 2022 yes.

### ISSUE THREAD

**Issue by charliemartinez** [tahoma2d/tahoma2d#1133]
### Bug Description

Hello,
Tahoma2d build August 14, 2022 recognizes my canon 600D (Rebel T3i) although the December 2022 build downloadable from the official page no longer recognizes it :-(

### Steps to reproduce

1. Download https://github.com/tahoma2d/tahoma2d/releases/download/v1.3.1/Tahoma2D-linux.tar.gz
2. Extract files
3. Run the .appimage

### Software Version

1.3

### Software Version Information

1.3.1

### Operating System

Debian 11 (Bullseye)

**Comment by manongjohn** [comment]
I think you might have been using a nightly or a PR build which had libgphoto2 support.

V1.3.1 is a fix release based on the original V1.3 release, both of which do not have Libgphoto2 support. Libgphoto2 support is a new feature for the 1.4 release sometime this year.

Download the latest nightly which is 1.3.1 + new stuff for 1.4.

**Comment by charliemartinez** [comment]
That's right, sorry, you're right: since the version of the August 2022 build shown is 1.3, I thought that 1.3.1 would have already added Libgphoto2 support. I close the issue. Greetings.
