### ISSUE TITLE
Crash when reframing.

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#1143]
### Bug Description

This crash happens in the Xsheet and in the timeline.

### Steps to reproduce

1. Create a new level (of any type) and move the frame a few cells lower (you can also create a level directly in the cell you need).
2. Highlight the frames so that the cells above the level you created are also highlighted.
3. Apply any "Reframe" option.
4. Crash.

![ezgif-5-f0639abde7](https://user-images.githubusercontent.com/25724133/223516572-cde77653-8b3d-47b7-be3f-5ed5779d7d3a.gif)

### Software Version

Nightly (Specify below)

### Software Version Information

Built: Feb 28 2023

### Operating System

windows 8.1

### Graphics Card

NVIDIA GeForce GT 1030

### Drawing Tablet

Huion KAMVAS PRO 20 (2019)

**Comment by artisteacher** [comment]
I get a crash too on macOS.
[reframe.txt](https://github.com/tahoma2d/tahoma2d/files/11062123/reframe.txt)

**Comment by manongjohn** [comment]
Issue related to implicit code. Will be fixed in #1167.
