### ISSUE TITLE
Support Krita Brushes

### ISSUE THREAD

**Issue by gitbugr** [tahoma2d/tahoma2d#1148]
OT/Tahoma are somewhat lacking in the brush department. Brushes, including the mypaint brushes, seem to be little vector ovals that are rendered to raster with a load of parameters to make them achieve a certain effect. This works well enough from afar, but up close, or at larger brush sizes, this is not great.

![image](https://user-images.githubusercontent.com/6732567/227773524-6090f6b1-e41d-4870-9758-231efb08458e.png)

At the very least relative to comparable software such as Krita.

![image](https://user-images.githubusercontent.com/6732567/227773751-6992d150-69f0-4a89-b2ce-f956d811fd30.png)

Krita at least partially supports gimp and photoshop brushes, and there are so many community made brushes that are available. 

I've seen [a previous OT issue](https://github.com/opentoonz/opentoonz/issues/1183#issuecomment-300479853) in which some people expressed dissaproval of the idea of bringing in photoshop brushes as OT is not primarily a painting program. While I understand this perspective, I disagree completely. The brushes for animation software are incredibly important for style, particularly with regards to outlines and effects. Supporting the krita brush engine wouldn't bring it in line with software like ArtRage, which is very sophisticated and intended for painting - but it would give us substantially more options when it comes to style. 

[There has been some discussion on merging the two software](https://github.com/opentoonz/opentoonz_docs/issues/142) as they're both QT based applications and overlap quite a bit, however it's not obvious how/why that should be done, on top of concern over licencing - despite that, Krita's [GPL licence is compatible with the 3-clause BSD licence](https://www.gnu.org/licenses/license-list.en.html) used by OT/Tahoma, so I think it would be possible and very beneficial to support these brushes.

![image](https://user-images.githubusercontent.com/6732567/227773935-7298f6d7-a0eb-4305-b764-608860ebb51e.png)

I'm not a C++ developer (very little and outdated experience) and I'm also not very familiar with either codebase, so I'm not sure I'd be able to undertake this task (at least not without a lot of hand-holding..).

Upon a cursory look, the brush engine (paintops) is nicely sectioned away in the [the plugins directory](https://invent.kde.org/voronwe/krita/-/tree/master/plugins/paintops) and the library for managing brush resources (libbrush) is stored in the [lib directory](https://invent.kde.org/voronwe/krita/-/tree/master/libs/brush)

I imagine, despite feature being essentially a port, it would be a fairly large undertaking, involving new UI to accomodate brush settings and such. I'm also not quite sure how smart raster levels work under-the-hood, so that might be a sticking point.

**Comment by manongjohn** [comment]
Although GPL and BSD-3 are technically compatible, GPL confirs some additional requirements that OT (and by extension T2D) does not want. At least that is how it was roughly explained to me. Therefore we do not directly incorporate anything with GPL licenses.  LGPL is little easier to deal with.

As much as I would love to incorporate a better brush system, i can't. 🙁

**Comment by gitbugr** [comment]
Thanks for the reply manongjohn, but aw, that is very unfortunate. 😞

**Comment by gitbugr** [comment]
@manongjohn Do you know if GPLv2 would come with the same requirements that OT/Tahoma seeks to avoid? Krita itself is licensed under GPLv3, however those files are licensed under GPLv2 or later (which does not bring with it the further restrictions included in GPLv3.)

**Comment by manongjohn** [comment]
I'm not sure what the differences are between 2 and 3. I am not a license expert and i dont recall what in a GPL license OT had an issue with, so I think we just avoid GPL altogether.

Not sure why we allow LGPL.

**Comment by gitbugr** [comment]
Hmm, I could create a discussion issue in the OT repo to see if shun or anyone privy could clarify? Would be very useful for, not only the possibility of this feature, but for any kind of future development that may involve the usage of other libraries.

**Comment by gitbugr** [comment]
@Bracket-H 

My proposal is not intended to be read as "bring painting to OT/Tahoma2D", rather, to bring in a better brushset, particularly for raster (stamp, texture, etc.) for stylisation, mostly when it comes to linework.

Painting backgrounds in Krita and bringing them over to OT/Tahoma2D is a piece of cake, not an unreasonable workflow. But if you want to use nice pencil brushes, etc. then drawing in Krita is not really an option, unless you want to totally dedicate yourself to animating in Krita, and lose all the lovely features in OT/Tahoma2D, or have a painful time moving your frames with timing etc back and fourth...

**Comment by gitbugr** [comment]
Hmm, I see what you're saying, and I can imagine ways to post-process lines and give them some texture, though that's not quite as intuative and I think would be quite limiting in some respects. 

Oldschool is very much my vibe and I also love the cel look haha, though I think there are some styles that would be quite difficult to achieve when a decent textured / stamp / air-brush would make the process so much simpler.

A modern example could be the Wolfwalkers, which is animated in a very pencil-test, sketchy way;

![Wolfwalkers still](https://ca-times.brightspotcdn.com/dims4/default/6b4f622/2147483647/strip/false/crop/5400x2919+0+0/resize/1486x803!/quality/80/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F32%2F81%2Fb6f86d064721865113404c9b0dce%2Fwolfwalkers-photo-0110.jpg)

Or Loving Vincent (an admitably unfair comparison / expectation of reproducability)

[![Loving vincent](https://variety.com/wp-content/uploads/2018/01/loving-vincent.jpg)](https://youtu.be/CGzKnyhYDQI)

There are also some old animated films which I believe would be easy enough to produce with a proper brushet, but difficult to achieve the desired effects without.

**Comment by gitbugr** [comment]
> Yes, but if Krita brushes work in opentoonz, then they also work in Krita.
>
> Here's what you can do, if, due to that licensing thing it will never happen:
> ...

You're right, and that's a workaround I'll need to deal with 😅

> I really don't want to just give you a hard time here, but OT with Krita brushes would not be that much of an improvement.

Feel free to give me a hard time lol, I do disagree, I think it would be a decent improvement but I do acknowledge it's other problems. I just feel like brushes are such a fundamental part of a 2D animation software, which is why I think separating the drawing/painting capabilities of Krita and OT/Tahoma into "each having their own strengths" is not really a fair perspective. Animation (at least frame my frame) is fundamentally a load of drawings you play in sequence. For character rigs, drawing in a different software is fine, for backgrounds, even more fine. When it comes to drawing the things that move, I feel like minimising your production pipeline is the idea. The only real difference is context.

Issues with the smart raster levels are, I feel, a solvable problem, and smart raster levels do just that, minimise your production pipeline. Recolouring suddenly becomes very easy.

> They use 'garbage' brushes too in digital timing/layout, as well as actual traditional roughs, which I assume they all paint over in a dedicated program, unless Toonboom is more flexible than I thought, but ...that's also proprietary software.

They use TVPaint, which is a (proprietary) animation software famous for is powerful brush, but I digress

**Comment by manongjohn** [comment]
My 2 cents...

I do understand that each software has their strengths and weakness and to get what you need may require multiple software.

Personally I prefer to do as much as I can in 1 application as possible. For most of my novice animation needs, when I do animate, I'm ok with what T2D has and dont really need to use other software. I know others need more.

When OT first came out, the original brushes were...well...horrible, in my opinion and I dont even have a lot of digital drawing experience to begin with.   The addition of MyPaint was a welcomed changed though obviously no where near other painting programs, but i think part of that was lack of common drawing features to go along with MyPaint brushes. Still, MyPaint was a significant improvment in comparison to the original brushes.

In general, OT/T2D's brush handling leaves a lot to be desired and has its own issues. I would love to completely redo the brush engjne if I had time and wherewithal to do it.  That is potentially a significant amount of work and there are other issues that require focus first.

Unless Krita changes the licensing on it's brush engine to LGPL, we can only try and improve what we currently have and add in missing drawing features to improve the drawing experience in T2D.

**Comment by gitbugr** [comment]
@manongjohn
I agree completely. I was hoping that using Krita's engine would be possible to use as we'd be able to use the community-made brushes and wouldn't be adding to the endless standards of competing filetypes, but damn, the licensing issue sucks. I wonder how far off the current brushet are from a decent level of improvement. MyPaint seems to work by pasting in a load of vectors like stamps, it would be great if it was possible to use PNGs instead, and if there was a way in-app to create brushes?

@Bracket-H 

> again ever since I added Natron to my workflow, and its VFX nodes, including anti aliasing, but not limited to it, I am fully on the "multiple programs train

I use Natron too, and it's pretty great - I think that's a more fair example though. It doesn't feel like such a break in the pipeline as it pretty much always happens at the end, etc. Sometimes when animating you skip the rough stage (for inbetweening for instance), some simple effects, retiming and needing to fill in some extra frames, etc. Going to then go through that process of export to PNG, move to Krita, etc. it's a time-sink in something where small time-losses naturally compound.

> But then again, I only care about consistent, and traditional looking lines, not fancy painterly ones that would boil and bubble when animated.

See, I'm a fan of the old boil lines haha!

> The dream would be "Krita as a Qt Panel", a bit like neovim tries to be something that can be plugged into different GUIs.
>
> Wouldn't it be cool to have Krita as an optional viewer in "paint mode"?
Modifying the same data as before, in toonz, but now the Krita painting interface does it?
> That would be ideal, imho, for those who want that look (again ever since I added Natron to my workflow, and its VFX nodes, including anti aliasing, but not limited to it, I am fully on the "multiple programs train)
>
> ...
>
> When I liken it to a server, I don't mean TCP/IP/Internet protocols, I mean actual shared memory that all applications can use as it if were a real resource in their core engine. Surely that must be possible. Surely ...
> MAybe not easy to make, but ...it's all just data, suuuuuurely it could be shared. Ssuuuuuhuurururuhelyyyy... unless computers are more limited than I thought.

I'd love that also! Though... Memory is isolated between applications by an OS I believe, so I think it probs would need to somehow be copied back and fourth rather than sharing... Unless there's some QT magic I'm unaware of that will allow you to do as you said and embed Krita in the application upon clicking an "Edit in Krita" if installed..

On the copying data front, would probably require a Krita plugin to take the pixels of each layer and send them to OT/T2D (but OT/T2D would need some way to handle it). Looks possible from my brief looksee: https://api.kde.org/krita/html/classDocument.html#abda324b9beee9384879af8b7e7807cfa

**Comment by gitbugr** [comment]
> If you "skip entire stages of production" then you're so good that you don't have to do the switch between toonz and Krita, you can do it all in Krita and then just time it in toonz later on.

M'kay, I think you misunderstood - I don't skip an entire stage of production, I did clarify "for inbetweening for instance". I don't think it is entirely uncommon to go straight into drawing simple inbetween frames without a rough using only onion skinning as your aide? I've certainly seem other animators do it.

> But you can hopefully see something in this last paragraph. What about the claymation people? Why have them photograph their work painstakingly and arrange the imagines in a timely sequence in toonz when it also could have a state of the art, zbrush type engine?

I mean, OT/T2D does cater for claymation people? There's a stop motion room that hooks up to your camera for that very thing. It doesn't ask you to go into another program and take your photos "because the other program's strength is taking photos", then import them... I don't think Zbrush is the analagous software here - this isn't about switching mediums. I mean, going back to the studios' usage, Toonz was initially made to make the jump from traditional to digital much easier. It didn't offload scanning in drawings to DragonFrame because "that's it's strength" to be manually pulled into Toonz to cleanup and colour... It's always about minimising the pipeline where it makes sense.

> Put everything into toonz, then it also needs sound editing, and not just simple editing, gotta have fancy convolution to simulate 3d rooms, multi track mixing, VSTs (so you can time music to the animation and not the other way around)
> 
> then integration with publishing platforms, a physical media pressing suite (why switch to a burning program? what if you want to just hand someone at college your quick test and the network is currently broken?)
> 
> Am I going to far now with the "hard time" I should give you? :P I mean, after all, in a way, it would be totally dope to have that all in toonz.
> 
> But...y'know. Things work as they are right now.

Lol, not far enough. :P I mean, sure. But again, does that minimise the pipeline? Not much. Replacing the audio is a one-and-done thing, not saving much time there. Does that mean that OT/T2D shouldn't have any audio features because it's not it's "strength"? No - you gain so much from having that ability, not only is it useful for timing your animations with sounds or lip sync, but tools around it have been built like using Rhubarb for auto-lip-sync.

The context of it's usage means you can built tools around these things. Smart raster levels, while not currently working well with painterly brushes, is a great idea that only makes sense in a 2D animation software, not a drawing/painting-only software.

There are also things that make sense in drawing/painting software that don't make sense in animation software - like colour models for print media, many file formats, image filters - In fact, I think you could probably make a better case for offloading much of the effects to a compositing software like Natron than brushes, though even then, things like masking in shadow are much easier when you have the tool right in front of you to preview and check while you're in the middle of it, rather than exporting and doing in Natron later. That would be quite annoying.

**Comment by manongjohn** [comment]
> Ah, again, annoyed at this. I don't think you know what you're talking about at all regarding this (I agree that python would make a better toonzscript, though)
> 
> So I'm just gonna call you out clearly on it.
> 
> What do Krita brushes do for you? Please outline your exact workflow here. Cause holy crap you're being obtuse on purpose.

I get that people don't always see eye-to-eye and agree on things, that people get passionate about certain topics and, that we all have different experiences from which we base things off.  I find these comments a bit rude and insulting.  No need for this.


As for the discussion...

I don't think it was ever clear how Studio Ghibli used OT when it was first made open source.  I think people were really hoping this would replace Flash/Adobe Animate, expecting to draw and animate directly in it.  For many, it fell WAY short of expectations and left a lot of bad impressions with potential users. Stability and other issues pretty much killed the remainder of the initial interest in OT.  The few developers that see potential in OT have since then been trying to improve and enhance it to meet what people are expecting of the software.

Having said that...can we not desire for OT to have a decent and robust brush engine so we don't have to switch programs?   How would Adobe Animate, TV Paint, CSP be regarded if they only had MyPaint brushes (no offence to MyPaint owner) or even the original OT brushes to go along with their animation feature? I see nothing wrong with wanting to improve the brush engine in T2D.  People often complain about drawing in OT, hence the need to go elsewhere.  What is wrong with wanting to change that? We may never reach the caliber of Adobe Animate, but we can always strive to get closer.

I have been trying to fill in some missing drawing features that people expect to have at hand when drawing.  Perhaps that is all in vain?  I don't think it is.

Is part of the issue that people are used to certain brushes in different drawing software and want to be able to use it in OT? I've often seen questions about how to get CSP brushes, Adobe brushes, Krita brushses in OT....as we can't import those directly, people wonder how to recreate those brushes in OT.  At least with MyPaint brushes, if you spend time with it in MyPaint or in OT, you can likely create a brush similar to what you are used to. Can't say that with the original brushes.

To Bracket-H's point...

If, for argument's sake, Krita were to change license tomorrow, what do Krita brushes offer that MyPaint brushes do not?  What benefits are gained by switching to Krita's brush engine?  It would need to be compelling enough to warrant replacing MyPaint.  Keep in mind that MyPaint or Krita brushes are really meant for Raster levels where you can have a more painterly style.  Direct blending with these brushes would not possible in Smart Raster levels and is reduced to just line coloring for Vector levels.

On the flip side, what can we improve now with MyPaint brushes to make it somewhat comparable? Granted, certain improvements likely need to be done in MyPaint source. Maybe some of the issue is the MyPaint integration into T2D needs work?


I am not a professional animator. These days I primarily develop, so I'm less than even a novice animator.  I animate vicariously through users of T2D.  :) So feel free to call me out on anything that I have misstated and educate me or agree to disagree.  It would be appreciated if rude comments/insults are left out ;)

**Comment by gitbugr** [comment]
Yeah things are a little heated so let's defuse a little. I don't take these things to heart so don't worry, and feel free to give me a hard time as I said, but don't let yourself get _actually_ annoyed over my dumb feature request and perspective. I am just a random guy on github. Chill.

Not sure if I should keep this going, but here's the bullet point answers to your questions;
* on Zbrush: I'm not saying traditional animators should use OT/T2D instead of pencil and paper though. Emulating the effect is my goal, I don't expect those who want to keep with the traditional methods to migrate to digital.
* My workflow depends on what I'm animating. Usually it's board, voice, rough, cleanup, colour, effects. Depending on the scene I'm doing, I may switch it up or cut corners. Clean up some keyframes before I finish the rough for the entire scene, I'm an indie animator. I did my degree in animation. I don't work in a studio, I have one or two other people who I work with.
* On onion-skinning: Yep, on simple inbetweens. I have just been thinking about the many things I do sometimes that may conflict and become annoying if I'm jumping back and fourth between two pieces of software. Yes, I'm aware of rolling, favouring drawings, arcs, etc. 
* What do I think Krita would give me? More options with less headache. I like to experiment with style. 

I have almost certainly overstated how "important" a feature like this is, but put simply, I just think it would be neat. I've found myself lost in the possibilities, and imagine it'd be very nice to not have to jump between programs.

@manongjohn 

Well, Krita's brush engine supports MyPaint, so there wouldn't be anything lost in this scenario, only gained.

Iirc, smart raster levels only produce artifacts when mixing colours on the same level? For my usage, this is workable, as the most useful feature for me w/ smart levels is recolouring across frames and I was never envisoniaging painting/blending colours, though perhaps others would be.

I'm a pretty tired right now, so forgive me for not coming up with better examples, I'll post some more tomorrow if it helps, but the first thing that comes to mind right now outside of linework is smears.

![image](https://user-images.githubusercontent.com/6732567/231032017-7fe867d6-a257-43ea-946e-637f63ca7241.png)

**Comment by manongjohn** [comment]
I just deleted Bracket-H's last 2 message and blocked him from this group.  Sorry it had to go that far, but I will not have any posters attacked like this. This behavior will not be tolerated.

**Comment by gitbugr** [comment]
@manongjohn S'all good. I get it, we disagree on this, clearly both feel strongly in some form. I think it needlessly devolved and I feel words were being put in my mouth - but either way this is very unlikely to happen due to the licensing issue. This was all hypothetical and outlived this issue. Thought the bridging Krita/T2D thing was a good idea though, maybe that can be made possible in future.

Probs best to close this ticket until something changes, I doubt it's a productive use of time continuing to debate something that can't happen lol
