### ISSUE TITLE
URGENT I Can't open file "There were problems loading this scene some files may be missing"

### ISSUE THREAD

**Issue by Smalfry64** [tahoma2d/tahoma2d#1152]
### Bug Description

I was using a nightly release of tahoma2d and it was bugging out quite a bit, so I deleted the app and reinstalled the official release. Even though my project and scene files were saved in my documents during deletion, I couldn't open a project I had been working on for a whole week. I'm afraid I may have deleted most of my work and might not be able to retrieve it. pls I need urgent help (I have to submit the project as my portfolio in 3 days)

### Steps to reproduce

1. create scene on nightly build of tahoma2d 
2. uninstall the application
3. install official release of tahoma2d 
4. open the same scene created

### Software Version

Nightly (Specify below)

### Software Version Information

I can't remember clearly, somewhere around 25-27 march

### Operating System

MacOs ventura 13.2.1

### Drawing Tablet

Huion Kamvas 13

**Comment by manongjohn** [comment]
The reason that might happen is you used something in the nightly that isnt supported in the official release.

You'd need to open it in a nightly, remove whatever new features you might have used in the nightly and and resave it.

If you reinstalled the nightly, can you still open it? If not there is a possibility the scene somehow got corrupted.

Without an attached scene, I cannot tell what might be wrong.

Note: The assets (level) files are likely ok, so at worst case, probably need to load the levels into a new scene and redo the timing/animation portion.  Would likely need to do this if the scene file somehow got corrupted.

**Comment by Smalfry64** [comment]
> The reason that might happen is you used something in the nightly that isnt supported in the official release.
> 
> You'd need to open it in a nightly, remove whatever new features you might have used in the nightly and and resave it.
> 
> If you reinstalled the nightly, can you still open it? If not there is a possibility the scene somehow got corrupted.
> 
> Without an attached scene, I cannot tell what might be wrong.
> 
> Note: The assets (level) files are likely ok, so at worst case, probably need to load the levels into a new scene and redo the timing/animation portion. Would likely need to do this if the scene file somehow got corrupted.

PHEW Thank you so much💀 I reinstalled the same nightly release and it worked. somehow didn't cross my mind to do that. 🤦‍♂️ One last thing, is it possible and if so, how would I get the file to open on the official release? I've found the nightly build to be quite buggy at times. Also I'm unaware of any new features preventing me from opening the scene.

**Comment by manongjohn** [comment]
I believe there were some OT ports to T2D that are in the nightlies that alters the scene files which might be preventing it from opening in the official release.

I would need the scene file to see what might be preventing it from opening.  If you can share it, i can look to see what it is. If you need to share it privately, you can join the Discord and DM it to me directly.

**Comment by manongjohn** [comment]
Out of curiosity, what in the nightly was buggy enough to prevent continued use?

**Comment by Smalfry64** [comment]
> Out of curiosity, what in the nightly was buggy enough to prevent continued use?

Its a little hard to explain through text but I'll try.

- while toggling between frames, a small square containing an adjacent frames drawing would suddenly appear on another frame, its weird but irreversible. Basically puts a sticker of another frame over my drawing and have to redraw, is v annoying.
- performance issues, not sure if it's the same with the official release but my app would just hang (macOS spinning rainbow) sometimes out of nowhere or when dragging playhead to denser sections. It runs fine after that but it is annoying
- frequent crashes, it never fails to do so

**Comment by Smalfry64** [comment]
> I believe there were some OT ports to T2D that are in the nightlies that alters the scene files which might be preventing it from opening in the official release.
> 
> I would need the scene file to see what might be preventing it from opening. If you can share it, i can look to see what it is. If you need to share it privately, you can join the Discord and DM it to me directly.

Sure I wouldn't mind sharing the file, can't seem to send the file type here so I'll do it thru discord
