### ISSUE TITLE
Nightly build missing library crash

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#1154]
### Bug Description

The latest nightly build crashes on open in macOS due to a missing library.

### Relevant logs/screenshots

[missing-library.txt](https://github.com/tahoma2d/tahoma2d/files/11195064/missing-library.txt)
<img width="806" alt="Screenshot 2023-04-10 at 9 01 36 PM" src="https://user-images.githubusercontent.com/21159116/231028381-bde988cf-57c7-4cd3-ad63-c8a9e5d2bcfb.png">

### Software Version

Nightly (Specify below)

### Software Version Information

4/7/23

### Operating System

macOS Ventura 13.2.1

**Comment by manongjohn** [comment]
@artisteacher  When I downloaded the nightly and inspected the contents, I didn't see the library it was looking for.

After rebuilding the nightly again and inspecting the contents,  I see the the missing library.

Can you download the latest nightly and check?

**Comment by artisteacher** [comment]
Still getting a crash. It looks like T2D is looking in the wrong place:
<img width="514" alt="Screenshot 2023-04-12 at 11 47 04 PM" src="https://user-images.githubusercontent.com/21159116/231645035-060e41b6-bfdf-47c2-b9a4-947bbd6d9365.png">
The library is directly in Frameworks, not in a sub-directory. I think there have been problems with rpath before and switching to an executable path solved the issue - ie. #99
