### ISSUE TITLE
It's not show all tool option bar 

### ISSUE THREAD

**Issue by yoki12345** [tahoma2d/tahoma2d#1157]
### Bug Description

I don't know how to fix it properly. It happened when I opened the program for the first time.

Brush tool : cannot adjust the size of the fine brush according to the decimal value and does not show draw order, including Eraser tool
![Tahoma2D pen](https://user-images.githubusercontent.com/132809690/236665863-c9f49539-c78e-445e-8570-8b0632927264.png)

Fill tool :not show Type ,Mode ,Gaps, Auto paint line
![Tahoma2D fill](https://user-images.githubusercontent.com/132809690/236665912-63f54c50-a35e-4873-8fe0-92657467a126.png)

Please help me and thx you

### Steps to reproduce

-

### Software Version

1.3

### Operating System

window 11

### Graphics Card

NVIDIA GEFORCE GTX

**Comment by manongjohn** [comment]
The default level type is standard `Raster`. Some of the options you are mentioning are for `Smart Raster` levels.

Either create a `Smart Raster` level first or, change the `Default Level Type` in `Preferences`.

**Comment by yoki12345** [comment]
THX You so much!!! I can fix it now💕💕💕
