### ISSUE TITLE
Reframe when Camera Track Selected Causes Crash

### ISSUE THREAD

**Issue by rontarrant** [tahoma2d/tahoma2d#1163]
### Bug Description

Not technically a bug since (obviously) Camera tracks can't be (or aren't supposed to be) retimed, but still...

If the user has a camera track selected and hits one of the Reframe buttons, this results in a catastrophic crash and the loss of all work.

A warning dialog would be nice... as well as—needless to say—not allowing the crash.

### Steps to reproduce

To reproduce:

- create a series of frames,
- select them all as well as any frame on the Camera track (or just the frames on the Camera track),
- click on one of the reframe buttons in the timeline toolbar.

### Relevant logs/screenshots

[CrashRpt-Log-20230525-075505-{ae8b21f2-91d2-4abb-a069-6543ab995a48}.txt](https://github.com/tahoma2d/tahoma2d/files/11564468/CrashRpt-Log-20230525-075505-.ae8b21f2-91d2-4abb-a069-6543ab995a48.txt)

### Software Version

1.3

### Software Version Information

v 1.3.1 (Dec 8, 2022)

### Operating System

Windows 10 21H2 19044.2965

### Graphics Card

GTX 980M

### Drawing Tablet

none

**Comment by artisteacher** [comment]
I get the same on macOS.

**Comment by manongjohn** [comment]
Issue related to implicit code. Will be fixed in #1167.
