### ISSUE TITLE
The Multiply effect doesn't work with implicit holds

### ISSUE THREAD

**Issue by DarrenTAnims** [tahoma2d/tahoma2d#1186]
### Bug Description

Using the Implicit holds, the multiply effect works on the frame with the drawings, but not on the following frames, with implicit holds.
I've attached a project showing how the multiply effect compares to the Matte In effect, which should give the same results, to show a shadow over the circle.
[MultiplyBug.zip](https://github.com/tahoma2d/tahoma2d/files/11970820/MultiplyBug.zip)

### Relevant logs/screenshots

![Frame1-MultiplyWorking](https://github.com/tahoma2d/tahoma2d/assets/28575907/f185b3f6-c8c5-43c0-b4e1-dfd0792556b6)
![Frame2-MultiplyNotWorking](https://github.com/tahoma2d/tahoma2d/assets/28575907/e976a0bf-a67b-411b-a1d0-f905cb983841)

### Software Version

Nightly (Specify below)

### Software Version Information

V1.3.1 May 17 2023

### Operating System

Windows11

### Graphics Card

NVIDIA GeForce GTX 1650 SUPER

**Comment by artisteacher** [comment]
Try adding stop frame holds to layers using multiply. Then the implicit frames should display properly with preview on.
