### ISSUE TITLE
Graph Editor / Timeline Interpolation / Adobe Flash Brush Tool !!

### ISSUE THREAD

**Issue by Rodoxdexts** [tahoma2d/tahoma2d#1188]
I want an advanced timeline / And an adobe flash vector brush!

I'm always frustrated when i have to edit interpolation in the timing view.

**_I want the graph editor in the timeline!
And a brush tool like adobe animate!_**

This helps a lot

Thanks

**Comment by artisteacher** [comment]
It might be helpful to explain in more detail what this looks like in Flash/Animate and how you would execute it in T2D. What does the vector brush do differently? What would the advanced timeline look like?

Just an FYI, if you unlock the workspace (top right lock icon), you can add additional docked panels. So you can have the graph editor in a different room, if that is helpful for you.

**Comment by manongjohn** [comment]
I am a visual person, so having difficulty understanding what/how this works based on the description you provided.

Is there a short video you can link to of what you would like to see?

**Comment by Rodoxdexts** [comment]
https://youtu.be/HG71FQVoCEI?si=wlwKBLE_UjyWG7zx

**Comment by Rodoxdexts** [comment]
Sorry guys
