### ISSUE TITLE
Shortcuts for changing Plastic Tool modes do not work.

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#1225]
### Bug Description

The following options for the Plastic Tool can be assigned shortcuts, but they do not work:

1) Animate
2) Build Skeleton
3) Paint Rigid
4) Edit Mesh
5) Next Mode

### Software Version

Nightly (Specify below)

### Software Version Information

Built: Sep 28.2023

### Operating System

windows 8.1

### Graphics Card

NVIDIA GeForce 9500 GT

### Drawing Tablet

Huion KAMVAS PRO 20 (2019)

**Comment by artisteacher** [comment]
This is an issue on macOS too.
