### ISSUE TITLE
Explode Sub-Scene crashes the program

### ISSUE THREAD

**Issue by BertWik** [tahoma2d/tahoma2d#1228]
### Bug Description

When a subscene contains only levels with audio files, trying to explode the subscene causes a crash.

### Software Version

Nightly (Specify below)

### Software Version Information

September 28 2023

### Operating System

MacOS Ventura 13.5.1

**Comment by beeheemooth** [comment]
![maxresdefault](https://github.com/tahoma2d/tahoma2d/assets/25724133/6569a5c4-1ada-4f6f-aa0a-a4277cc9484b)
