### ISSUE TITLE
Raster palette not loading

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#1229]
### Bug Description

Raster palettes are not saving in the latest nightly builds - not sure how long this has been going on. They seem to save in the sandbox but not for projects. Upon opening, the new colors are all gone. Saving a default raster palette also fails. Save as doesn’t seem to respond. 

### Steps to reproduce

Make a project & a scene
Create a raster level 
Add some colors to the palette (and optionally save as default palette)
Close T2D
Palette changes/default don’t load

### Software Version

Nightly (Specify below)

### Software Version Information

Oct. 3

### Operating System

macOS Ventura

**Comment by manongjohn** [comment]
Did you try with the nightly built within the past 2 hours?  If not, can you download the latest nightly built 2 hours ago and try again?

**Comment by manongjohn** [comment]
Nevermind. I was able to reproduce the bug.  Will look further into it.

**Comment by artisteacher** [comment]
Thanks!

**Comment by manongjohn** [comment]
Actually, I'm wrong.  The only time it doesn't save the Raster palette change is when I create a scene with no levels using it.  If I update the raster palette and save the scene with no levels or no raster levels, it doesn't get updated.

I'm not sure what I'm doing differently.

**Comment by artisteacher** [comment]
Perhaps related, when opening T2D again, the Sandbox is the active project, rather than the last used project.

**Comment by artisteacher** [comment]
It's definitely related to the sandbox. When opening a recent scene from the sidebar of the startup pop-up, if I don't change the project back first, the sandbox's raster palette is used instead. So the issue seems to be 2-fold. The active project isn't staying active between sessions and loading a scene without explicitly choosing the correct project first doesn't load the correct raster palette.

**Comment by artisteacher** [comment]
@manongjohn 

I've done some further testing. It looks like beginning with #1131, the sandbox is always active upon opening a new session of T2D, even when a different project was active in the last session.

1.  Directly upon opening a new installation of T2D, choose an existing project from the startup pop-up
2. Still from the startup pop-up, choose an existing scene to load that has a raster level already and hence has a raster palette (if necessary add colors  so that there's more than the default 2 starting styles & save)
3. Completely close out of T2D
4. Open T2D - the sandbox is active instead of the project

This happens every time on current builds. Anything Jan 5th and earlier doesn't have this issue. 

Though, for both current and earlier builds, loading a scene in a different project without changing the project first (using the "load another scene" button in the startup pop-up and choosing a scene in an inactive project) doesn't load the newly active project's raster palette, even though the scene and project do both change.

**Comment by manongjohn** [comment]
It appears to be just a macOS issue.  Doesn't happen in Windows.  Haven't tested in Linux, though.

The 1st thing released after Jan 5th was the Symmetry Tool.  Not sure what I might have done to affect just macOS, but will review for any changes that might have caused this.

**Comment by manongjohn** [comment]
I believe I've found the problem.  It's related to the Symmetry tool loading at startup. It causing it to read the default environment file (env.ini) instead of the one in user's profile.

Will submit a fix soon.
