### ISSUE TITLE
AppImage problem .desktop on Linux

### ISSUE THREAD

**Issue by ampera-chu** [tahoma2d/tahoma2d#1247]
### Bug Description

Hello ! :) 
The AppImage runs perfectly in the root folder, but I have an issue when I try to run Tahoma2D.desktop

I've tried with a flag in the desktop settings  `Exec = path/to/tahoma/Tahoma2d.AppImage -TAHOMA2DROOT path/to/tahoma/tahomastuff ` but the same error is displayed.

### Steps to reproduce

Create Tahoma2D.desktop than run it.

### Relevant logs/screenshots

> 
> Tahoma2D 1.3 - Critical" Undefined or empty: ""
> Installing Tahoma2D 1.3. again could fix the problem

### Software Version

1.3.1

### Software Version Information

Tried on 1.3.1 and Nighly version

### Operating System

Linux Mint 21.2 Cinnamon

**Comment by manongjohn** [comment]
Try the following to see if it helps:

Exec=bash -c 'cd pathtoTahoma2DFolder && ./Tahoma2D.AppImage'

**Comment by ampera-chu** [comment]
It worked ! Thanks for this quick response :) 
The animation department of my school wanted to switch from DragonFrame, this fixed "shortcut" will help to make to Tahoma2D more accessible ! 
thanks for you time !

**Comment by manongjohn** [comment]
Great!  I hope T2D works out well for you/your school.
