### ISSUE TITLE
adobe photoshop multilayered support

### ISSUE THREAD

**Issue by fadi123go** [tahoma2d/tahoma2d#1250]
I wish that tahma can import adobe photoshop multilayered files.

**Comment by artisteacher** [comment]
It can...

**Comment by fadi123go** [comment]
Sorry artisteacher . There is a new app called panelforge, it produces animatics and rough key animation . I want Tahoma 2d to be capable of importing its layered output flawlessy. Both of these apps can form a great production line.

**Comment by artisteacher** [comment]
I've never used or heard of panelforge, but I assume you must be exporting PSD files from there? 

T2D loads/imports PSDs already:
- as a single flat image
- with each PSD layer as frames in a single T2D column/layer
- with each PSD layer loaded in its own column/layer and ignoring PSD groups
- where each PSD group is loaded as it's own column/layer, where the PSD layers in the group are frames in the T2D column
- where each PSD group is loaded with the PSD layers in a sub-scene column/layer

If you are looking for a different loading behavior than the existing ones, you need to be much more specific about what you are looking for. 

If you want one of those options but panelforge's PSDs aren't loading correctly, then you need to explain as much as you can about what is going wrong. What is happening when you import a PSD? Which load options are enabled? What do you expect to happen instead?

**Comment by fadi123go** [comment]
Thanks. I will explore these option further. If I encounter any problem I will give you a clearer description. Thanks again.
