### ISSUE TITLE
system error

### ISSUE THREAD

**Issue by urworthyoflove89** [tahoma2d/tahoma2d#1258]
Bug Description

A System error message popped up when I tried to up load the Tahoma2D application, it stated "The code execution cannot proceed because VCRUNTIME 140_1.dll was not found. Reinstalling the program may fix this problem." I reinstalled 3 times and it did the same thing, I have windows 11 and have updated my tablet multiple times. It has over 4 GB of room for storage. Is there something that can be done or do I need to do something else with my tablet?

### Software Version

Other (Specify below)

### Software Version Information

official release? I have a intel core m3 in the tablet

### Operating System

windows 11

### Graphics Card

no

### Drawing Tablet

not a drawing tablet, it is a samsung Galaxy TabProS

**Comment by manongjohn** [comment]
Check the Troubleshooting section in the on-line manual:

https://tahoma2d.readthedocs.io/en/latest/troubleshooting.html#windows

**Comment by urworthyoflove89** [comment]
Thank you!!
