### ISSUE TITLE
Align and Distribute Panel 

### ISSUE THREAD

**Issue by erayzesen** [tahoma2d/tahoma2d#1259]
**Is your feature request related to a problem? Please describe**
I feel the lack of an align tool, especially for quickly positioning drawings on vector levels (such as placing a head in the exact center of the body or aligning the drawing to the center of the scene, etc.) 

Of course, it would be great if the same feature could be implemented for raster levels as well. For positioning in raster levels, data from pixel drawing boundaries can be used. Just like in vectors, there's actually a need for knowing the boundaries, using a bounding box approach, for this feature. The selected object or objects can be centered, aligned to the right, or aligned to the left based on their boundaries.

**Describe the solution you'd like**
Very simple panel implementation is like : 

Relative to (Checkbox)- Canvas, first selected, last selected
Align (Buttons): 
Left , Center, Right , Top, ,Bottom...

It could be something similar. In fact, it can be entirely inspired by the align panel in Inkscape. 

![Screenshot_2023-10-23_00-29-31](https://github.com/tahoma2d/tahoma2d/assets/65820625/f2132181-cdbe-4ba5-a236-f31ed3509628)

**Comment by beeheemooth** [comment]
Oh yea, these are really useful options (I remember them in Flash)! I’m not sure that this way it will be possible to align something in raster levels, but in vector levels these options are definitely lacking in Tahoma/OT. Aligning objects is the weak point of the program at the moment; everything needs to be done “by eye”.

**Comment by erayzesen** [comment]
> Oh yea, these are really useful options (I remember them in Flash)! I’m not sure that this way it will be possible to align something in raster levels, but in vector levels these options are definitely lacking in Tahoma/OT. Aligning objects is the weak point of the program at the moment; everything needs to be done “by eye”.

I don't know a  information about the raster levels side but I think vector levels needs this feature. And yes, flash(or adobe animate) has this feature. To be honest, I don't care which software will be the inspiration for implementing this feature. Just as long as we have this capability. I don't think it would be very difficult to add this feature. I thought to add it myself, but I couldn't even compile Tahoma or Opentoonz. : (

**Comment by beeheemooth** [comment]
There is another problem. In Flash it is possible to select objects from different layers at the same time, but in Tahoma/OT you cannot do this - you always work only with the current column (I remember that this was unexpected news for me when I started doing animation in OT). Thus, the function, if it is implemented, will only be able to work with objects (groups) within the same level.

**Comment by erayzesen** [comment]
> There is another problem. In Flash it is possible to select objects from different layers at the same time, but in Tahoma/OT you cannot do this - you always work only with the current column (I remember that this was unexpected news for me when I started doing animation in OT). Thus, the function, if it is implemented, will only be able to work with objects (groups) within the same level.

  It's a good point. But if I'm not wrong, we can select multiple column in the timeline. Maybe align panel can work with bounding box of the levels when we select multiple columns. Actually best way to learn this, listening to a Tahoma2d contributor. I hope this feature request may be of their attention.

**Comment by erayzesen** [comment]
I want to share this why it's an important feature. 

- It's important feature when Tahoma2d is using by graphic designers and motion designers. They don't like relative positioning in any software.  Align tools helps to these needs. 
- Tahoma2d (even OpenToonz) doesn't have good svg importers right now. Maybe people can draw vector designs according to original design in Tahoma2D until  svg problem has been solved.    
 
Adobe animate have these tools because of these reasons.

**Comment by erayzesen** [comment]
I'm closing this feature request because of this. 
https://github.com/tahoma2d/tahoma2d/pull/1275

Yep, I was lucky for this issue.
