### ISSUE TITLE
Brush Stabilization Please ?

### ISSUE THREAD

**Issue by mihimal** [tahoma2d/tahoma2d#1266]
Can you add brush stabilization to Tahoma2D just like we find in Krita?

(Coz' My hands are bit shaky even with using a pen tablet)

**Comment by artisteacher** [comment]
There's some stabilization already, just accessed in different places depending upon the level or brush type. For vector or the default smart raster brush, try experimenting with the accuracy and smooth settings in the tool options. For the mypaint raster brushes, in the brush settings, try adjusting the "slow position tracking".
<img width="393" alt="Screenshot 2023-11-01 at 3 53 06 PM" src="https://github.com/tahoma2d/tahoma2d/assets/21159116/b9fb3a45-3f1d-4586-b329-4e6ee21a858f">

**Comment by mihimal** [comment]
Thank you sir. You all are very kind ♥️
