### ISSUE TITLE
1920×804 instead of 1920×1080

### ISSUE THREAD

**Issue by mihimal** [tahoma2d/tahoma2d#1267]
Sir, I use the resolution of 1920×804 as my default. but each time I click on  "Create new scene" it creates a new scene in 1920×1080 instead of 1920×804. can you make it able to set a "Custom-default resolution" to a New Scene and New Project as we want in a future update?

when I want to start a new scene in 1920×804, I need to Close Tahoma2D and open again. because the softwares default for a New Scene is: 1920×1080. can you make it able to set a "default resolution" for a new scene we creating in the future?

**Comment by artisteacher** [comment]
You don't have to reopen - you can just open the startup pop-up again from the Windows menu. 

I do think that the resolution should probably be remembered though. New scenes made from the new scene command should automatically use the resolution that was chosen last.

**Comment by mihimal** [comment]
But, when I click "File" > "New Scene" No popup comes to change the resolution 🙄

**Comment by mihimal** [comment]
**Thanks sir, It helped! ♥️**
