### ISSUE TITLE
How can I export my UI Preferences in Tahoma2D ?

### ISSUE THREAD

**Issue by mihimal** [tahoma2d/tahoma2d#1268]
If I want to **Export** my software preferences like:

**Custom Panels, Windows and their locations, Brush Presets, Customized software UI** 

How can I do it?

**Comment by artisteacher** [comment]
I don't think there's an export option - but you can import your settings from an older version of T2D to a newer install. At the bottom of the sidebar in "Preferences", there's an import option.

**Comment by mihimal** [comment]
Thanks for replying ♥️
