### ISSUE TITLE
Nightly build crash

### ISSUE THREAD

**Issue by BertWik** [tahoma2d/tahoma2d#1270]
### Bug Description

Tahoma2D 1.4 (beta) (Build Nov 4 2023) crashes immediately after trying to open.

### Software Version

Nightly (Specify below)

### Software Version Information

Tahoma2D 1.4 (beta) (Build Nov 4 2023)

### Operating System

Mac OS Ventura

**Comment by manongjohn** [comment]
I just downloaded the latest macOS Nightly, built  Nov 4th, and was able to start up without any issues.

Is there an Apple or T2D crash log you can attach for review?

**Comment by BertWik** [comment]
Yes, see attached.

￼

**Comment by manongjohn** [comment]
Still not seeing an attachment

**Comment by BertWik** [comment]
I did attach a word file.
Now I attach a text file

￼

**Comment by manongjohn** [comment]
Odd. All I see is 
![image](https://github.com/tahoma2d/tahoma2d/assets/19245851/b17c8c54-6481-4f18-b268-2f93db6e8c57)

Not sure why, but it's putting this:

 <Crash Log.docx>

Appears you are replying to the email notification you get, it might not be posting the attachment correctly.  Can you go to the github issue in your browser and post it directly in a comment?

**Comment by BertWik** [comment]
Here is the Word file

[Crash Log.docx](https://github.com/tahoma2d/tahoma2d/files/13259759/Crash.Log.docx)

**Comment by manongjohn** [comment]
Looks like it's failing to make a new directory, probably your profile directory in `tahomastuff\profiles` that is created at initial startup.  Where did you place Tahoma2D?

I would suggest deleting the Tahoma2D app, and re-extract from the DMG file again.  After getting through the security checks, make sure you agree to allow access to all the folders it prompts you for.

**Comment by BertWik** [comment]
It works.

**Comment by artisteacher** [comment]
For future reference, if you don't grant the correct permissions from the start, you can open System Settings &rarr; Privacy & Security &rarr; Files & Folders and then give T2D permission to access the correct directories.

And always move T2D onto the computer from the DMG. Opening directly from the DMG will always crash on open.
