### ISSUE TITLE
Native .deb package, Issues with the .deb package I created from --appimage-extract.

### ISSUE THREAD

**Issue by charliemartinez** [tahoma2d/tahoma2d#1301]
Something I would like for Tahoma2D is to have a native .deb package.

I am the maintainer of the Quirinux GNU/Linux operating system packages, and I have been performing an --appimage-extract on each new version you release to incorporate it into our repository. This allows us to offer it to our users preinstalled in our ISOs and update the package without requiring users to download the appimage file. We actually prefer using deb packages, but what we do is store everything in /opt/tahoma2d to avoid conflicts with our system's libraries (based on Debian).

I am having difficulty getting version 1.4 to work. The previous version (1.3.8) works  without any issues:

This works:

[https://repo.quirinux.org/pool/main/t/tahoma2d/](https://repo.quirinux.org/pool/main/t/tahoma2d/)

This not:

[https://repo.quirinux.org/dev/Test/](https://repo.quirinux.org/dev/Test/)

I am likely placing one of the libraries in the wrong path. I kindly ask for guidance as this is very important for us.

It would be very helpful if you could extract the .deb files I just shared to check whether I am placing the extracted files from the .appimage in the correct location.

Greetings and thank you.

Tahoma2D 1.4  (Build Dec  1 2023)

Report Date: 2023-12-03 18:07:03
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: Debian GNU/Linux 12 (bookworm)
OS Kernel: 6.1.0-13-amd64
CPU Threads: 8

Crash File: /home/USER/.local/share/Tahoma2D/Tahoma2D/crash/Crash-20231203-180703.log

==== Backtrace ====
  1> pthread_key_delete en ??:?
  2> gsignal en ??:?
  3> abort en ??:?
  4> __cxa_throw_bad_array_new_length en ??:?
  5> std::rethrow_exception(std::__exception_ptr::exception_ptr) en ??:?
  6> std::terminate() en ??:?
  7> __cxa_throw en ??:?
  8> std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_is_local() const en basic_string.h:226
 (inlined por) std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_dispose() en basic_string.h:235
 (inlined por) std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string() en basic_string.h:662
 (inlined por) toQString en tsystem.cpp:38
 (inlined por) setPathsPermissions en tsystem.cpp:235
 (inlined por) TSystem::mkDir(TFilePath const&) en tsystem.cpp:249
  9> main en main.cpp:236
 (inlined por) main en main.cpp:582
 10> __libc_init_first en ??:?
 11> __libc_start_main en ??:?
 12> _start en ??:?
==== End ====

==== Modules ====
0x55718568d000 - 
0x7ffd427dd000 - linux-vdso.so.1
0x7fce511fa000 - /opt/tahoma2d/usr/bin/../lib/libQt5Xml.so.5
0x7fce51182000 - /opt/tahoma2d/usr/bin/../lib/libQt5PrintSupport.so.5
0x7fce51167000 - /opt/tahoma2d/usr/bin/../lib/libQt5SerialPort.so.5
0x7fce510be000 - /lib/x86_64-linux-gnu/libGL.so.1
0x7fce50e00000 - /opt/tahoma2d/usr/bin/../lib/libglut.so.3
0x7fce50d8d000 - /opt/tahoma2d/usr/bin/../lib/libGLU.so.1
0x7fce50cec000 - /opt/tahoma2d/usr/bin/../lib/libturbojpeg.so.0
0x7fce5104f000 - /opt/tahoma2d/usr/bin/../lib/libopencv_videoio.so.4.5
0x7fce50c71000 - /opt/tahoma2d/usr/bin/../lib/libcolorfx.so
0x7fce50abe000 - /opt/tahoma2d/usr/bin/../lib/libimage.so
0x7fce50600000 - /opt/tahoma2d/usr/bin/../lib/libtnztools.so
0x7fce50000000 - /opt/tahoma2d/usr/bin/../lib/libtnzstdfx.so
0x7fce50a93000 - /opt/tahoma2d/usr/bin/../lib/libtfarm.so
0x7fce50577000 - /opt/tahoma2d/usr/bin/../lib/libgphoto2.so.6
0x7fce50a83000 - /opt/tahoma2d/usr/bin/../lib/libgphoto2_port.so.12
0x7fce50a7e000 - /lib/x86_64-linux-gnu/libdl.so.2
0x7fce4f800000 - /opt/tahoma2d/usr/bin/../lib/libQt5Widgets.so.5
0x7fce4f000000 - /opt/tahoma2d/usr/bin/../lib/libQt5Gui.so.5
0x7fce4ea00000 - /opt/tahoma2d/usr/bin/../lib/libQt5Core.so.5
0x7fce50a79000 - /lib/x86_64-linux-gnu/libpthread.so.0
0x7fce50514000 - /opt/tahoma2d/usr/bin/../lib/libopencv_imgcodecs.so.4.5
0x7fce4e600000 - /opt/tahoma2d/usr/bin/../lib/libopencv_calib3d.so.4.5
0x7fce4ca00000 - /opt/tahoma2d/usr/bin/../lib/libopencv_imgproc.so.4.5
0x7fce4ba00000 - /opt/tahoma2d/usr/bin/../lib/libopencv_core.so.4.5
0x7fce4b400000 - /opt/tahoma2d/usr/bin/../lib/libtoonzqt.so
0x7fce50a5a000 - /opt/tahoma2d/usr/bin/../lib/libsound.so
0x7fce4ae00000 - /opt/tahoma2d/usr/bin/../lib/libtoonzlib.so
0x7fce4aa00000 - /opt/tahoma2d/usr/bin/../lib/libQt5Script.so.5
0x7fce4ff80000 - /opt/tahoma2d/usr/bin/../lib/libtnzext.so
0x7fce4e86f000 - /opt/tahoma2d/usr/bin/../lib/libtnzbase.so
0x7fce4a600000 - /opt/tahoma2d/usr/bin/../lib/libtnzcore.so
0x7fce504b9000 - /opt/tahoma2d/usr/bin/../lib/libQt5OpenGL.so.5
0x7fce4f6e4000 - /opt/tahoma2d/usr/bin/../lib/libQt5Multimedia.so.5
0x7fce4a436000 - /opt/tahoma2d/usr/bin/../lib/libQt5Network.so.5
0x7fce4a000000 - /lib/x86_64-linux-gnu/libstdc++.so.6
0x7fce4b321000 - /lib/x86_64-linux-gnu/libm.so.6
0x7fce50a32000 - /lib/x86_64-linux-gnu/libgcc_s.so.1
0x7fce49e1f000 - /lib/x86_64-linux-gnu/libc.so.6
0x7fce4ff51000 - /opt/tahoma2d/usr/bin/../lib/libudev.so.1
0x7fce4e547000 - /lib/x86_64-linux-gnu/libGLdispatch.so.0
0x7fce4ff1d000 - /lib/x86_64-linux-gnu/libGLX.so.0
0x7fce4acbe000 - /lib/x86_64-linux-gnu/libX11.so.6
0x7fce4ff0a000 - /opt/tahoma2d/usr/bin/../lib/libXi.so.6
0x7fce50a28000 - /opt/tahoma2d/usr/bin/../lib/libXxf86vm.so.1
0x7fce48800000 - /opt/tahoma2d/usr/bin/../lib/libavcodec.so.58
0x7fce48400000 - /opt/tahoma2d/usr/bin/../lib/libavformat.so.58
0x7fce48000000 - /opt/tahoma2d/usr/bin/../lib/libavutil.so.56
0x7fce4b960000 - /opt/tahoma2d/usr/bin/../lib/libswscale.so.5
0x7fce4feeb000 - /lib/x86_64-linux-gnu/libz.so.1
0x7fce4fec1000 - /opt/tahoma2d/usr/bin/../lib/liblzma.so.5
0x7fce4e835000 - /opt/tahoma2d/usr/bin/../lib/libpng16.so.16
0x7fce4b29b000 - /opt/tahoma2d/usr/bin/../lib/libjpeg.so.8
0x7fce4e81c000 - /opt/tahoma2d/usr/bin/../lib/libmypaint-1.4.so.0
0x7fce4a373000 - /opt/tahoma2d/usr/bin/../lib/libGLEW.so.2.1
0x7fce4feb5000 - /opt/tahoma2d/usr/bin/../lib/libltdl.so.7
0x7fce4a9b6000 - /opt/tahoma2d/usr/bin/../lib/libexif.so.12
0x7fce4a26f000 - /lib/x86_64-linux-gnu/libharfbuzz.so.0
0x7fce47c00000 - /opt/tahoma2d/usr/bin/../lib/libicui18n.so.66
0x7fce47800000 - /opt/tahoma2d/usr/bin/../lib/libicuuc.so.66
0x7fce49d95000 - /opt/tahoma2d/usr/bin/../lib/libpcre2-16.so.0
0x7fce486cc000 - /opt/tahoma2d/usr/bin/../lib/libglib-2.0.so.0
0x7fce51243000 - /lib64/ld-linux-x86-64.so.2
0x7fce49d2a000 - /opt/tahoma2d/usr/bin/../lib/libwebp.so.6
0x7fce4837c000 - /opt/tahoma2d/usr/bin/../lib/libtiff.so.5
0x7fce49cd3000 - /opt/tahoma2d/usr/bin/../lib/libopenjp2.so.7
0x7fce47400000 - /opt/tahoma2d/usr/bin/../lib/libIlmImf-2_3.so.24
0x7fce47b27000 - /opt/tahoma2d/usr/bin/../lib/libopencv_features2d.so.4.5
0x7fce482ff000 - /opt/tahoma2d/usr/bin/../lib/libopencv_flann.so.4.5
0x7fce47fa3000 - /opt/tahoma2d/usr/bin/../lib/libQt5Svg.so.5
0x7fce47ab5000 - /opt/tahoma2d/usr/bin/../lib/libsuperlu.so.5
0x7fce4a973000 - /opt/tahoma2d/usr/bin/../lib/libgslcblas.so.0
0x7fce4c9de000 - /opt/tahoma2d/usr/bin/../lib/liblz4.so.1
0x7fce47a60000 - /opt/tahoma2d/usr/bin/../lib/libpulse.so.0
0x7fce4b271000 - /lib/x86_64-linux-gnu/libxcb.so.1
0x7fce4e805000 - /opt/tahoma2d/usr/bin/../lib/libXext.so.6
0x7fce486a9000 - /opt/tahoma2d/usr/bin/../lib/libswresample.so.3
0x7fce47000000 - /opt/tahoma2d/usr/bin/../lib/libvpx.so.6
0x7fce4c9d1000 - /opt/tahoma2d/usr/bin/../lib/libwebpmux.so.3
0x7fce4aca7000 - /opt/tahoma2d/usr/bin/../lib/libopencore-amrwb.so.0
0x7fce4a966000 - /opt/tahoma2d/usr/bin/../lib/libsnappy.so.1
0x7fce47786000 - /opt/tahoma2d/usr/bin/../lib/libmp3lame.so.0
0x7fce482d3000 - /opt/tahoma2d/usr/bin/../lib/libopencore-amrnb.so.0
0x7fce47726000 - /opt/tahoma2d/usr/bin/../lib/libopus.so.0
0x7fce4868a000 - /opt/tahoma2d/usr/bin/../lib/libspeex.so.1
0x7fce47a22000 - /opt/tahoma2d/usr/bin/../lib/libtheoraenc.so.1
0x7fce47f82000 - /opt/tahoma2d/usr/bin/../lib/libtheoradec.so.1
0x7fce473d1000 - /opt/tahoma2d/usr/bin/../lib/libvorbis.so.0
0x7fce47325000 - /opt/tahoma2d/usr/bin/../lib/libvorbisenc.so.2
0x7fce46e6e000 - /opt/tahoma2d/usr/bin/../lib/libopenh264.so.7
0x7fce46caa000 - /opt/tahoma2d/usr/bin/../lib/libxml2.so.2
0x7fce4a25b000 - /opt/tahoma2d/usr/bin/../lib/libbz2.so.1.0
0x7fce472d3000 - /opt/tahoma2d/usr/bin/../lib/libbluray.so.2
0x7fce46ac9000 - /opt/tahoma2d/usr/bin/../lib/libgnutls.so.30
0x7fce49cbf000 - /opt/tahoma2d/usr/bin/../lib/libjson-c.so.4
0x7fce4726f000 - /opt/tahoma2d/usr/bin/../lib/libgobject-2.0.so.0
0x7fce469fe000 - /lib/x86_64-linux-gnu/libfreetype.so.6
0x7fce47243000 - /lib/x86_64-linux-gnu/libgraphite2.so.3
0x7fce44e00000 - /opt/tahoma2d/usr/bin/../lib/libicudata.so.66
0x7fce4698a000 - /opt/tahoma2d/usr/bin/../lib/libpcre.so.3
0x7fce468df000 - /opt/tahoma2d/usr/bin/../lib/libzstd.so.1
0x7fce47a10000 - /opt/tahoma2d/usr/bin/../lib/libjbig.so.0
0x7fce44dba000 - /opt/tahoma2d/usr/bin/../lib/libHalf.so.24
0x7fce476ff000 - /opt/tahoma2d/usr/bin/../lib/libIex-2_3.so.24
0x7fce47f76000 - /opt/tahoma2d/usr/bin/../lib/libIlmThread-2_3.so.24
0x7fce44d4b000 - /opt/tahoma2d/usr/bin/../lib/libblas.so.3
0x7fce44cc3000 - /opt/tahoma2d/usr/bin/../lib/libpulsecommon-13.99.so
0x7fce44c6d000 - /opt/tahoma2d/usr/bin/../lib/libdbus-1.so.3
0x7fce4b26c000 - /lib/x86_64-linux-gnu/libXau.so.6
0x7fce44a00000 - /lib/x86_64-linux-gnu/libXdmcp.so.6
0x7fce44994000 - /opt/tahoma2d/usr/bin/../lib/libsoxr.so.0
0x7fce468d1000 - /opt/tahoma2d/usr/bin/../lib/libogg.so.0
0x7fce4486c000 - /opt/tahoma2d/usr/bin/../lib/libcairo.so.2
0x7fce44c22000 - /lib/x86_64-linux-gnu/libfontconfig.so.1
0x7fce44738000 - /lib/x86_64-linux-gnu/libp11-kit.so.0
0x7fce44716000 - /opt/tahoma2d/usr/bin/../lib/libidn2.so.0
0x7fce44590000 - /opt/tahoma2d/usr/bin/../lib/libunistring.so.2
0x7fce44c0b000 - /opt/tahoma2d/usr/bin/../lib/libtasn1.so.6
0x7fce44553000 - /opt/tahoma2d/usr/bin/../lib/libnettle.so.7
0x7fce44519000 - /opt/tahoma2d/usr/bin/../lib/libhogweed.so.5
0x7fce44498000 - /lib/x86_64-linux-gnu/libgmp.so.10
0x7fce468c4000 - /opt/tahoma2d/usr/bin/../lib/libffi.so.7
0x7fce4448b000 - /lib/x86_64-linux-gnu/libbrotlidec.so.1
0x7fce443d7000 - /opt/tahoma2d/usr/bin/../lib/libsystemd.so.0
0x7fce443ca000 - /opt/tahoma2d/usr/bin/../lib/libwrap.so.0
0x7fce44349000 - /opt/tahoma2d/usr/bin/../lib/libsndfile.so.1
0x7fce44000000 - /opt/tahoma2d/usr/bin/../lib/libasyncns.so.0
0x7fce44333000 - /opt/tahoma2d/usr/bin/../lib/libapparmor.so.1
0x7fce4a961000 - /lib/x86_64-linux-gnu/librt.so.1
0x7fce4431d000 - /lib/x86_64-linux-gnu/libbsd.so.0
0x7fce442d8000 - /opt/tahoma2d/usr/bin/../lib/libgomp.so.1
0x7fce4422f000 - /opt/tahoma2d/usr/bin/../lib/libpixman-1.so.0
0x7fce49cb9000 - /opt/tahoma2d/usr/bin/../lib/libxcb-shm.so.0
0x7fce4421d000 - /opt/tahoma2d/usr/bin/../lib/libxcb-render.so.0
0x7fce43c00000 - /opt/tahoma2d/usr/bin/../lib/libXrender.so.1
0x7fce43fd5000 - /lib/x86_64-linux-gnu/libexpat.so.1
0x7fce44211000 - /lib/x86_64-linux-gnu/libffi.so.8
0x7fce43fb2000 - /lib/x86_64-linux-gnu/libbrotlicommon.so.1
0x7fce43e92000 - /opt/tahoma2d/usr/bin/../lib/libgcrypt.so.20
0x7fce43e73000 - /opt/tahoma2d/usr/bin/../lib/libnsl.so.1
0x7fce43e31000 - /opt/tahoma2d/usr/bin/../lib/libFLAC.so.8
0x7fce43e20000 - /lib/x86_64-linux-gnu/libresolv.so.2
0x7fce43e13000 - /lib/x86_64-linux-gnu/libmd.so.0
0x7fce43bd8000 - /lib/x86_64-linux-gnu/libgpg-error.so.0
0x7fce51151000 - /opt/tahoma2d/usr/plugins/platforms/libqxcb.so
0x7fce43493000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
0x7fce433f6000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libQt5DBus.so.5
0x7fce5114c000 - /lib/x86_64-linux-gnu/libX11-xcb.so.1
0x7fce44208000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-icccm.so.4
0x7fce43000000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-image.so.0
0x7fce51146000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-keysyms.so.1
0x7fce43b9f000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-randr.so.0
0x7fce43e0b000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-render-util.so.0
0x7fce43b99000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-shape.so.0
0x7fce43b8e000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-sync.so.1
0x7fce43b82000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-xfixes.so.0
0x7fce43b7c000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-xinerama.so.0
0x7fce433d3000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-xkb.so.1
0x7fce433a8000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-xinput.so.0
0x7fce43b71000 - /lib/x86_64-linux-gnu/libSM.so.6
0x7fce4338a000 - /lib/x86_64-linux-gnu/libICE.so.6
0x7fce43b64000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxkbcommon-x11.so.0
0x7fce43347000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxkbcommon.so.0
0x7fce42c00000 - /opt/tahoma2d/usr/plugins/platforms/../../lib/libxcb-util.so.1
0x7fce4333d000 - /lib/x86_64-linux-gnu/libuuid.so.1
0x7fce43330000 - /lib/x86_64-linux-gnu/libXcursor.so.1
0x7fce43328000 - /lib/x86_64-linux-gnu/libXfixes.so.3
0x7fce43303000 - /opt/tahoma2d/usr/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
0x7fce43bcd000 - /opt/tahoma2d/usr/plugins/iconengines/libqsvgicon.so
0x7fce43bb9000 - /opt/tahoma2d/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
0x7fce432e1000 - /opt/tahoma2d/usr/plugins/xcbglintegrations/../../lib/libxcb-glx.so.0
0x7fce42f90000 - /lib/x86_64-linux-gnu/libGLX_mesa.so.0
0x7fce42f56000 - /lib/x86_64-linux-gnu/libglapi.so.0
0x7fce432a9000 - /lib/x86_64-linux-gnu/libdrm.so.2
0x7fce432a2000 - /lib/x86_64-linux-gnu/libxcb-dri2.so.0
0x7fce41800000 - /lib/x86_64-linux-gnu/libxshmfence.so.1
0x7fce4329b000 - /lib/x86_64-linux-gnu/libxcb-dri3.so.0
0x7fce44c06000 - /lib/x86_64-linux-gnu/libxcb-present.so.0
0x7fce3a400000 - /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
0x7fce2ce00000 - /lib/x86_64-linux-gnu/libLLVM-15.so.1
0x7fce432ca000 - /lib/x86_64-linux-gnu/libsensors.so.5
0x7fce4320d000 - /lib/x86_64-linux-gnu/libdrm_radeon.so.1
0x7fce42ef8000 - /lib/x86_64-linux-gnu/libelf.so.1
0x7fce4328f000 - /lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
0x7fce432bf000 - /lib/x86_64-linux-gnu/libdrm_nouveau.so.2
0x7fce42ed3000 - /lib/x86_64-linux-gnu/libdrm_intel.so.1
0x7fce42e99000 - /lib/x86_64-linux-gnu/libedit.so.2
0x7fce38c00000 - /lib/x86_64-linux-gnu/libz3.so.4
0x7fce42e66000 - /lib/x86_64-linux-gnu/libtinfo.so.6
0x7fce42e5b000 - /lib/x86_64-linux-gnu/libpciaccess.so.0
==== End ====

**Comment by manongjohn** [comment]
Reading the crashlog, it appears to be failing to create a directory at startup, likely Tahoma's stuff folder/profiles/users/username.

As you are doing a system install rather than a portable, i believe something needs to be made to tell it where to make a user's profile folder. I'm not sure how you did that for 1.3.1.

When i can i will attempt to install the .deb package on my Ubuntu VM. Always wanted to be able to make an official Linux "installer" version but unsure how to start that.
