### ISSUE TITLE
unknown crash

### ISSUE THREAD

**Issue by Minced-Meat** [tahoma2d/tahoma2d#1321]
### Bug Description

im not sure what caused it to crash

### Relevant logs/screenshots

Tahoma2D 1.4  (Build Dec  1 2023)

Report Date: 2023-12-22 17:45:32
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 (10.0)
OS Kernel: 10.0.22621
CPU Threads: 6

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1650/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.99

Crash File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20231222-174532.log
Mini Dump File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20231222-174532.dmp

Application Dir: C:/Users/USER/Documents/software/Tahoma2D-portable-win (1)/Tahoma2D
Stuff Dir: C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tahomastuff

Project Name: sandbox
Scene Name: NEW OCS YIUPPYY!!!
Project Path: C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tahomastuff\sandbox\tahomaproject.xml
Scene Path: C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tahomastuff\sandbox\scenes\NEW OCS YIUPPYY!!!.tnz

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fff9d567a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fff9d50e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff9d59340e] <ntdll.dll>
  4> RasterBlurredBrush::getBoundFromPoints {bluredbrush.cpp:508} <tnztools.dll>
  5> FullColorEraserTool::leftButtonUp {fullcolorerasertool.cpp:704} <tnztools.dll>
  6> SceneViewer::onRelease {sceneviewerevents.cpp:1042} <Tahoma2D.exe>
  7> SceneViewer::tabletEvent {sceneviewerevents.cpp:350} <Tahoma2D.exe>
  8> QWidget::event [0x5371877b] <Qt5Widgets.dll>
  9> SceneViewer::event {sceneviewerevents.cpp:1501} <Tahoma2D.exe>
 10> QApplicationPrivate::notify_helper [0x536f6be4] <Qt5Widgets.dll>
 11> QApplication::notify [0x536f52a8] <Qt5Widgets.dll>
 12> QCoreApplication::notifyInternal2 [0x531cd4aa] <Qt5Core.dll>
 13> QDesktopWidget::workAreaResized [0x53741ffc] <Qt5Widgets.dll>
 14> QDesktopWidget::workAreaResized [0x5373fc96] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x536f6be4] <Qt5Widgets.dll>
 16> QApplication::notify [0x536f5aa3] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x531cd4aa] <Qt5Core.dll>
 18> QGuiApplicationPrivate::processTabletEvent [0x7ffefb82bc62] <Qt5Gui.dll>
 19> QWindowSystemInterface::sendWindowSystemEvents [0x7ffefb80f9a0] <Qt5Gui.dll>
 20> QEventDispatcherWin32::processEvents [0x53212ac9] <Qt5Core.dll>
 21> DispatchMessageW [0x7fff9c6f8241] <USER32.dll>
 22> DispatchMessageW [0x7fff9c6f7d01] <USER32.dll>
 23> QEventDispatcherWin32::processEvents [0x53212300] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7fff32820339] <qwindows.dll>
 25> QEventLoop::exec [0x531c9c0c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x531cc4b4] <Qt5Core.dll>
 27> main {main.cpp:895} <Tahoma2D.exe>
 28> WinMain [0x7ff78b466c64] <Tahoma2D.exe>
 29> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 30> BaseThreadInitThunk [0x7fff9c15257d] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7fff9d54aa58] <ntdll.dll>
==== End ====

==== Modules ====
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Tahoma2D.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\freeglut.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Xml.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\libgphoto2_port.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\colorfx.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\image.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\libgphoto2.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tnztools.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tfarm.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tnzstdfx.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\toonzqt.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\opencv_world451.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\sound.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Script.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tnzext.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\toonzlib.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Widgets.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tnzbase.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\tnzcore.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5OpenGL.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Core.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\CONCRT140.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\glew32.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\libintl-8.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\libjson-c-2.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\libiconv-2.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\Qt5Svg.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\platforms\qwindows.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\iconengines\qsvgicon.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_c885f29e168e777a\nvoglv64.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qgif.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qicns.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qico.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qjpeg.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qsvg.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qtga.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qtiff.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qwbmp.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\imageformats\qwebp.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\mediaservice\dsengine.dll
C:\WINDOWS\SYSTEM32\dxva2.dll
C:\WINDOWS\SYSTEM32\EVR.dll
C:\Windows\System32\devenum.dll
C:\WINDOWS\SYSTEM32\msdmo.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\EdsImage.dll
C:\Windows\System32\PortableDeviceApi.dll
C:\Users\USER\Documents\software\Tahoma2D-portable-win (1)\Tahoma2D\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\mswsock.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\system32\Ninput.dll
C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2506_none_270c5ae97388e100\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
==== End ====

### Software Version

1.4

### Operating System

windows 11

### Graphics Card

gtx 1650 super

### Drawing Tablet

huion dial 2

**Comment by VinylBoi** [comment]
Have the same issue but it happens on start up of version 1.4

Windows 10.
gtx 980ti
Wacom HD 22 touch

**Comment by manongjohn** [comment]
@Minced-Meat If at all still possible, can you get me the crashdump file indicated in the log (replace `\USER\` with your username): `C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20231222-174532.dmp`

**Comment by Minced-Meat** [comment]
I wasn't able to get any results im sorry
