### ISSUE TITLE
Style Editor with more color options

### ISSUE THREAD

**Issue by ByteBeamer** [tahoma2d/tahoma2d#1323]
**Is your feature request related to a problem? Please describe**
I was looking at the original OpenToonz Style Editor and I wish Tahoma had the same amount (or more) sliders like hue, saturation, etc. Forgive me if this is already an option and I can't find it.

OpenToonz
![style_editor_color](https://github.com/tahoma2d/tahoma2d/assets/81110386/d7750c3d-e9de-4569-8c68-916af3577c6f)

Tahoma2D
![image](https://github.com/tahoma2d/tahoma2d/assets/81110386/365db0fb-8fa1-41b8-a4ac-75bcd01670f7)

**Describe the solution you'd like**
Add sliders or an option to add sliders like HSV, and RGB to the editor.

**Comment by manongjohn** [comment]
@ByteBeamer If you click on the menu button in the bottom right corner of the Style Editor panel, it has the options to show those other settings.

**Comment by ByteBeamer** [comment]
Sorry (and thanks), I’m still new to the program
