### ISSUE TITLE
Crash when using geometry tool

### ISSUE THREAD

**Issue by ByteBeamer** [tahoma2d/tahoma2d#1329]
### Bug Description

Any time I try and use the geometry tool upon lifting my pen or releasing mouse the application crashes

### Steps to reproduce

Use the geometry tool at all, with or without drawing tablet

### Relevant logs/screenshots

[Crash-20240102-111949.log](https://github.com/tahoma2d/tahoma2d/files/13812472/Crash-20240102-111949.log)
[Crash-20240102-111949.dmp](https://github.com/tahoma2d/tahoma2d/files/13812473/Crash-20240102-111949.dmp)

### Software Version

1.4

### Operating System

Windows 11

### Graphics Card

NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2

### Drawing Tablet

XP Pen Artist 10 Display (2nd Gen) / mouse

**Comment by ByteBeamer** [comment]
I don't know if this is related but after pressing shift and alt while drawing the line doesn't actually draw. 

This is a GIF of the crash occurring
![ezgif-5-2e2d872c73](https://github.com/tahoma2d/tahoma2d/assets/81110386/4e9bf62f-df28-4ba0-a84a-1e7e10cc2d14)

This is a GIF of the snap to perspective, and draw line shortcut (ctrl or alt while drawing) not working
![ezgif-5-57620a0613](https://github.com/tahoma2d/tahoma2d/assets/81110386/16eb7530-42a7-49b4-b2e8-6ee6ea1d419b)

**Comment by manongjohn** [comment]
I recall looking into the same crash reported in Discord last month, though I didn't have a fix for it.

In my cause, I was only able to reproduce it when my system was running low on memory.  It kept removing the Raster palette from memory which caused crashes under certain circumstances with the geometry tool.

How much memory does your system have? Are you running other stuff at the same time that might be using up a lot of your memory?  Try closing other programs and see it will help.

I will look further into it to see what I can do to avoid this issue.

**Comment by ByteBeamer** [comment]
Thanks, I will try that out. My system only has 8 GB of RAM and I had Chrome running in the background. That might have been the issue.

**Comment by ByteBeamer** [comment]
The issue was definitely lack of ram, when I have chrome closed it works perfectly
