### ISSUE TITLE
Won't Open, Crashing on Startup

### ISSUE THREAD

**Issue by mortalpoet** [tahoma2d/tahoma2d#1335]
### Bug Description

Program crashes on open. Installed the most recent stable version on Windows 10. Works on my desktop computer, but not my Wacom MobileStudio Pro 16

### Steps to reproduce

Happens when opening Tahoma2D.exe

### Relevant logs/screenshots

Tahoma2D 1.4  (Build Dec  1 2023)

Report Date: 2024-01-08 12:38:41
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 (10.0)
OS Kernel: 10.0.19045
CPU Threads: 4

Crash File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240108-123841.log
Mini Dump File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240108-123841.dmp

==== Backtrace ====
  1> RtlDeleteAce [0x7ff8479c8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8479a12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff8479f0ebe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ff82e362b9c] <MSVFW32.dll>
  6> ICOpen [0x7ff82e362d64] <MSVFW32.dll>
  7> <lambda_9695d86ee572e1d7d63c2c682de73493>::operator() {tiio_avi.cpp:1072} <image.dll>
  8> `anonymous namespace'::safe_ICOpen {tiio_avi.cpp:1084} <image.dll>
  9> Tiio::AviWriterProperties::AviWriterProperties {tiio_avi.cpp:1136} <image.dll>
 10> initImageIo {tiio.cpp:213} <image.dll>
 11> initToonzEnv {main.cpp:189} <Tahoma2D.exe>
 12> main {main.cpp:585} <Tahoma2D.exe>
 13> WinMain [0x7ff70bef6c64] <Tahoma2D.exe>
 14> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 15> BaseThreadInitThunk [0x7ff8459c7344] <KERNEL32.DLL>
 16> RtlUserThreadStart [0x7ff8479a26b1] <ntdll.dll>
==== End ====

==== Modules ====
C:\Program Files\Tahoma2D\Tahoma2D.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\Tahoma2D\Qt5Xml.dll
C:\Program Files\Tahoma2D\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\Tahoma2D\Qt5SerialPort.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\Tahoma2D\freeglut.dll
C:\Program Files\Tahoma2D\libgphoto2.dll
C:\Program Files\Tahoma2D\EDSDK.dll
C:\Program Files\Tahoma2D\libgphoto2_port.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\Tahoma2D\colorfx.dll
C:\Program Files\Tahoma2D\image.dll
C:\Program Files\Tahoma2D\tnztools.dll
C:\Program Files\Tahoma2D\tfarm.dll
C:\Program Files\Tahoma2D\tnzstdfx.dll
C:\Program Files\Tahoma2D\opencv_world451.dll
C:\Program Files\Tahoma2D\sound.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\Tahoma2D\toonzqt.dll
C:\Program Files\Tahoma2D\toonzlib.dll
C:\Program Files\Tahoma2D\tnzext.dll
C:\Program Files\Tahoma2D\Qt5Script.dll
C:\Program Files\Tahoma2D\tnzbase.dll
C:\Program Files\Tahoma2D\tnzcore.dll
C:\Program Files\Tahoma2D\Qt5OpenGL.dll
C:\Program Files\Tahoma2D\Qt5Multimedia.dll
C:\Program Files\Tahoma2D\Qt5Widgets.dll
C:\Program Files\Tahoma2D\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\Tahoma2D\Qt5Core.dll
C:\Program Files\Tahoma2D\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MSVCP140.dll
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\CONCRT140.dll
C:\Program Files\Tahoma2D\libmypaint-1-4-0.dll
C:\Program Files\Tahoma2D\Qt5Svg.dll
C:\Program Files\Tahoma2D\glew32.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\Program Files\Tahoma2D\libintl-8.dll
C:\Program Files\Tahoma2D\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\Tahoma2D\libiconv-2.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\Tahoma2D\platforms\qwindows.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\Program Files\Tahoma2D\iconengines\qsvgicon.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvpmwi.inf_amd64_b87538f7c2b591a0\nvoglv64.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dxgi.dll
C:\WINDOWS\system32\d3d11.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\nvapi64.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\SYSTEM32\dcomp.dll
C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

### Software Version

1.4

### Software Version Information

Tahoma2D 1.4

### Operating System

Windows 10

### Graphics Card

NVIDIA Quadro M1000M

### Drawing Tablet

Wacom MobileStudioPro 16

**Comment by manongjohn** [comment]
@mortalpoet It's crashing due to Logitech DLL:

C:\WINDOWS\SYSTEM32\lvcod64.dll

This has impacted a number of other software, not just T2D.  It is typically not needed and the recommendation is to delete this file.

**Comment by mortalpoet** [comment]
That seems to have fixed it, thank you so much for the quick response!!
