### ISSUE TITLE
Canvas resize anchor not working

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#1338]
### Bug Description

When resizing the canvas, the anchor position is ignored. The canvas is extended equally on each side (horizontally or vertically) dependent upon changing the width or the height.

### Steps to reproduce

1. Create a raster or smart raster level
2. Open the "Canvas Size" window
3. Set the anchor to one of the sides instead of the middle
4. Change the width or height -> the additional canvas gets added equally to both sides, rather than opposite the anchor

### Relevant logs/screenshots

<img width="224" alt="Screenshot 2024-01-11 at 7 08 22 PM" src="https://github.com/tahoma2d/tahoma2d/assets/21159116/569833c3-acd8-4816-9e38-d0ee1ef01172">
<img width="1042" alt="Screenshot 2024-01-11 at 7 08 54 PM" src="https://github.com/tahoma2d/tahoma2d/assets/21159116/1be077b4-0a67-4287-8f54-18a177882db7">

### Software Version

1.4

### Software Version Information

Also an issue in action builds for current PRs

### Operating System

macOS Sonoma

**Comment by manongjohn** [comment]
It works for me.  Keep in mind, the canvas is always centered when displayed.

Did you try drawing something on the canvas and then resize and see how the drawing now sits based on the anchor

**Comment by artisteacher** [comment]
Never mind then! It is working properly.
