### ISSUE TITLE
Tahoma rendering issue 

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1339]
### Bug Description

I have a problem with Tahoma 1.4 rendering.
When I want to preview my animation it doesn't show most of my drawings when rendering especially when I add effects or blending modes like overlays, multiple etc with clipping mask enabled.
I think the auto stretch layer feature could be the problem 😕.

### Software Version

1.4

### Operating System

Window 11

**Comment by artisteacher** [comment]
Try adding a "Frame stop hold" or etc. to the end of the FX layer. The command is in the cell context menu (though I might have the exact name wrong).

Mesh layers might also need the stop hold.

**Comment by Codeoloketuyi** [comment]
Thanks it worked
