### ISSUE TITLE
New layer blend mode Fx for Tahoma 

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1351]
Hello , is it possible to add a new layer blend mode called "color " to Tahoma.
For example like in Photoshop.
![bmodes](https://github.com/tahoma2d/tahoma2d/assets/137768661/8e03fb3b-80a8-498c-8b4d-8d83417a7d84)

Thank you.

**Comment by beeheemooth** [comment]
Not sure what you mean. You can add different layer blend modes or change layer colors in the FX Browser in preview mode.


![Screen_1152](https://github.com/tahoma2d/tahoma2d/assets/25724133/c8faba25-da7c-4d53-837b-338ef6ba22df)

**Comment by Codeoloketuyi** [comment]
What I mean is, a colorize blend mode that changes the hue and saturation of a color .
Here is a better explanations.

The "Color" blend mode applies the hue and saturation of the top layer to the luminance of the layers beneath it, resulting in a color effect similar to that of the top layer. It's often used to maintain the brightness and contrast of the underlying layers while blending their colors with those of the top layer., 😁

**Comment by Codeoloketuyi** [comment]
![Screenshot_20240323-222046](https://github.com/tahoma2d/tahoma2d/assets/137768661/697945c9-e02c-4447-9989-37959aeff0ff)

**Comment by artisteacher** [comment]
Does the GPUHSLBlend FX (under Shaders) do something similar to what you want?

**Comment by Codeoloketuyi** [comment]
> Does the GPUHSLBlend FX (under Shaders) do something similar to what you want?

Well no it doesn't.
It like the color Doge and color burn FX but does one can't do the job.

**Comment by artisteacher** [comment]
It crashes for me so I can't see what it actually does. 

Was just wondering if some combination of checked/unchecked for Hue, Saturation, and Luminosity would be similar to your description.

**Comment by Codeoloketuyi** [comment]
> It crashes for me so I can't see what it actually does.
> 
> Was just wondering if some combination of checked/unchecked for Hue, Saturation, and Luminosity would be similar to your description.

Ok

**Comment by Codeoloketuyi** [comment]
> It crashes for me so I can't see what it actually does.
> 
> Was just wondering if some combination of checked/unchecked for Hue, Saturation, and Luminosity would be similar to your description.

It would be somehow similar to it.

**Comment by Codeoloketuyi** [comment]
Thanks artisteacher the gpuhsl FX actually behaves like the color blend mode.
So that means I don't need this feature request anymore

**Comment by artisteacher** [comment]
Fantastic!
