### ISSUE TITLE
Preview issue

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1362]
### Bug Description

This is the problem 👇.

### Relevant logs/screenshots

https://github.com/tahoma2d/tahoma2d/assets/137768661/ab566cac-57ea-440c-ac07-8762de6fde74

### Software Version

1.4

### Software Version Information

1.4

### Operating System

Window 11

**Comment by artisteacher** [comment]
I'm not sure exactly what the problem is?

**Comment by Codeoloketuyi** [comment]
The drawing keeps disappearing on preview mode .

**Comment by artisteacher** [comment]
It looks like you have a macroFX. Did you key any of the macro settings? Can you share a screenshot of the macro?

**Comment by Codeoloketuyi** [comment]
No I don't key the macroFx only the camera and layer level.
The macroFx was created for shadows and highlights on the character.

**Comment by artisteacher** [comment]
I can't reproduce so far on macOS. A few things to potentially test:

- If you change one of the macro fx settings (ie. the amount of transparency) to force preview to recalculate, and then play through, is there still a problem?
- If you convert the scene to explicit (bottom of Scene menu) is there any change?
- Is the display issue the same in the preview window (Ctrl+R) ?
- Is this an issue in the most recent nightly build? (this is what I'm using)

**Comment by Codeoloketuyi** [comment]
Am not using the nightly build of Tahoma.
I am currently using the window version of Tahoma.

**Comment by Codeoloketuyi** [comment]
I have noticed the auto stretch layer feature in Tahoma 1.4 doesn't support layers with blending effects , that is why my drawings keeps disappearing when I add any layer blend mode like multiply , or overlays to dose layers.

**Comment by artisteacher** [comment]
Try the nightly build. I recreated your macro - including the blur and mattein & it displays as it should throughout.
