### ISSUE TITLE
Color Palette Not Updating 

### ISSUE THREAD

**Issue by dxh0909** [tahoma2d/tahoma2d#1366]
### Bug Description

In previous versions of Tahoma as well as OpenToonz, if you change one of the colors in the Level Palette, it will update every instance it was used. For example, if you assigned a light blue to color_1 in the Level Palette and drew/painted with it, if you later changed color_1 to a dark red, every instance of the light blue previously assigned to color_1 would be changed to the current dark red. However this is no longer the case. Now it will only apply the new updated color to new drawings instead of updating any older ones. This was such a useful feature and it’s a shame it’s not working properly. 

### Software Version

1.4

### Operating System

macOS Catalina 10.15

### Drawing Tablet

Mouse/ Huion Kamvas 13

**Comment by manongjohn** [comment]
Are you using Smart Raster or Vector levels?

**Comment by dxh0909** [comment]
I was using the default Raster level, I just checked with the other levels
and it worked. Thank you!
