### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by BertWik** [tahoma2d/tahoma2d#1373]
### Bug Description

When I use my stylus to draw, undo does not work anymore. As soon as I use the mouse for drawing it works again. But after using the pen again it does not.
In the nightly built from januari 20 it was still working perfectly!

### Software Version

Nightly (Specify below)

### Software Version Information

januari 30

### Operating System

macOS Sonoma

### Drawing Tablet

Huion Kamvas 24 plus

**Comment by manongjohn** [comment]
@BertWik I believe I know the change that broke undo. Before I revert it, I want to see if I can fix it bit I need some information.

Can you do the following:
1. Open `Preferences -> Touch/Tablet Settings -> Open Viewer Event Log`
2. Use stylus and draw a line on the canvas
3. Confirm undo does not work
4. Copy the log from the viewer event log , paste it into a document
5. Post document here.

Thanks.

**Comment by BertWik** [comment]
Added the log in the Word file:

[Event logging.docx](https://github.com/tahoma2d/tahoma2d/files/14111544/Event.logging.docx)
