### ISSUE TITLE
"Fill in Empty Cells"is not work

### ISSUE THREAD

**Issue by PUTI999** [tahoma2d/tahoma2d#1377]
### Bug Description

It seems"Fill in Empty Cells"is not work

### Relevant logs/screenshots

![I](https://github.com/tahoma2d/tahoma2d/assets/158379585/b2453f37-6980-49dd-8a5b-257e29fc58bc)

### Software Version

Nightly (Specify below)

### Operating System

MacOS Sonoma 14.3

### Graphics Card

Radeon Pro 560X

**Comment by artisteacher** [comment]
If your scene has implicit holds (default behavior), fill in empty cell can't do anything - the drawings already hold until there's a new drawing or stop hold cell. For scenes or levels with explicit holds, drawings need to be manually adjusted to display across multiple frames. In that case, fill in empty cells works just fine.

I'm seeing the command work as expected on macOS.

**Comment by PUTI999** [comment]
I got it, thanks a lot!
