### ISSUE TITLE
Render Preview issue 

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1381]
### Bug Description

I drew a red ball with shadow and highlights as you can see in the video below 👇 to demonstrate the problem.
When I. Want to preview it, it keeps disappearing on render as shown in the video below 👇.
So I don't know what is going on with the preview render of Tahoma 1.4.1 .
Please follow the video to recreate the problem.
I am using windows nightly build.

https://github.com/tahoma2d/tahoma2d/assets/137768661/6b5d1a7e-de99-40b2-8aa1-a32de13fb332

### Steps to reproduce

Create three layers one for shadows and highlights the other for character.
Add multiple and light ino fx the shadow and highlights layer with clipping mask enabled.

### Software Version

1.4.1

### Software Version Information

1.4.1

### Operating System

Window 11

**Comment by manongjohn** [comment]
There is a bit of a known issue with Implicit Holds and some Fx.

As a workaround, try adding a `Stop Frame Hold` at the end of all your columns at the end of the scene and see if that helps.

**Comment by Codeoloketuyi** [comment]
It only works for frames with no FX on it.

**Comment by artisteacher** [comment]
Stop frame hold works for me in frames with FX.

**Comment by Codeoloketuyi** [comment]
Is it possible for you to use the window version of Tahoma to test

**Comment by artisteacher** [comment]
Unfortunately, I don't have a device running Windows. 

Did you switch frames after adding the stop frame holds at the end of each layer?

**Comment by manongjohn** [comment]
@Codeoloketuyi Not sure what you tried, but I recreated your vidoe and here's the workaround that I suggested for the issue with fx and implicit holds:

https://github.com/tahoma2d/tahoma2d/assets/19245851/b3a6b7ad-78c2-4275-a06f-6f040959fdd4

You need to put stop frames on all the levels at the end and regenerate the preview.

**Comment by Codeoloketuyi** [comment]
Oh you didn't mention the regenerat preview part I was unable to preview the render after adding the stop frame hold. Now I understand.
