### ISSUE TITLE
Windows REALLY thinks this is a trojan.

### ISSUE THREAD

**Issue by FlamingFoxProd** [tahoma2d/tahoma2d#1383]
### Bug Description

Quite simply, I can't download it (specifically trying to download the windows installer file). Every time it finishes, Windows detects a virus and doesn't let it finish downloading.

### Steps to reproduce

1. Download the windows installer file
2. There is no step 2

### Relevant logs/screenshots

![clipboard-file-UdWwgH](https://github.com/tahoma2d/tahoma2d/assets/119158149/621e0e4e-a393-4973-a70f-9e5885314991)

### Software Version

1.4.1

### Operating System

Windows 11

**Comment by manongjohn** [comment]
Wow.  I tried downloading it and got the same issue.  Not sure how that happened.

I deleted it and replaced it with a clean one.   I was able to download it without issue after that.  Try again?

**Comment by manongjohn** [comment]
Strange.  Although downloading the new one doesn't automatically get detected, after a few minutes, it suddenly shows up as a threat.  I think Microsoft Defender is falsely identifying something in it as a virus. I am submitting it to Microsoft to review.

**Comment by manongjohn** [comment]
While waiting for Microsoft to get back to me, I did submit the file to virustotal.com and the 66 virus scanners did not detect any viruses in the file.

**Comment by manongjohn** [comment]
![image](https://github.com/tahoma2d/tahoma2d/assets/19245851/725f3381-ee4c-4dcd-b7e0-a9c14335d47c)

**Comment by manongjohn** [comment]
I submitted further information to Microsoft and they again verified there was no virus.  I think they updated definitions, somehow, so it doesn't seem to be flagging it anymore.

Going to close this.

**Comment by classicallytofu** [comment]
This seems to still be an issue with Kaspersky. I actually thought something was wrong because it was labeled as "Trojan", so I let Kaspersky delete the .exe. Now, I'm going to have to download it again.
![Screenshot 2024-12-20 233147](https://github.com/user-attachments/assets/7eaa8928-51cf-4cda-adc1-33382878f4fe)
