### ISSUE TITLE
Preview and Rendering Issues

### ISSUE THREAD

**Issue by 8A2A** [tahoma2d/tahoma2d#1386]
### Bug Description

There are no effects added to the file, it's all hand-drawn raster layers.This was an issue with version 1.4.Updated to the latest version and still does.
![01](https://github.com/tahoma2d/tahoma2d/assets/158819508/d8b95154-294a-4005-984a-051b5eba44b7)
![02](https://github.com/tahoma2d/tahoma2d/assets/158819508/6f84ffad-bbe0-42a8-9046-631babc4a1a9)

### Software Version

1.4.1

### Operating System

WIN 11

**Comment by 8A2A** [comment]
When rendering the output, it's all blank frames.

**Comment by manongjohn** [comment]
Do you have a background layer?

All drawings are transparent by nature so if you dont have a background layer, the background is black. If your lines are not colored, it will appear like there is  nothing on screen.

**Comment by 8A2A** [comment]
It's solved, I accidentally added the "output" effect to a couple of layers, delete it and it will show up.
