### ISSUE TITLE
Incorrect sequence of erasing operations in raster levels when using Frame Range mode with the Shift button held down

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#1391]
### Bug Description

The Eraser Tool in Frame Range mode with the Shift button held down should continue the chain of erasing operations, continuing it from the last processed frame (see Figure (1)) This is exactly the behavior at the moment in OT.

However, the program works differently (see Figure (2)). While holding Shift, the Eraser Tool erases frames starting from the first one, passing through the already processed frames.

### Steps to reproduce

![ezgif-1-b597971a42](https://github.com/tahoma2d/tahoma2d/assets/25724133/72a3e4df-ee6a-4181-9ffe-05287301de4d)

### Relevant logs/screenshots

![Screen_1180](https://github.com/tahoma2d/tahoma2d/assets/25724133/d41456ad-4328-4197-b9fc-fc8318039739)

### Software Version

1.4.1

### Software Version Information

Built^ Feb 4 2024

### Operating System

windows 8.1

### Graphics Card

NVIDIA GeForce 9500 GT

### Drawing Tablet

Huion KAMVAS PRO 20 (2019)

**Comment by andeon** [comment]
I think the behavior changed after this commit https://github.com/tahoma2d/tahoma2d/pull/1309 when working in timeline/xsheet. If you use the Level Strip "Level" it will work as shown, but may not work in some of your workflows.
