### ISSUE TITLE
Tape Tool Crash

### ISSUE THREAD

**Issue by pngween** [tahoma2d/tahoma2d#1402]
### Bug Description

Crash using tape tool

### Steps to reproduce

Using symmetry in grid and overlays, use the tape tool to connect two points
then bam crash

### Software Version

1.4.1

### Operating System

Windows 10

### Graphics Card

Integrated Graphics Vega 7

**Comment by beeheemooth** [comment]
I confirm this.

**Comment by beeheemooth** [comment]
![ezgif-2-39cccf6a7c](https://github.com/tahoma2d/tahoma2d/assets/25724133/1c6880fa-0416-44f6-b7b9-4f7603e7e617)


[crash.zip](https://github.com/tahoma2d/tahoma2d/files/14434342/crash.zip)

**Comment by manongjohn** [comment]
Ok.  I think it might be related to Join Vectors.  When it's off for me, symmetry works fine.  However if I turn it on, I get odd results and eventually it crashes.  Will look into it.
