### ISSUE TITLE
Repetitive crash

### ISSUE THREAD

**Issue by Watermelontears** [tahoma2d/tahoma2d#1403]
### Bug Description

crashes randomly, doesnt seem to do it under specific circumstances, but maybe the log will show.

### Steps to reproduce

probably just animate and use for more then an hour or two, a crash will happen.

### Relevant logs/screenshots

Tahoma2D 1.4.1  (Build Feb  1 2024)

Report Date: 2024-02-28 13:46:06
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 (10.0)
OS Kernel: 10.0.22631
CPU Threads: 12

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon RX 6750 XT
GPU Version: 4.6.0 Compatibility Profile Context 23.12.1.231124

Crash File: C:\Users\New PC\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240228-134606.log
Mini Dump File: C:\Users\New PC\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240228-134606.dmp

Application Dir: C:/Program Files (x86)/Tahoma2D
Stuff Dir: C:\Program Files (x86)\Tahoma2D\tahomastuff

Project Name: powderrrrrr
Scene Name: powdddddddrrrr
Project Path: C:\Users\New PC\Documents\powderrrrrr\tahomaproject.xml
Scene Path: C:\Users\New PC\Documents\powderrrrrr\scenes\powdddddddrrrr.tnz

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffce5127a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffce50ce242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffce515340e] <ntdll.dll>
  4> RasterBlurredBrush::getBoundFromPoints {bluredbrush.cpp:508} <tnztools.dll>
  5> FullColorEraserTool::leftButtonUp {fullcolorerasertool.cpp:711} <tnztools.dll>
  6> SceneViewer::onRelease {sceneviewerevents.cpp:1042} <Tahoma2D.exe>
  7> SceneViewer::tabletEvent {sceneviewerevents.cpp:350} <Tahoma2D.exe>
  8> QWidget::event [0x6549877b] <Qt5Widgets.dll>
  9> SceneViewer::event {sceneviewerevents.cpp:1501} <Tahoma2D.exe>
 10> QApplicationPrivate::notify_helper [0x65476be4] <Qt5Widgets.dll>
 11> QApplication::notify [0x654752a8] <Qt5Widgets.dll>
 12> QCoreApplication::notifyInternal2 [0x64fad4aa] <Qt5Core.dll>
 13> QDesktopWidget::workAreaResized [0x654c1ffc] <Qt5Widgets.dll>
 14> QDesktopWidget::workAreaResized [0x654bfc96] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x65476be4] <Qt5Widgets.dll>
 16> QApplication::notify [0x65475aa3] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x64fad4aa] <Qt5Core.dll>
 18> QGuiApplicationPrivate::processTabletEvent [0x7ffc0c2bbc62] <Qt5Gui.dll>
 19> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc0c29f9a0] <Qt5Gui.dll>
 20> QEventDispatcherWin32::processEvents [0x64ff2ac9] <Qt5Core.dll>
 21> DispatchMessageW [0x7ffce4678241] <USER32.dll>
 22> DispatchMessageW [0x7ffce4677d01] <USER32.dll>
 23> QEventDispatcherWin32::processEvents [0x64ff2300] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ffc12880339] <qwindows.dll>
 25> QEventLoop::exec [0x64fa9c0c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x64fac4b4] <Qt5Core.dll>
 27> main {main.cpp:899} <Tahoma2D.exe>
 28> WinMain [0x7ff7640d6864] <Tahoma2D.exe>
 29> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 30> BaseThreadInitThunk [0x7ffce3d9257d] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7ffce510aa58] <ntdll.dll>
==== End ====

==== Modules ====
C:\Program Files (x86)\Tahoma2D\Tahoma2D.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Program Files (x86)\Tahoma2D\Qt5Xml.dll
C:\Windows\System32\win32u.dll
C:\Program Files (x86)\Tahoma2D\Qt5PrintSupport.dll
C:\Program Files (x86)\Tahoma2D\Qt5SerialPort.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\shcore.dll
C:\Program Files (x86)\Tahoma2D\freeglut.dll
C:\Program Files (x86)\Tahoma2D\libgphoto2.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files (x86)\Tahoma2D\EDSDK.dll
C:\Program Files (x86)\Tahoma2D\libgphoto2_port.dll
C:\Program Files (x86)\Tahoma2D\colorfx.dll
C:\Program Files (x86)\Tahoma2D\image.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files (x86)\Tahoma2D\tfarm.dll
C:\Program Files (x86)\Tahoma2D\tnzstdfx.dll
C:\Program Files (x86)\Tahoma2D\sound.dll
C:\Program Files (x86)\Tahoma2D\tnztools.dll
C:\Program Files (x86)\Tahoma2D\toonzlib.dll
C:\Program Files (x86)\Tahoma2D\toonzqt.dll
C:\Program Files (x86)\Tahoma2D\Qt5Script.dll
C:\Program Files (x86)\Tahoma2D\opencv_world451.dll
C:\Program Files (x86)\Tahoma2D\tnzext.dll
C:\Program Files (x86)\Tahoma2D\tnzbase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files (x86)\Tahoma2D\Qt5OpenGL.dll
C:\Program Files (x86)\Tahoma2D\Qt5Widgets.dll
C:\Program Files (x86)\Tahoma2D\Qt5Multimedia.dll
C:\Program Files (x86)\Tahoma2D\tnzcore.dll
C:\Program Files (x86)\Tahoma2D\Qt5Network.dll
C:\Program Files (x86)\Tahoma2D\Qt5Core.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files (x86)\Tahoma2D\Qt5Gui.dll
C:\Windows\SYSTEM32\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files (x86)\Tahoma2D\glew32.dll
C:\Program Files (x86)\Tahoma2D\libmypaint-1-4-0.dll
C:\Program Files (x86)\Tahoma2D\Qt5Svg.dll
C:\Windows\SYSTEM32\CONCRT140.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files (x86)\Tahoma2D\libintl-8.dll
C:\Program Files (x86)\Tahoma2D\libjson-c-2.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Program Files (x86)\Tahoma2D\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files (x86)\Tahoma2D\platforms\qwindows.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files (x86)\Tahoma2D\iconengines\qsvgicon.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\uiautomationcore.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0398226.inf_amd64_c5d9587384e4b5ff\B398182\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0398226.inf_amd64_c5d9587384e4b5ff\B398182\atio6axx.dll
C:\Windows\SYSTEM32\amdihk64.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\ApplicationTargetedFeatureDatabase.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qgif.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qicns.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qico.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qjpeg.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qsvg.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qtga.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qtiff.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qwbmp.dll
C:\Program Files (x86)\Tahoma2D\imageformats\qwebp.dll
C:\Windows\System32\threadpoolwinrt.dll
C:\Program Files (x86)\Tahoma2D\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Program Files (x86)\Tahoma2D\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Program Files (x86)\Tahoma2D\mediaservice\dsengine.dll
C:\Windows\SYSTEM32\EVR.dll
C:\Windows\SYSTEM32\dxva2.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\UMPDC.dll
C:\Windows\System32\devenum.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\msdmo.dll
C:\Program Files (x86)\Tahoma2D\EdsImage.dll
C:\Windows\System32\PortableDeviceApi.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\winrnr.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\nlansp_c.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\NetworkExplorer.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2506_none_270c5ae97388e100\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\edputil.dll
==== End ====

### Software Version

1.4.1

### Operating System

windows 11

### Graphics Card

 AMD Radeon RX 6750 XT

### Drawing Tablet

xp-pen 15.6 pro

**Comment by manongjohn** [comment]
Can you get me this file from your computer: 
C:\Users\New PC\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240228-134606.dmp
