### ISSUE TITLE
Levels opacity issue 

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1432]
### Bug Description

Their is something wrong with the level opacity when I use it on onion skin.

### Steps to reproduce

Create two layers Set one level layer opacity to 50% and activate onion skin then try to draw on the other level layer will using onion skin.

The level layer opacity doesn't stay at 50% when I am using onion skinning.

### Software Version

1.4.1

### Software Version Information

1.4.2 nightly build 

### Operating System

Window 11

**Comment by artisteacher** [comment]
Yes, it seems that the onionskin overrides whatever the layer opacity is while onionskin is active. I wonder if it was deliberate? To make it clear which drawing is the active one? 

It also looks like the layer filters don't work well on certain colors (like #F7F55E) - whether or not onionskin is active.

**Comment by Codeoloketuyi** [comment]
> Yes, it seems that the onionskin overrides whatever the layer opacity is while onionskin is active. I wonder if it was deliberate? To make it clear which drawing is the active one?
> 
> It also looks like the layer filters don't work well on certain colors (like #F7F55E) - whether or not onionskin is active.

Yes you are correct 💯

**Comment by artisteacher** [comment]
Light Table opacity is respected when Onionskin is on, so for better consistency, it probably makes sense for onionskin to respect layer opacity.
