### ISSUE TITLE
Crashes After Closing

### ISSUE THREAD

**Issue by Meemoo-twenny-too** [tahoma2d/tahoma2d#1442]
### Bug Description

Enabled Advanced Controls and then the next time I closed the programme, the error EXCEPTION_ACCESS_VIOLATION came up (after closing)

It seems similar to this issue https://github.com/tahoma2d/tahoma2d/issues/1390 except it happens after closing the programme. Also I don't have the file they reccomended deleting

### Steps to reproduce

Enabled Advanced Controls in Preferences, closed T2D, reopened it and this error appeared next time I closed the programme. This now happens every time (after) I close the programme. 

### Relevant logs/screenshots

Tahoma2D 1.4.2  (Build Apr  2 2024)

Report Date: 2024-04-11 11:35:21
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 (10.0)
OS Kernel: 10.0.19045
CPU Threads: 4

Crash File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240411-113521.log
Mini Dump File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240411-113521.dmp

Application Dir: C:/Program Files/Tahoma2D
Stuff Dir: C:\Program Files\Tahoma2D\tahomastuff

Project Name: Otherwold Template 12FPS
Scene Name: 
Project Path: C:\Users\USER\Documents\Otherwold Template 12FPS\tahomaproject.xml
Scene Path: 

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd27948b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd279212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd27970ebe] <ntdll.dll>
  4> std::operator<<<std::char_traits<char> > {ostream:737} <tnzcore.dll>
  5> TOStream::TOStream {tstream.cpp:247} <tnzcore.dll>
  6> TOStream::child {tstream.cpp:485} <tnzcore.dll>
  7> ExportPanel::saveExportSettings {exportpanel.cpp:968} <Tahoma2D.exe>
  8> ExportPanel::~ExportPanel {exportpanel.cpp:914} <Tahoma2D.exe>
  9> ExportPanel::`scalar deleting destructor' [0x7ff7457877c4] <Tahoma2D.exe>
 10> QObjectPrivate::deleteChildren [0x73bce0bb] <Qt5Core.dll>
 11> QWidget::~QWidget [0x74093475] <Qt5Widgets.dll>
 12> Room::`scalar deleting destructor' [0x7ff74570aeeb] <Tahoma2D.exe>
 13> QObjectPrivate::deleteChildren [0x73bce0bb] <Qt5Core.dll>
 14> QWidget::~QWidget [0x74093475] <Qt5Widgets.dll>
 15> QStackedWidget::`scalar deleting destructor' [0x7ff74570ae15] <Tahoma2D.exe>
 16> QObjectPrivate::deleteChildren [0x73bce0bb] <Qt5Core.dll>
 17> QWidget::~QWidget [0x74093475] <Qt5Widgets.dll>
 18> MainWindow::~MainWindow {mainwindow.cpp:525} <Tahoma2D.exe>
 19> main {main.cpp:904} <Tahoma2D.exe>
 20> WinMain [0x7ff745ce8624] <Tahoma2D.exe>
 21> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 22> BaseThreadInitThunk [0x7ffd26a17344] <KERNEL32.DLL>
 23> RtlUserThreadStart [0x7ffd279226b1] <ntdll.dll>
==== End ====

==== Modules ====
C:\Program Files\Tahoma2D\Tahoma2D.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Program Files\Tahoma2D\Qt5Xml.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Program Files\Tahoma2D\Qt5PrintSupport.dll
C:\Program Files\Tahoma2D\Qt5SerialPort.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
C:\Program Files\Tahoma2D\freeglut.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Program Files\Tahoma2D\EDSDK.dll
C:\Program Files\Tahoma2D\libgphoto2.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\Tahoma2D\libgphoto2_port.dll
C:\Program Files\Tahoma2D\colorfx.dll
C:\Program Files\Tahoma2D\image.dll
C:\Program Files\Tahoma2D\tnztools.dll
C:\Program Files\Tahoma2D\tnzstdfx.dll
C:\Program Files\Tahoma2D\tfarm.dll
C:\Program Files\Tahoma2D\toonzqt.dll
C:\Program Files\Tahoma2D\sound.dll
C:\Program Files\Tahoma2D\opencv_world451.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\Tahoma2D\toonzlib.dll
C:\Program Files\Tahoma2D\Qt5Script.dll
C:\Program Files\Tahoma2D\tnzext.dll
C:\Program Files\Tahoma2D\tnzbase.dll
C:\Program Files\Tahoma2D\tnzcore.dll
C:\Program Files\Tahoma2D\Qt5OpenGL.dll
C:\Program Files\Tahoma2D\Qt5Widgets.dll
C:\Program Files\Tahoma2D\Qt5Multimedia.dll
C:\Program Files\Tahoma2D\Qt5Gui.dll
C:\Program Files\Tahoma2D\Qt5Network.dll
C:\Program Files\Tahoma2D\Qt5Core.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\MSVCP140.dll
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\Tahoma2D\libmypaint-1-4-0.dll
C:\Program Files\Tahoma2D\glew32.dll
C:\Program Files\Tahoma2D\Qt5Svg.dll
C:\Windows\SYSTEM32\CONCRT140.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\Tahoma2D\libintl-8.dll
C:\Program Files\Tahoma2D\libjson-c-2.dll
C:\Program Files\Tahoma2D\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\Tahoma2D\platforms\qwindows.dll
C:\Windows\SYSTEM32\ig8icd64.dll
C:\Windows\SYSTEM32\igdusc64.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\Tahoma2D\iconengines\qsvgicon.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\d3d9.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\d3d11.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\dxgi.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\Tahoma2D\imageformats\qgif.dll
C:\Program Files\Tahoma2D\imageformats\qicns.dll
C:\Program Files\Tahoma2D\imageformats\qico.dll
C:\Program Files\Tahoma2D\imageformats\qjpeg.dll
C:\Program Files\Tahoma2D\imageformats\qsvg.dll
C:\Program Files\Tahoma2D\imageformats\qtga.dll
C:\Program Files\Tahoma2D\imageformats\qtiff.dll
C:\Program Files\Tahoma2D\imageformats\qwbmp.dll
C:\Program Files\Tahoma2D\imageformats\qwebp.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Program Files\Tahoma2D\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Program Files\Tahoma2D\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Program Files\Intel\iCLS Client\ssleay32.dll
C:\Program Files\Intel\iCLS Client\LIBEAY32.dll
C:\Windows\SYSTEM32\wkscli.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\igd10iumd64.dll
C:\Windows\SYSTEM32\ncrypt.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\SYSTEM32\NTASN1.dll
==== End ====

### Software Version

1.4.2

### Operating System

Windows 10

**Comment by manongjohn** [comment]
I can't reproduce this.

According to the crash log, it's trying to save Export panel settings to a file and it's failing to write it.  Looks like you have an Export panel open when you are trying to quit.  Did you add it to one of your room layouts? Export panel and saving it's settings don't really have anything to do with the Show Advanced Preferences and Options setting. 

Try this...delete the file `C:\Program Files\Tahoma2D\tahomastuff\config\exportsettings.txt` and see if the problem persists.  If for some reason that's not there, maybe that folder can't be written to for some odd reason.  Check the permissions on the `config` folder, go to the Security tab and make sure you see your login and it has full permissions.

**Comment by Meemoo-twenny-too** [comment]
Yeah I added an Export panel to one of my Rooms. Misdiagnosis on my end!

There isn't a file called exportsettings.txt (there is export-toonz.lua) but I changed the permissions and that fixed it!

**Comment by manongjohn** [comment]
Glad that worked.

Might want to double check the `tahomastuff` folder's permissions are correct.  If not, correct it and make sure it's applied to all files/folders below.
