### ISSUE TITLE
FX folder 

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1443]
The ability to create folders to organize FX in the FX schematic in Tahoma just like in level layer .
And the folder can be affected by an FX if applied to it .

**Describe the solution you'd like**
![Screenshot 2024-04-14 134548](https://github.com/tahoma2d/tahoma2d/assets/137768661/cfd1d0da-d63e-4124-9b76-3b29534bfcb5)
![Screenshot 2024-04-14 134710](https://github.com/tahoma2d/tahoma2d/assets/137768661/8332f700-65db-4fda-966a-e4a2b2694569)

**Comment by manongjohn** [comment]
You can Group (Ctrl+G) the Fx nodes in the FX schematic similar to grouping columns to create folders in the timeline/xsheet.

The Column Folders are purposefully not emulated as groups in the FX schematic, and vice versa.

**Comment by Codeoloketuyi** [comment]
Ok thanks
