### ISSUE TITLE
I CAN'T SEE SOME OF MY LAYERS IN MY PROJECT AGAIN

### ISSUE THREAD

**Issue by brooocci** [tahoma2d/tahoma2d#1453]
### Bug Description

I don't know if this is a bug or not but idk where else to put this
I animated in 3's
So I was working on a project and all of a sudden a bunch o X's came unto the x sheet and now I can't see the frames in-between again unless they're drawn into that space
I dunno if I pressed something wrong, just help me get rid of this issue please...

### Steps to reproduce

I don't know how to..

### Relevant logs/screenshots

![Screen Shot 2024-05-01 at 11 01 32 AM](https://github.com/tahoma2d/tahoma2d/assets/112030787/f6dd8a0c-6071-414e-a8db-fe94453f7c1f)

### Software Version

1.4

### Software Version Information

idk stable.. whatever

### Operating System

macOS Montery 12.6

### Drawing Tablet

Huion 1060

**Comment by manongjohn** [comment]
It appears you switched off Implicit Hold mode.  In Explicit Hold mode, you need to re-expose frames in order for them to keep showing.

Toggle it back to Implicit Hold mode on by clicking on this button in the Quick Toolbar:
![image](https://github.com/tahoma2d/tahoma2d/assets/19245851/87b15fcc-d13d-4007-9ba0-8ef9e41a9341)

**Comment by brooocci** [comment]
Awesome! Thank you so much!!
