### ISSUE TITLE
Levels exporter is blank

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1454]
### Bug Description

The levels exporter in Tahoma is blank no function or button.

### Steps to reproduce

Go to the levels tab in Tahoma.
Then click on export levels there you will see the problem .

### Software Version

1.4.2

### Software Version Information

1.4.3

### Operating System

Window 11

**Comment by manongjohn** [comment]
Confirmed. Will work on fixing.
