### ISSUE TITLE
close gap feature not working

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1475]
### Bug Description

whenever I try the close gap or fill feature in Tahoma it seems to not work at all in closing the gap.
can this be fixed.

### Steps to reproduce

create a smart raster level and draw a circle with a small opening and try filling it with the bucket tool.

### Relevant logs/screenshots

https://github.com/tahoma2d/tahoma2d/assets/137768661/ce951820-da82-433a-9616-94d6d5ecd2a3

https://github.com/tahoma2d/tahoma2d/assets/137768661/ff1f5a94-9144-4a38-973c-acce6c28ba01

Uploading 2024-05-21 16-16-23.mp4…

here are examples illustrating the problem

### Software Version

Nightly (Specify below)

### Software Version Information

1.4.3

### Operating System

window 10

**Comment by artisteacher** [comment]
Have you tried increasing the gap distance? That's the slider just to the right.

**Comment by Codeoloketuyi** [comment]
Thanks 🙏 I solved the problem.
