### ISSUE TITLE
Automatic painting feature not working properly

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1498]
### Bug Description

The automatic paint feature in tahoma doesn't seem to work properly when I use it to paint irregular shapes for example.

https://github.com/tahoma2d/tahoma2d/assets/137768661/ce62779c-c463-4978-babb-05296336083c

https://github.com/tahoma2d/tahoma2d/assets/137768661/581a3a7e-4bd9-4f6d-96bb-61d50b818df1

### Steps to reproduce

Create a Rasta level in Tahoma.
Then animate an irregular object with different shapes and sizes.

Then go to the fill tool select a color at random and fill the first frame of the animation then go to the fiill tool settings bar on frame range pick linear mode and pick the fill type to be area.

Then click on the first frame ,after that click on the last frame and see the results you get.
Some of the frames in the animation are not filled.

### Software Version

Nightly (Specify below)

### Software Version Information

Nightly build

### Operating System

Windows 11

**Comment by manongjohn** [comment]
It is working however you'll need to understand how it works and its limitations...

When you pick the 1st and last points, essentially a line is drawn between them.  On each frame, the logic moves along this line and determines a point some distance from the previous point based on the number of frames involved and the actual distance between the 1st and last point and the interpolation method chosen.  The point it determines is the fill point. If the point happens to fall in that shape, it will fill, if not, it may fill something else.

Its up to you to find a good set of points to use especially on an irregular shape. The more irregular it is, the likely it may not fill correctly.

**Comment by Codeoloketuyi** [comment]
Ok I understand now
