### ISSUE TITLE
Clipping masks

### ISSUE THREAD

**Issue by terrants** [tahoma2d/tahoma2d#150]
I would love to know if tahoma has clipping masks and if not,may you please add it to the app,thank you

**Comment by artisteacher** [comment]
If you mean clipping masks in the way that they work in Photoshop, then no - Tahoma doesn't have that. However if you want to mask out/in part of a level, you can use the various [matte FXs](https://tahoma.readthedocs.io/en/latest/applying_special_fx.html?highlight=matte#matte). Any FX are only visible with preview on or in the final render.

**Comment by artisteacher** [comment]
Clipping masks were recently merged & will be part of the 1.4 release!
