### ISSUE TITLE
`Save Palatte As` does nothing.

### ISSUE THREAD

**Issue by melieconiek** [tahoma2d/tahoma2d#1524]
### Bug Description

`Save Palette As` in the level palette window's hamburger menu does nothing when clicked.

### Steps to reproduce

1. Open the palette window click on the hamburger and `Save Palette As`.

### Software Version

1.4.3

### Software Version Information

Nightly - Jul 5th

### Operating System

Windows 10

**Comment by beeheemooth** [comment]
It's strange that this option works from a shortcut.
