### ISSUE TITLE
crashes while starting

### ISSUE THREAD

**Issue by zsinton** [tahoma2d/tahoma2d#1533]
### Bug Description

Installed Tahoma2D, unpacked it, but whenever i try to open the application its crashing unexpectedly 

### Relevant logs/screenshots

Tahoma2D 1.4.3  (Build Jun  2 2024)

Report Date: 2024-07-27 11:56:46
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 (10.0)
OS Kernel: 10.0.22631
CPU Threads: 16

Crash File: C:\Users\Lenya\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240727-115646.log
Mini Dump File: C:\Users\Lenya\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20240727-115646.dmp

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fff83847f5a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fff837ee642] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff8387403e] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7fff4fd0413e] <MSVFW32.dll>
  6> ICOpen [0x7fff4fd03da4] <MSVFW32.dll>
  7> <lambda_d6bfe711d5006a7e839b6cb4b48df02e>::operator() {tiio_avi.cpp:1072} <image.dll>
  8> `anonymous namespace'::safe_ICOpen {tiio_avi.cpp:1084} <image.dll>
  9> Tiio::AviWriterProperties::AviWriterProperties {tiio_avi.cpp:1136} <image.dll>
 10> initImageIo {tiio.cpp:213} <image.dll>
 11> initToonzEnv {main.cpp:189} <Tahoma2D.exe>
 12> main {main.cpp:585} <Tahoma2D.exe>
 13> WinMain [0x7ff66bd88f74] <Tahoma2D.exe>
 14> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 15> BaseThreadInitThunk [0x7fff8250257d] <KERNEL32.DLL>
 16> RtlUserThreadStart [0x7fff8382af28] <ntdll.dll>
==== End ====

==== Modules ====
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Tahoma2D.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Xml.dll
C:\Windows\System32\win32u.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5SerialPort.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5PrintSupport.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\bcrypt.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\freeglut.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\EDSDK.dll
C:\Windows\System32\SHLWAPI.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\libgphoto2.dll
C:\Windows\System32\WS2_32.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\libgphoto2_port.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\colorfx.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\image.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\tnzstdfx.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\tfarm.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\tnztools.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\toonzqt.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\sound.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\toonzlib.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\tnzext.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Script.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\tnzbase.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5OpenGL.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\tnzcore.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\opencv_world451.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Widgets.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Multimedia.dll
C:\Windows\System32\OLEAUT32.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Core.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Gui.dll
C:\Windows\SYSTEM32\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\glew32.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\libmypaint-1-4-0.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\Qt5Svg.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\libintl-8.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\libjson-c-2.dll
C:\Windows\SYSTEM32\dxcore.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\platforms\qwindows.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
D:\Benutzerdaten\Downloads\Tahoma2D-portable-win (2)\Tahoma2D\iconengines\qsvgicon.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0401134.inf_amd64_35bda0dee1499017\B399690\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0401134.inf_amd64_35bda0dee1499017\B399690\atio6axx.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\System32\DriverStore\FileRepository\u0401134.inf_amd64_35bda0dee1499017\B399690\amdihk64.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\ApplicationTargetedFeatureDatabase.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Windows\SYSTEM32\lvcod64.dll
==== End ====

### Software Version

1.4.3

### Operating System

Windows 11

### Graphics Card

AMD Ryzen 7 7800X3D

**Comment by manongjohn** [comment]
There is a known issue with a Logitech DLL that affects T2D and some other art programs.

Current recommendation to fix this is to either rename or delete the following file:
`C:\Windows\SYSTEM32\lvcod64.dll`

Actually, before you do anything, can you zip up that file and attach it to this ticket? Trying to get a copy of the problematic DLL.

**Comment by zsinton** [comment]
@manongjohn renaming the file worked, thank you!

**Comment by manongjohn** [comment]
@zsinton Any chance you can zip and post the DLL to this ticket?

**Comment by zsinton** [comment]
@manongjohn 
[lvcod64 - Kopie.zip](https://github.com/user-attachments/files/16413236/lvcod64.-.Kopie.zip)

**Comment by manongjohn** [comment]
@zsinton If you are able to and willing, I could use your help testing a potential fix for this issue.  Can you please perform the following steps to verify:

1. Rename your lvcod64 - Kopie.dll back to `C:\Windows\SYSTEM32\lvcod64.dll`
2. Click this link to download a T2D portable build with the potential fix: https://github.com/manongjohn/tahoma2d/actions/runs/10184642502/artifacts/1761405437
3. Unzip to a different location than your normal one and run it.  Let me know if it actually loads or still crashes.
4. Just to make sure, try running the original T2D and verify it crashes.

Thanks.
