### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by nicholsaz** [tahoma2d/tahoma2d#1577]
### Bug Description

on launch app crashes and generates a log window

### Steps to reproduce

launch app

### Relevant logs/screenshots

Tahoma2D 1.4.4  (Build Aug  1 2024)

Report Date: 2024-09-17 07:21:28
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 15.0
OS Kernel: 24.0.0
CPU Threads: 10

Crash File: /Users/USER/Library/Application Support/Tahoma2D/Tahoma2D/crash/Crash-20240917-072128.log

==== Backtrace ====
  1> 0x0 (in ???)
  2> abort (in libsystem_c.dylib) + 126
  3> __cxxabiv1::__aligned_malloc_with_fallback(unsigned long) (in libc++abi.dylib) + 0
  4> demangling_terminate_handler() (in libc++abi.dylib) + 266
  5> _objc_terminate() (in libobjc.A.dylib) + 104
  6> std::__terminate(void (*)()) (in libc++abi.dylib) + 6
  7> __cxa_get_exception_ptr (in libc++abi.dylib) + 0
  8> __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (in libc++abi.dylib) + 0
  9> TSystem::mkDir(TFilePath const&) (in libtnzcore.dylib) (tsystem.cpp:0)
 10> main (in Tahoma2D) (main.cpp:583)
 11> 0x204e052cd (in ???)
==== End ====

### Software Version

1.4.4

### Operating System

MacOS 15

### Graphics Card

Apple M1 Pro GPU

### Drawing Tablet

Mouse

**Comment by manongjohn** [comment]
If I had to guess, either you didnt move the application out of the DMG file or when prompted, you didnt grant security access to whatever it would have prompted you for.

Please drag the application out of DMG file and move to someplace on your machine. Grant access to whatever it asks for to ensure no issues using the software.

**Comment by nicholsaz** [comment]
I just discovered (did all you suggested) that after restarting the MacBook Pro, it ran fine.I appreciate your assistance!MarkOn Sep 17, 2024, at 8:03 AM, manongjohn ***@***.***> wrote:﻿
If I had to guess, either you didnt move the application out of the DMG file or when prompted, you didnt grant security access to whatever it would have prompted you for.
Please drag the application out of DMG file and move to someplace on your machine. Grant access to whatever it asks for to ensure no issues using the software.
