### ISSUE TITLE
Record audio crash

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#158]
**Describe the bug**
Clicking on the record button on the "Record Audio" window causes a crash

**To Reproduce**
List steps to reproduce the behavior.
1. Open the "Record Audio" window
2. Click record

**Expected behavior**
Audio to record without a crash.

**Crash Report**
[record_audio.txt](https://github.com/turtletooth/tahoma/files/5208925/record_audio.txt)

**Device Information:**
 - OS: macOS 10.15.6 & 10.14.6
 - Tahoma Version: 1.0.1

**Comment by jeremybullock** [comment]
Does this happen on OpenToonz.  The audio code between the two is identical.  If this doesn't happen in OT, it may be due to a different version of Qt.  Either way, I'll take a look.  The windows and mac audio code is handled differently though.  So it may be a case of "Hey can you test this. . ."

**Comment by artisteacher** [comment]
No crash on OT. But there is a crash on OTX. Could being portable make a difference?

> So it may be a case of "Hey can you test this. . ."

I'm happy to test as needed.

**Comment by manongjohn** [comment]
Might be a QT version issue. OT still builds on an older version I believe. OTX (mac) uses the latest QT.

What version are you building with?

For OTX, I have found there have been issues with more recent QT versions in both macOS and linux versions since 5.13, I think. With Linux I was able to force builds to use QT 5.9.7 like I do with Windows buildd, but I can't do that with macOS builds through Travis. If I could, I would probably use 5.12.

**Comment by artisteacher** [comment]
I've been using 5.15.0.

**Comment by jeremybullock** [comment]
@artisteacher could you test this on OTX and see what happens?

**Comment by artisteacher** [comment]
There's an immediate crash after pressing record.
<img width="835" alt="Screen Shot 2020-10-05 at 1 24 42 PM" src="https://user-images.githubusercontent.com/21159116/95111923-354b5c80-070e-11eb-9a28-40783db03d5c.png">

**Comment by manongjohn** [comment]
Division by 0 error?

**Comment by manongjohn** [comment]
@artisteacher Does Tahoma2D have permission to use your microphone on your mac?  Did it ever prompt you for it? That might explain the crash if it is trying to use something it doesn't have access to.

I saw a report that when someone using QT Creator tried to access the microphone on macOS and it prompted for access, however their installed program wouldn't prompt for access and couldn't record, though they didn't have a crash.

**Comment by artisteacher** [comment]
It hasn't asked to use the microphone even though it should - #228.

**Comment by artisteacher** [comment]
The camera permission dialog comes up just fine. The only difference I see, is that there's not a camera active by default. You have to select the built-in camera to use it - which triggers the prompt. In the record audio dialog, the built-in microphone is already selected. Perhaps if the microphone had to be manually selected, it would trigger the prompt for permissions? In turn, being able to allow the microphone to run might prevent the crash?

**Comment by manongjohn** [comment]
Have you tried manually granting Tahoma2D access to the microphone to see if that helps?

**Comment by artisteacher** [comment]
There's not an option to. In some of the other permissions categories, you can drag & drop to add an app, or there's a + button to choose an app. That's not the case for the microphone. They only show up here after approving or disapproving the permissions prompt.
<img width="360" alt="Screen Shot 2020-10-06 at 11 34 52 PM" src="https://user-images.githubusercontent.com/21159116/95284700-d16b8580-082c-11eb-9006-9d18e6bf89b1.png">

**Comment by jeremybullock** [comment]
I'm going to try what you suggested @artisteacher 
Let's see if having the user manually select an audio device does anything.

**Comment by artisteacher** [comment]
Several people with similar issues say that [the following](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos#3036317) is necessary for the microphone permissions to work properly:
<img width="753" alt="Screen Shot 2020-10-09 at 9 50 15 PM" src="https://user-images.githubusercontent.com/21159116/95642882-79758e80-0a79-11eb-8e73-bd871afe16fe.png">
But targeting audio instead of video.

**Comment by jeremybullock** [comment]
Do you want me to hide this feature on the mac side for now?

**Comment by artisteacher** [comment]
Yeah, until it is resolved, that's probably for the best.

**Comment by artisteacher** [comment]
@manongjohn do you get a crash on your mac VM's?

**Comment by manongjohn** [comment]
Unfortunately, I can't get the audio to work on my VM so i can't do anything to fix this since I can't get it to crash and try potential workarounds.

I tried to do a little research to see what might fix the problem. Most responses point to what we have done but still not triggering the request for audio permission.

Have you tried with the latest OT nightlies or Github builds now that they've updated their build environment? Curious if it still works fine.

**Comment by artisteacher** [comment]
Good point. I'll give that a try.

**Comment by artisteacher** [comment]
It does crash when recording audio in OT with the latest nightlies.

**Comment by shun-iwasawa** [comment]
In my environment, adding `NSMicrophoneUsageDescription` and [removing the sample rate condition in the audio settings](https://github.com/opentoonz/opentoonz/pull/3763/files#diff-a22302ecad38a56df4906302ef725392d71686b09a0c46dcafd48e3d62e8397cR176-R180) seems to fix the crash.
