### ISSUE TITLE
[Linux] Compile Error: 'Recursive' is not a member of 'QMutex'

### ISSUE THREAD

**Issue by deathchimera** [tahoma2d/tahoma2d#1600]
### Bug Description

Not sure if it's just me, but my build is failing to compile for 1.4.5, and 1.5. It looks like the error's coming from the file - toonz/sources/include/tthreadmessage.h. The '#include' highlighted in the second screenshot below appears to be the only error when opening up the project in VS Code. I'm guessing either it's a dependency issue, or a Linux-only issue.

Maybe someone knows what's going on behind the scenes that would be causing this?

### Steps to reproduce

Follow build instructions

### Relevant logs/screenshots

compile error
![err01](https://github.com/user-attachments/assets/bae4c438-02be-44c5-a888-7663737e336a)
editor error
![err02](https://github.com/user-attachments/assets/d60279e1-6567-48be-a44d-6413dc364fcb)
where the compile error points to (line 87)
![err03](https://github.com/user-attachments/assets/0dd67e26-1c5e-4d0d-9ab0-a248337437d2)

### Software Version

1.4.4

### Operating System

Void Linux

**Comment by manongjohn** [comment]
Only reason I can think of that may cause that compiler error is that you are compiling against Qt6?

Do you have both Qt 5.15.x and Qt6 installed on your machine? Maybe it's somehow using the wrong library?

**Comment by MegaMcVolt** [comment]
Hi!
I have the same problem and YES, Qt5 and Qt6 are installed on my system (Slackware 15.0 x86_64 current), in the following folders:
`QT5DIR=/usr/lib64/qt5/bin`
`QT6DIR=/usr/lib64/qt6/bin`
And the Qt5 and Qt6 libraries are located in:
`/usr/lib64`

I understand that for successful compilation it is necessary to remove Qt6 ...

But is there really no way to somehow get around this, for example by explicitly telling the compiler to link only with Qt5?

**Comment by manongjohn** [comment]
My Linux build environments do not currently have both Qt5.15 and Qt6 on it so I haven't run into this issue, yet.

Have you tried explicitly setting LD_LIBRARY_PATH for Qt5.15?

I'm not sure how you are building, I know when I compile, I have to run a script that sets the following:
```
LD_LIBRARY_PATH =/opt/qt515/lib/x86_64-linux-gnu:/opt/qt515/lib
PKG_CONFIG_PATH=/opt/qt515/lib/pkgconfig
```
My QT Base directory is `/opt/qt515`

**Comment by deathchimera** [comment]
I have both QT 5.15 & QT 6 installed. This looks like the problem, I just need to figure out how fix it on my system. I'll update when I get it working, or run across more issues. Here's my build script for reference.

[template.txt](https://github.com/user-attachments/files/17270597/template.txt)

**Comment by deathchimera** [comment]
Did a bunch of testing and still couldn't figure out how to resolve it. Maybe it's just a skill diff, but here's what I tried:

- Purging everything QT6 (+restart)
- Scouring Makefiles for anything pointing to QT6 (found none)
- Compiling different versions of T2D (v1.4.5 & up are the only ones with this issue)
- Attempting to point directly to QT 5.15 with LD_LIBRARY_PATH (need to consult with Void Linux users on this)

While compiling for v1.4, I noticed these warnings popping up that point to 'tthreadmessage.h' again. It looks like some part of QMutex is deprecated, and might somehow be causing errors when building for v1.4.5 and up. Can't know for sure what the true issue is without more Linux testers though.

![change](https://github.com/user-attachments/assets/ec92e868-44d6-4447-a746-f083ed9aed5c)

**Comment by manongjohn** [comment]
@deathchimera 

> * Compiling different versions of T2D (v1.4.5 & up are the only ones with this issue)

Just to confirm, you can build 1.4.4 without issue but not 1.4.5?

**Comment by deathchimera** [comment]
@xrheihwh 
@manongjohn
Yea, 1.4.4 built fine. I'll send a log file of 1.4.5 trying to compile in a bit; I'll make use of the VERBOSE option this time. I'm not too sure what the difference between each of our systems is, but I'll look into it within the next few days; see if I can't find new hints. 

Void is pretty similar to Arch in how it handles build automation, so I mostly look [here](https://aur.archlinux.org/packages/tahoma2d-git) when builds are breaking. Haven't seen any relevant activity to this issue there though. I'm gonna manually build T2D as well, see if I haven't missed anything.

**Comment by manongjohn** [comment]
🤔 If you built 1.4.4 successfully, it must be something added in 1.4.5 thats causing a problem.

I reviewed the fixes applied for 1.4.5 and i cant see what would be doing that.

One way to figure it out is to clone the v
1.4.5 branch and back out 1 commit at a time until you can compile successfully.

**Comment by deathchimera** [comment]
I can do that, shouldn't be too bad since the error is less than two percent into compilation. Not sure how to see how many commits are in-between 1.4.5 and 1.4.4, but if there's a lot I can probably skip commits by a set amount to find it quicker

**Comment by manongjohn** [comment]
There are 30 commits

**Comment by deathchimera** [comment]
Sry, had to deal with dependency issues since it's my first time building without my script. Starting to go through the commits now.

**Comment by deathchimera** [comment]
Compiling from origin/v1.4.5 works. _Branch_ v1.4.5 doesn't include [this](https://github.com/tahoma2d/tahoma2d/commit/fad7726e15d3d69262c076cd038a7de55b6099c7) commit, and compiling from _tag_ v1.4.5 nets the original QMutex error because it _does_ include this commit. I can't compile from the release page because whatever commit lineage it uses, includes that commit. My opinion will probably change tomorrow, but that's what it seems like for now.  

I had to wrestle a lot with git, but maybe you guys can make something of this explanation, even if it's not the right one. I'll test some more if that commit doesn't lead to anything new; I'm sure there are holes in my understanding of all this.

**Comment by manongjohn** [comment]
@deathchimera Please send me your entire build log, or look in more detail at your recent because I think you are failing for something else now.

I just looked in more detail at the snippet of the 2 build logs you shared. In the initial log you opened the ticket with you definitely errored because QMutex::Recursive was not a member of QMutex.  It was removed in Qt6.  However, I just noticed in the 2nd log, it switched to a `warning`, which is expected since QMutex::Recursive is deprecated but not yet removed in Qt5.15 and should still compile.

Do you know which version of Qt5 you have installed?  Expecting Qt5.15.2.

**Comment by deathchimera** [comment]
The initial snippet is from a failed 1.4.5 build, and the second is from a successful 1.4 build; here are the full logs below. I have QT 5.15.11 installed.

v1.4.5 failed build
[t2d-145.log](https://github.com/user-attachments/files/17350909/t2d-145.log)

v1.4.4 successful build
[t2d-144.log](https://github.com/user-attachments/files/17350910/t2d-144.log)

**Comment by manongjohn** [comment]
Sadly, nothing jumps out comparing the logs.  Somehow the T2D build is still going after, what I assume is your Qt6 library instead of Qt5.

You said you tried doing this prior to building T2D?
   `export LD_LIBRARY_PATH=xxxx:$LD_LIBRARY_PATH`
where xxxx is your qt5 library path

I noticed in your template.txt script, you have it commented out.

I reviewed the commit you suspect might be causing it.  I don't see anything in there that would cause a difference from a Linux build point of view, certainly not something what would cause it to try to use Qt6.  The only real difference from a cmake point of view where linux might have been impacted was I moved to compiling with C++17 and disabled anything that was deprecated before Qt5.15.2.

Can try removing this line from the `toonz/sourcces/CMakeLists.txt` file:
   `-DQT_DISABLE_DEPRECATED_BEFORE=0x050F02`
And see if that helps any?

**Comment by deathchimera** [comment]
Setting the LD_LIBRARY_PATH variable didn't work for me, but removing that line from CMakeLists appears to have fixed it. It's now giving me warnings instead of errors like in the 1.4.4 build. I'm letting it compile completely, will edit this with a log file. Tested a bit from the latest commit, and looks like a success too.

**Comment by manongjohn** [comment]
Glad it works. Odd though. I wonder why all my builds still work with that setting but your qt5 library doesnt.

**Comment by deathchimera** [comment]
Close as not planned since only @MegaMcVolt faced the same issue? I could leave it open for a bit to see if Mega can fix it by doing the same, but not sure what's causing this hiccup either.

**Comment by manongjohn** [comment]
I think it can be closed for now.

@MegaMcVolt Please try the suggestion at the bottom of this comment https://github.com/tahoma2d/tahoma2d/issues/1600#issuecomment-2408657568 and see if it helps your issue also.  Let us know here or in a different ticket if its a different issue.

**Comment by MegaMcVolt** [comment]
Hi all!
Below are the results of my compilations and runs of Tahoma2D:
| Version | Patch | Build | Run |
|---------|-------|-------|-----|
|  1.4.4  |  nothing  | successful | crash [Crash-20241013-000325.log](https://github.com/user-attachments/files/17351570/Crash-20241013-000325.log) |
|  1.4.5  | [#1600 (comment)](https://github.com/tahoma2d/tahoma2d/issues/1600#issuecomment-2408657568) | successful | crash [Crash-20241013-002618.log](https://github.com/user-attachments/files/17351585/Crash-20241013-002618.log) |
| 1.5 | [#1600 (comment)](https://github.com/tahoma2d/tahoma2d/issues/1600#issuecomment-2408657568) | successful | crash [Crash-20241013-005953.log](https://github.com/user-attachments/files/17351639/Crash-20241013-005953.log) |

I have thoughts/guesses why the app is crashing, but I need time to check them...

**Comment by Tekkitslime** [comment]
I hit this same error in the master branch and im confused, because `-DQT_DISABLE_DEPRECATED_BEFORE=0x050F02` means to disable all functions that are deprecated in and before version `5.16.2`, which doesnt even exist. i think that option sholdve been `0x050E02` at the very least! changing it to that seems to works as expected.

**Comment by ericwomer** [comment]
> I hit this same error in the master branch and im confused, because `-DQT_DISABLE_DEPRECATED_BEFORE=0x050F02` means to disable all functions that are deprecated in and before version `5.16.2`, which doesnt even exist. i think that option sholdve been `0x050E02` at the very least! changing it to that seems to works as expected.

Why is this issue closed if the incorrect variable is still in the CMakeLists.txt file? Does it fix a Mac issue if having the incorrect value maybe?

**Comment by aleislost** [comment]
I'm facing this issue still in an Arch-based linux distro. I can't build from source. I tried gemini to give me help but nope, nothing works
