### ISSUE TITLE
Tahoma2d crash

### ISSUE THREAD

**Issue by vicoviquitica** [tahoma2d/tahoma2d#1621]
### Bug Description

Tahoma 2d suddenly crashes and ''Crash Reason: EXCEPTION_ACCESS_VIOLATION'' appears on my screen, what makes me lost part of my work, im forced to close it, help pls

### Relevant logs/screenshots

![Captura de pantalla (74)](https://github.com/user-attachments/assets/4ce6689e-d9a0-4651-8c9e-61f1b02d663e)

### Software Version

1.4.5

### Software Version Information

Build ABI: x86_64-little_endian-llp64

### Operating System

Windows 10 (10.0)

### Graphics Card

GPU Vendor: Intel GPU Model: Intel(R) UHD Graphics GPU Version: 4.6.0 - Build 27.20.100.9664

### Drawing Tablet

xppen deco pro medium

**Comment by manongjohn** [comment]
Please attach the crash log (and crash dump).
You can find it in `C:\Users\yourlogin\AppData\Local\Tahoma2D\Tahoma2D\crash`

**Comment by vicoviquitica** [comment]
> Please attach the crash log (and crash dump). You can find it in `C:\Users\yourlogin\AppData\Local\Tahoma2D\Tahoma2D\crash`
Here I attached the crash log and crash dump, hopefully, you can help me solve this

[Crash-20241019-181912.dmp](https://github.com/user-attachments/files/17447831/Crash-20241019-181912.dmp)
[Crash-20241019-181912.log](https://github.com/user-attachments/files/17447832/Crash-20241019-181912.log)
