### ISSUE TITLE
Repeting issue of crashing

### ISSUE THREAD

**Issue by Phrog-02** [tahoma2d/tahoma2d#1627]
### Bug Description

My tahoma keeps crashing and ive restared, upgraded to 1.5 and i dont what to do because im doing a school animation project. 
the crash reason is always: Crash Reason: EXCEPTION_ACCESS_VIOLATION

### Relevant logs/screenshots

Tahoma2D 1.5 (Beta)  (Build Oct  5 2024)

Report Date: 2024-10-23 12:06:04
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 12

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics
GPU Version: 4.6.0 - Build 31.0.101.5388

Crash File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20241023-120604.log
Mini Dump File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20241023-120604.dmp

Application Dir: C:/Users/USER/Desktop/LBS 2023/Year 2/Animation 1 & 2/Tahoma/Tahoma2D-1.5/Tahoma2D
Stuff Dir: C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tahomastuff

Project Name: lownScare4
Scene Name: HP_ClownScare8
Project Path: C:\Users\USER\Documents\lownScare4\tahomaproject.xml
Scene Path: C:\Users\USER\Documents\lownScare4\scenes\HP_ClownScare8.tnz

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fff2fd07f7a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fff2fcae632] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff2fd3416e] <ntdll.dll>
  4> RasterBlurredBrush::getBoundFromPoints {bluredbrush.cpp:508} <tnztools.dll>
  5> FullColorEraserTool::leftButtonUp {fullcolorerasertool.cpp:749} <tnztools.dll>
  6> SceneViewer::onRelease {sceneviewerevents.cpp:1052} <Tahoma2D.exe>
  7> SceneViewer::tabletEvent {sceneviewerevents.cpp:350} <Tahoma2D.exe>
  8> QWidget::event [0x7ffed61d80f7] <Qt5Widgets.dll>
  9> SceneViewer::event {sceneviewerevents.cpp:1552} <Tahoma2D.exe>
 10> QApplicationPrivate::notify_helper [0x7ffed61b55c0] <Qt5Widgets.dll>
 11> QApplication::notify [0x7ffed61b3e73] <Qt5Widgets.dll>
 12> QCoreApplication::notifyInternal2 [0x7ffed572318a] <Qt5Core.dll>
 13> QDesktopWidget::workAreaResized [0x7ffed6201284] <Qt5Widgets.dll>
 14> QDesktopWidget::workAreaResized [0x7ffed61feb59] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x7ffed61b55c0] <Qt5Widgets.dll>
 16> QApplication::notify [0x7ffed61b4643] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x7ffed572318a] <Qt5Core.dll>
 18> QGuiApplicationPrivate::processTabletEvent [0x7ffed5b656b7] <Qt5Gui.dll>
 19> QWindowSystemInterface::sendWindowSystemEvents [0x7ffed5b4f030] <Qt5Gui.dll>
 20> QEventDispatcherWin32::processEvents [0x7ffed576bcfa] <Qt5Core.dll>
 21> qt_plugin_query_metadata [0x7ffed42728d9] <qwindows.dll>
 22> QEventLoop::exec [0x7ffed571f64c] <Qt5Core.dll>
 23> QCoreApplication::exec [0x7ffed5722164] <Qt5Core.dll>
 24> main {main.cpp:898} <Tahoma2D.exe>
 25> WinMain [0x7ff6cfa354f7] <Tahoma2D.exe>
 26> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 27> BaseThreadInitThunk [0x7fff2ebd257d] <KERNEL32.DLL>
 28> RtlUserThreadStart [0x7fff2fceaf08] <ntdll.dll>
==== End ====

==== Modules ====
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Tahoma2D.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\System32\USER32.dll
C:\windows\System32\win32u.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\gdi32full.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\ucrtbase.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5PrintSupport.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5SerialPort.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Xml.dll
C:\windows\System32\SHELL32.dll
C:\windows\System32\ole32.dll
C:\windows\System32\combase.dll
C:\windows\System32\RPCRT4.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\msvcrt.dll
C:\windows\System32\COMDLG32.dll
C:\windows\System32\SETUPAPI.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\freeglut.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\sechost.dll
C:\windows\System32\shcore.dll
C:\windows\System32\bcrypt.dll
C:\windows\System32\SHLWAPI.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\EDSDK.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\libgphoto2.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\libgphoto2_port.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\colorfx.dll
C:\windows\System32\WS2_32.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tnztools.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\image.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tnzstdfx.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Widgets.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tfarm.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Gui.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Core.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\toonzqt.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\sound.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\toonzlib.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\opencv_world451.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Script.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tnzext.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tnzbase.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\tnzcore.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Multimedia.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Network.dll
C:\windows\SYSTEM32\MPR.dll
C:\windows\SYSTEM32\GLU32.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\windows\System32\CRYPT32.dll
C:\windows\System32\OLEAUT32.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\MSVCP140.dll
C:\windows\SYSTEM32\MFPlat.DLL
C:\windows\SYSTEM32\MF.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\VCRUNTIME140.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\VCRUNTIME140_1.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\MSVCP140_1.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\windows\SYSTEM32\WINMM.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\windows\SYSTEM32\VERSION.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\glew32.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\libmypaint-1-4-0.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\windows\SYSTEM32\d3d11.dll
C:\windows\SYSTEM32\dxgi.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\windows\SYSTEM32\USERENV.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\Qt5Svg.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\windows\SYSTEM32\DNSAPI.dll
C:\windows\SYSTEM32\cfgmgr32.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\libjson-c-2.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\libintl-8.dll
C:\windows\SYSTEM32\dxcore.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\libiconv-2.dll
C:\windows\SYSTEM32\NETUTILS.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\CONCRT140.dll
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\SYSTEM32\profapi.dll
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\UMPDC.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\styles\qwindowsvistastyle.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\SYSTEM32\drvstore.dll
C:\windows\SYSTEM32\directxdatabasehelper.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\SYSTEM32\CoreMessaging.dll
C:\windows\SYSTEM32\CoreUIComponents.dll
C:\windows\system32\Oleacc.dll
C:\windows\system32\UIAutomationCore.dll
C:\windows\System32\clbcatq.dll
C:\windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_04afa34408d130c9\igxelpicd64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_04afa34408d130c9\igdml64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_04afa34408d130c9\igdgmm64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_04afa34408d130c9\igc64.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\twinapi.appcore.dll
C:\windows\system32\ApplicationTargetedFeatureDatabase.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\WINMMBASE.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qgif.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qicns.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qico.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qjpeg.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qsvg.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qtga.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qtiff.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qwbmp.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\imageformats\qwebp.dll
C:\windows\SYSTEM32\CRYPTSP.dll
C:\windows\system32\rsaenh.dll
C:\windows\SYSTEM32\DEVOBJ.dll
C:\windows\System32\WINTRUST.dll
C:\windows\SYSTEM32\MSASN1.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\bearer\qgenericbearer.dll
C:\windows\SYSTEM32\dhcpcsvc6.DLL
C:\windows\SYSTEM32\dhcpcsvc.DLL
C:\windows\System32\netprofm.dll
C:\windows\System32\npmproxy.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\mediaservice\dsengine.dll
C:\windows\SYSTEM32\dxva2.dll
C:\windows\SYSTEM32\EVR.dll
C:\Windows\System32\devenum.dll
C:\windows\SYSTEM32\ntmarta.dll
C:\windows\SYSTEM32\msdmo.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\EdsImage.dll
C:\Windows\System32\PortableDeviceApi.dll
C:\Users\USER\Desktop\LBS 2023\Year 2\Animation 1 & 2\Tahoma\Tahoma2D-1.5\Tahoma2D\audio\qtaudio_windows.dll
C:\windows\SYSTEM32\MMDevAPI.DLL
C:\windows\SYSTEM32\wdmaud.drv
C:\windows\SYSTEM32\ksuser.dll
C:\windows\SYSTEM32\AVRT.dll
C:\windows\SYSTEM32\AUDIOSES.DLL
C:\windows\SYSTEM32\msacm32.drv
C:\windows\SYSTEM32\midimap.dll
C:\windows\SYSTEM32\resourcepolicyclient.dll
C:\windows\SYSTEM32\PROPSYS.dll
C:\windows\SYSTEM32\LINKINFO.dll
C:\windows\system32\wintab32.dll
C:\windows\SYSTEM32\Wacom_Tablet.dll
C:\windows\system32\winhttp.dll
C:\windows\SYSTEM32\SspiCli.dll
C:\windows\system32\napinsp.dll
C:\windows\system32\pnrpnsp.dll
C:\windows\System32\mswsock.dll
C:\windows\System32\winrnr.dll
C:\windows\system32\wshbth.dll
C:\windows\system32\nlansp_c.dll
C:\Windows\System32\rasadhlp.dll
C:\windows\System32\fwpuclnt.dll
C:\windows\system32\Ninput.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3672_none_2713b9d173822955\comctl32.DLL
C:\windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\windows\SYSTEM32\policymanager.dll
C:\windows\SYSTEM32\msvcp110_win.dll
==== End ====

### Software Version

1.4.5

### Operating System

windows 11 i think?

### Graphics Card

dont know

### Drawing Tablet

wacom (one by wacom CTL - 472)  or somthing

**Comment by manongjohn** [comment]
I believe this issue will be fixed by PR #1624 which will hit the nightly in a few days and will only be available in v1.5

**Comment by Phrog-02** [comment]
thanks i guess re install it, but repeteting crash began from v1.4 and still crashed in v.1.5

**Comment by manongjohn** [comment]
> thanks i guess re install it, but repeteting crash began from v1.4 and still crashed in v.1.5

It's not in v1.5, yet, so downloading and reinstalling the beta wont help.  Its still waiting to be merged into the nightly.  You can try the artifact for the PR i mentioned to see if it helps until it officially merges into the nightly.

**Comment by Phrog-02** [comment]
also what is "nightly"

**Comment by manongjohn** [comment]
> also what is "nightly"

A nightly is a build that has all the changes that are going to be in the next release.  It can be updated with stuff in as little as an hour apart, days, weeks or event months depending on what is being developed and when it's considered ready for the next release.

Some people use it to try stuff coming up in the next release or it contains a fix that is troubling them so much they need it and can't wait for the next release or fix release.  However, a nightly can have more bugs as a result of new development and can sometimes be a little more unstable.
