### ISSUE TITLE
drawing crash while working 

### ISSUE THREAD

**Issue by PSthebuilder** [tahoma2d/tahoma2d#1641]
### Bug Description

While i was drawing the software crash 

### Steps to reproduce

was erasing and adjusting brush size the few frames were done 

### Relevant logs/screenshots

Tahoma2D 1.4  (Build Dec  1 2023)

Report Date: 2024-11-12 21:41:26
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 (10.0)
OS Kernel: 10.0.19045
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: GeForce GTX 1650/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 457.51

Crash File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20241112-214126.log
Mini Dump File: C:\Users\USER\AppData\Local\Tahoma2D\Tahoma2D\crash\Crash-20241112-214126.dmp

Application Dir: D:/tahoma/Tahoma2D/Tahoma2D
Stuff Dir: D:\tahoma\Tahoma2D\tahomastuff

Project Name: Run cycle
Scene Name: PRac
Project Path: C:\Users\USER\Documents\Run cycle\tahomaproject.xml
Scene Path: C:\Users\USER\Documents\Run cycle\scenes\PRac.tnz

==== Backtrace ====
  1> RtlDeleteAce [0x7ffcceda9b4c] <ntdll.dll>
  2> RtlRaiseException [0x7ffcced82376] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffccedd13ce] <ntdll.dll>
  4> RasterBlurredBrush::getBoundFromPoints {bluredbrush.cpp:508} <tnztools.dll>
  5> FullColorEraserTool::leftButtonUp {fullcolorerasertool.cpp:704} <tnztools.dll>
  6> SceneViewer::onRelease {sceneviewerevents.cpp:1042} <Tahoma2D.exe>
  7> SceneViewer::tabletEvent {sceneviewerevents.cpp:350} <Tahoma2D.exe>
  8> QWidget::event [0x614a877b] <Qt5Widgets.dll>
  9> SceneViewer::event {sceneviewerevents.cpp:1501} <Tahoma2D.exe>
 10> QApplicationPrivate::notify_helper [0x61486be4] <Qt5Widgets.dll>
 11> QApplication::notify [0x614852a8] <Qt5Widgets.dll>
 12> QCoreApplication::notifyInternal2 [0x610ed4aa] <Qt5Core.dll>
 13> QDesktopWidget::workAreaResized [0x614d1ffc] <Qt5Widgets.dll>
 14> QDesktopWidget::workAreaResized [0x614cfc96] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x61486be4] <Qt5Widgets.dll>
 16> QApplication::notify [0x61485aa3] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x610ed4aa] <Qt5Core.dll>
 18> QGuiApplicationPrivate::processTabletEvent [0x7ffc4343bc62] <Qt5Gui.dll>
 19> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc4341f9a0] <Qt5Gui.dll>
 20> QEventDispatcherWin32::processEvents [0x61132ac9] <Qt5Core.dll>
 21> CallWindowProcW [0x7ffcce7fef5c] <USER32.dll>
 22> DispatchMessageW [0x7ffcce7fe684] <USER32.dll>
 23> QEventDispatcherWin32::processEvents [0x61132300] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ffc4e330339] <qwindows.dll>
 25> QEventLoop::exec [0x610e9c0c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x610ec4b4] <Qt5Core.dll>
 27> main {main.cpp:895} <Tahoma2D.exe>
 28> WinMain [0x7ff6c4f26c64] <Tahoma2D.exe>
 29> __scrt_common_main_seh {exe_common.inl:288} <Tahoma2D.exe>
 30> BaseThreadInitThunk [0x7ffccd647374] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7ffcced7cc91] <ntdll.dll>
==== End ====

==== Modules ====
D:\tahoma\Tahoma2D\Tahoma2D\Tahoma2D.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\bcrypt.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5SerialPort.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5PrintSupport.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Xml.dll
D:\tahoma\Tahoma2D\Tahoma2D\freeglut.dll
D:\tahoma\Tahoma2D\Tahoma2D\libgphoto2.dll
D:\tahoma\Tahoma2D\Tahoma2D\libgphoto2_port.dll
D:\tahoma\Tahoma2D\Tahoma2D\colorfx.dll
D:\tahoma\Tahoma2D\Tahoma2D\image.dll
D:\tahoma\Tahoma2D\Tahoma2D\tfarm.dll
C:\Windows\System32\WS2_32.dll
D:\tahoma\Tahoma2D\Tahoma2D\tnztools.dll
D:\tahoma\Tahoma2D\Tahoma2D\EDSDK.dll
D:\tahoma\Tahoma2D\Tahoma2D\tnzstdfx.dll
D:\tahoma\Tahoma2D\Tahoma2D\sound.dll
D:\tahoma\Tahoma2D\Tahoma2D\opencv_world451.dll
C:\Windows\System32\OLEAUT32.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Script.dll
D:\tahoma\Tahoma2D\Tahoma2D\toonzqt.dll
D:\tahoma\Tahoma2D\Tahoma2D\tnzext.dll
D:\tahoma\Tahoma2D\Tahoma2D\tnzbase.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5OpenGL.dll
D:\tahoma\Tahoma2D\Tahoma2D\toonzlib.dll
D:\tahoma\Tahoma2D\Tahoma2D\tnzcore.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Multimedia.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Network.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\VCRUNTIME140.dll
C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Widgets.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Core.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.4355_none_792ecafd2442822f\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
D:\tahoma\Tahoma2D\Tahoma2D\libmypaint-1-4-0.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Gui.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\CONCRT140.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\tahoma\Tahoma2D\Tahoma2D\libintl-8.dll
D:\tahoma\Tahoma2D\Tahoma2D\Qt5Svg.dll
C:\Windows\SYSTEM32\winmmbase.dll
D:\tahoma\Tahoma2D\Tahoma2D\libjson-c-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
D:\tahoma\Tahoma2D\Tahoma2D\glew32.dll
D:\tahoma\Tahoma2D\Tahoma2D\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
D:\tahoma\Tahoma2D\Tahoma2D\platforms\qwindows.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
D:\tahoma\Tahoma2D\Tahoma2D\iconengines\qsvgicon.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\nvoglv64.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\d3d11.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\dxgi.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qgif.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qicns.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qico.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qjpeg.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qsvg.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qtga.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qtiff.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qwbmp.dll
D:\tahoma\Tahoma2D\Tahoma2D\imageformats\qwebp.dll
D:\tahoma\Tahoma2D\Tahoma2D\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
D:\tahoma\Tahoma2D\Tahoma2D\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
D:\tahoma\Tahoma2D\Tahoma2D\mediaservice\dsengine.dll
C:\Windows\SYSTEM32\dxva2.dll
C:\Windows\SYSTEM32\EVR.dll
C:\Windows\System32\devenum.dll
C:\Windows\SYSTEM32\msdmo.dll
D:\tahoma\Tahoma2D\Tahoma2D\EdsImage.dll
C:\Windows\System32\PortableDeviceApi.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\winrnr.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.4355_none_60b8b9eb71f62e16\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\policymanager.dll
C:\Windows\SYSTEM32\msvcp110_win.dll
C:\Windows\system32\Ninput.dll
C:\Windows\SYSTEM32\edputil.dll
==== End ====

### Software Version

1.4.5

### Operating System

windows 10 

### Graphics Card

gtx 1650

### Drawing Tablet

huion h264

**Comment by manongjohn** [comment]
I believe this particular issue will be fixed by #1624 which is included in the next release, v1.5.  Feel free to try the v1.5beta to see if it still happens often for you.
