### ISSUE TITLE
Allow any project to be selected on export scene

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#203]
**Is your feature request related to a problem? Please describe**
The Export Scene window only gives access to the sandbox and documents directories for project locations.
<img width="250" alt="Screen Shot 2020-09-24 at 8 41 47 AM" src="https://user-images.githubusercontent.com/21159116/94150669-70fd4100-fe47-11ea-95c4-e0c67338712c.png">

**Describe the solution you'd like**
For new and existing projects, we should be able to choose any location - like we can elsewhere in Tahoma.

Also, thanks so much for all the amazing improvements that are continually added to Tahoma!

**Comment by jeremybullock** [comment]
This has been (mostly) implemented.  You can now choose from the recent projects or export to the default project location.
