### ISSUE TITLE
Status bar messages not all visible on smaller screens

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#375]
**Describe the bug**
Status bar messages can get cut off if the screen is not large enough - ie. if the screen is only 15in.

**To Reproduce**
1. Open Tahoma2D on a device with a smaller screen - ie. almost any laptop
2. Add a vector level
3. Switch to the brush tool

**Expected behavior**
If the message isn't completely visible, there should be a way to reveal the end of the message. There are several possible approaches:

-  There could be a scrolling behavior when hovering over the status bar (like in Blender)
- There could be a button to show more
- The space between each message could shrink on smaller screen sizes
- There could be shorter messages - ie. "Control: Straight Lines at Angles" takes up less space than "Control - Straight Lines Snapped to Angles".

**Screenshots**
This shows the right side of the status bar on a 15in laptop:
<img width="605" alt="Screen Shot 2020-10-18 at 9 30 06 AM" src="https://user-images.githubusercontent.com/21159116/96368887-9585c980-1124-11eb-8df8-7fc24f7187dc.png">
What does shift+ctrl do? You can't tell from the status bar here.

**Device Information:**
 - OS: macOS
 - Tahoma2D Version: Beta

**Comment by DarrenTAnims** [comment]
It's not really the size of the screen, but the resolution. I use Tahoma on a laptop, but my resolution is quite high, so it fits for me. I'm currently running at: 1920x1080. What resolution are you running at? And can you make it larger?

**Comment by artisteacher** [comment]
On my 15in, the default resolution (which I prefer), is the equivalent of 1680x1050. The highest resolution (1920x1200) makes the entire status bar visible on my 15in screen. That doesn't help on my 13in where the resolution can't get that high.  Either way, I shouldn't need to change my resolution to see more for one panel in Tahoma.

**Comment by manongjohn** [comment]
Would a Hover-Hint displaying the full text be a good compromise to fix this?  

Additionally if the text doesn't fit the space provided, we should also edit the visible text to show there is more ("..."), which would hopefully help show there might be more in case it happens to get cut off on a space.

**Comment by artisteacher** [comment]
Sounds good to me.

**Comment by artisteacher** [comment]
The hover hint is working great.
