### ISSUE TITLE
Inbetween text squashed in level strip

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#460]
**Screenshots**
<img width="22" alt="Screen Shot 2020-11-04 at 9 19 34 PM" src="https://user-images.githubusercontent.com/21159116/98189757-a20b6f80-1ee3-11eb-9de0-33f314ae7d26.png">

**Device Information:**
 - OS: macOS
 - Tahoma2D Version: 1.1

**Comment by jeremybullock** [comment]
This seems like it's a mac thing.

**Comment by artisteacher** [comment]
Figures! It seems completely fine in the horizontal orientation.
