### ISSUE TITLE
Black drawings hard to see with level strip active

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#496]
**Describe the bug**
With the Dark and Darker themes, if the level strip is active, it is hard to see black drawings.

**To Reproduce**
1. Use the the Dark or Darker themes
2. Make a vector drawing with just black lines
3. Select the drawing in the level strip panel

**Expected behavior**
I'd expect such a standard linework color to be more visible.

**Screenshots**
Dark theme:
<img width="585" alt="Screen Shot 2020-11-13 at 9 05 22 AM" src="https://user-images.githubusercontent.com/21159116/99080538-6e89ae80-258f-11eb-8d50-e073be2d5470.png">
Darker theme:
<img width="494" alt="Screen Shot 2020-11-13 at 8 40 09 AM" src="https://user-images.githubusercontent.com/21159116/99080141-de4b6980-258e-11eb-877b-53b777eb2cdc.png">

**Device Information:**
 - OS: macOS
 - Tahoma2D Version: 1.1

**Comment by artisteacher** [comment]
Personally I wouldn't want to change any theme viewer background colors for the scene itself. However, it would be helpful if the viewer background lightened to something like #544e4e, just when vector levels are active in the level strip.
<img width="468" alt="Screen Shot 2020-11-13 at 9 15 54 AM" src="https://user-images.githubusercontent.com/21159116/99081477-ddb3d280-2590-11eb-8c99-81f98b538884.png">

**Comment by jeremybullock** [comment]
It's interesting you bring this up.  I was thinking about this recently too.  I originally changed the viewer background for both aesthetic reasons and for stop motion work.  But I agree that it can interfere with drawing - either on vector levels or raster levels larger than the camera/canvas.

I'll take a look and see what can be done.

**Comment by jeremybullock** [comment]
What do you think about lightening the viewer background color for the medium and dark theme.  Leaving darker as a good theme for stop motion?

**Comment by artisteacher** [comment]
That's not a bad solution, though I like the dark background in general. Also, some animators might go back and forth between drawn & stop motion techniques. It would be nice to be able to change the viewer background value on the fly and as needed, without needing to get into preferences.

My first thought was that something like the camera preview color buttons could be great - except for viewer background ( whether preview is on or not). That way you could quickly change the background, depending on your workflow/need. So when doing stopmotion, you could leave the theme default or change to black. If you switch to drawing black vector linework - or anything that extends past the camera, you could switch to a light color.
<img width="218" alt="Screen Shot 2020-11-17 at 8 40 59 PM" src="https://user-images.githubusercontent.com/21159116/99471916-92454f80-2915-11eb-9aec-69bfdb2f589c.png">
Actually, are these buttons actually used for the camera by anyone? They could be co-opted...

Or what about a value slider?

**Comment by artisteacher** [comment]
On a semi-related issue, in the dark themes, the active color stop arrow is hard to see - especially when the color is particularly light.
<img width="194" alt="Screen Shot 2021-08-28 at 9 06 21 PM" src="https://user-images.githubusercontent.com/21159116/131234873-7ce6addb-fb92-42f7-8420-ad42925e864e.png">

**Comment by artisteacher** [comment]
Fixed in #865
