### ISSUE TITLE
Issue with the Tahoma documentation site

### ISSUE THREAD

**Issue by wolfscorcher** [tahoma2d/tahoma2d#531]
I never used or know how to use GitHub, and I don't know where else to report this, so here I am.

**Describe the bug**
The Tahoma Documentation won't load. It worked fine yesterday.

**Device Information:**
I tried on both Safari and Firefox, so I guess that's not a problem with the browsers.
<img width="653" alt="Screen Shot 2020-11-23 at 10 27 07" src="https://user-images.githubusercontent.com/74888385/99927417-e4ec9480-2d77-11eb-8f52-67cf096680a1.png">

**Comment by artisteacher** [comment]
Weird - it wasn't doing that earlier today.

**Comment by jeremybullock** [comment]
The documentation is down for now.  We moved Tahoma to a new organization here on GitHub, and the docs are being transferred to manongjohn's account on read the docs.

**Comment by wolfscorcher** [comment]
Alright then, thank you for the explanation! I'll close this discussion then.

**Comment by manongjohn** [comment]
Tahoma2d manual is back on-line.

**Comment by wolfscorcher** [comment]
Alright, thanks! :)
