### ISSUE TITLE
Unable to set "+space" shortcut for tools

### ISSUE THREAD

**Issue by JIAJE** [tahoma2d/tahoma2d#538]
I don't speak English, here is the translation
When I want to set the shortcut "Shift+space" for the Zoom Tool, it doesn't work. But setting "Shift+Any key" does work. And the default shortcut for the Zoom Tool in "OpenToonz 1.4" is "Shift+space".

**Comment by artisteacher** [comment]
This was actually a deliberate choice, since space is hardcoded for several actions in Tahoma. #373

Space = panning
Space+shift = zoom
Space+ctrl = rotate

Shift+space already zooms in the Viewer. It doesn't need to be set as a shortcut for the Zoom Tool.

**Comment by manongjohn** [comment]
Closing. No bug identified.
