### ISSUE TITLE
Corrupted? scene keeps crashing after using plastic tool

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#551]
**Describe the bug**
A scene got corrupted after using the plastic tool. Deleting the images from the project doesn't help, & the images/mesh can be loaded into a new scene without issue. The problem seems to come from the scene file itself.

**To Reproduce**
List steps to reproduce the behavior.
1. Open the scene or export the scene = instant crash

**Project:**
[Plastic crashes.zip](https://github.com/tahoma2d/tahoma2d/files/5765714/Plastic.crashes.zip)
**Crash Report:**
[plastic crash.txt](https://github.com/tahoma2d/tahoma2d/files/5765715/plastic.crash.txt)

**Device Information:**
 - OS: macOS Catalina
 - Tahoma2D Version: 1.1
 - GPU: Radeon Pro Vega 20

**Comment by manongjohn** [comment]
I found the problem in the scene file.  it appears, Col2's pegbar information had Col3 as a parent, but for some reason Col3 is missing.  I'm guessing Col3 is probably the mesh column which somehow failed to write out correctly.

Do you recall what actions with the Plastic tool might have caused this?  Did it crash right away or you didn't notice until it saved and you tried to open it later?

**Comment by artisteacher** [comment]
I’m not sure, it was a student from last semester that had the problem.

**Comment by artisteacher** [comment]
Maybe related to this?
https://github.com/opentoonz/opentoonz/issues/3709

**Comment by manongjohn** [comment]
Thanks.  That very well could be the issue. Maybe when the mesh layer was deleted it, for some odd reason it didn't reparent the layer back to the Table like it should have.

I will play around and see if I can duplicate it.

**Comment by manongjohn** [comment]
I was able to recreate it.  It appears to be a general issue when deleting the parent of a layer from the xsheet. The child layer doesn't reparent automatically back to the Table like it does if you deleted the parent in the Schematic.

Now to fix it....

**Comment by artisteacher** [comment]
I'm glad you found the problem!
