### ISSUE TITLE
Crash when setting keys on a plastic mesh with no skeleton

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#552]
**Describe the bug**
Adding keyframes from the Viewer's context menu (when a mesh level is active), with the Plastic Tool's animate mode active (but no skeleton is actually created) causes a crash. While part of this is user error, there should be a warning notification that there's no skeleton instead of a crash.

**To Reproduce**
List steps to reproduce the behavior.
1. Select a level and switch to the plastic tool
2. Create a mesh
3. Switch to the plastic tool's animate mode (without building a skeleton)
4. With the mesh layer still active, right-click in the Viewer & choose "Global Rest Key" (or etc.)

**Crash Report**
[plastic_no_skeleton.txt](https://github.com/tahoma2d/tahoma2d/files/5783428/plastic_no_skeleton.txt)

**Device Information:**
 - OS: macOS
 - Tahoma2D Version: 1.1

**Comment by manongjohn** [comment]
Reviewing the logic surrounding the plastic tool's `Set Global Key` and `Set Global Rest Key`, I'm not sure why these options are not hidden like `Set Key` and `Set Rest Key` when a skeleton hasn't been created.  These options are useless without a skeleton.

I will hide these options in the context menu when no skeleton has been created.
