### ISSUE TITLE
Questions regarding Krita import 

### ISSUE THREAD

**Issue by azerzzer** [tahoma2d/tahoma2d#555]
**Is your feature request related to a problem? Please describe**
No, this is not regarding a problem, rather, it is a question about the ways I can import drawings from Krita into Tahoma

**Describe the solution you'd like**
It would be awesome if I got a few solutions on how I could use Krita to draw for my animations in tahoma without having to export the file every single time and then having to import it manually in Tahoma. Or is this the only way to use krita to draw for tahoma?

**Comment by artisteacher** [comment]
You could save as a PSD from Krita. Then load the PSD in Tahoma (don't import, choose "Load"). Then any saved changes to the drawings in the PSD from Krita will display in Tahoma upon reloading the scene or reloading the PSD (Level -> Reload).

**Comment by DarrenTAnims** [comment]
You can either select a single frame and copy it, with Ctrl+A, Ctrl+C. Then in Tahoma, press Ctrl+V.

Or you can export your animation, as you say, but when you import the images into Tahoma, choose the Load option. Then you can go back and edit them in Krita, export them and just reload your scene in Tahoma and it'll look at the new exported images.

**Comment by azerzzer** [comment]
> You can either select a single frame and copy it, with Ctrl+A, Ctrl+C. Then in Tahoma, press Ctrl+V.
> 
> Or you can export your animation, as you say, but when you import the images into Tahoma, choose the Load option. Then you can go back and edit them in Krita, export them and just reload your scene in Tahoma and it'll look at the new exported images.

Ok, thank you, I will do this from now on.

**Comment by azerzzer** [comment]
> You could save as a PSD from Krita. Then load the PSD in Tahoma (don't import, choose "Load"). Then any saved changes to the drawings in the PSD from Krita will display in Tahoma upon reloading the scene or reloading the PSD (Level -> Reload).

Would this work with any file type that krita can export and tahoma can load, like .png, .jpg, etc.

**Comment by manongjohn** [comment]
To go from Krita to Tahoma, I would recommend exporting as PNG.  Loading PNG files into Tahoma will allow you to further edit them in Tahoma if you need to.

Using PSD is fine as well, however PSD files cannot be further modified in Tahoma if you need to fix something.

If you have multiple files that are supposed to be in 1 level in Tahoma, make sure you name them appropriately as a set of sequenced files after extracting. (i.e.  abc_0001.png, abc_0002.png, etc)

As for Loading vs Importing.  If you plan on Loading, then likely files you exported will be outside the Project folders so you will need to remember to include them if you need share your Project files with someone.  Additionally, deleting/moving the files outside the Project folder could break your scene.  

Alternatively, you can do your initial Krita work, Import them into Tahoma, then if you need to edit them again, you can do that in Tahoma (if you used PNG), or you can open the files in the Project folder (under "extras") with Krita and edit them.  Doing this method, if you add a new file to the level (naming it appropriately for the sequence), the next time you open Tahoma, that image should load automatically into the Level Strip for that level.  Then you can drag/drop from there to the Timeline where you need it.
