### ISSUE TITLE
Could you in the future add the option to paint with custom tilesets or patterns?

### ISSUE THREAD

**Issue by NothingAnimated** [tahoma2d/tahoma2d#558]
In the future could you add a way to be able to draw/paint with tileset and the brush would snap to the grid (for example if the tiles were 128 x 128 you could make the grid 128 x 128 so that it would snap and be consistant. This could possibly work like the pallet system. Thank you for reading.

**Comment by artisteacher** [comment]
You can already outline/fill with custom patterns on vector and smart raster levels already:

Go to the texture tab of the style editor, press:
<img width="53" alt="Screen Shot 2021-01-13 at 8 23 31 PM" src="https://user-images.githubusercontent.com/21159116/104532010-447b5980-55dd-11eb-88d7-a584303fb36e.png">
Then switch to the settings tab to load the texture and adjust the settings:
<img width="261" alt="Screen Shot 2021-01-13 at 8 23 43 PM" src="https://user-images.githubusercontent.com/21159116/104532044-5826c000-55dd-11eb-98d9-c6c0288423d9.png">

Currently, to see the texture in a smart raster level, you need to turn preview on. Also, right now the settings only impact the smart raster levels. So changing scale or etc. is ignored on vector levels. I'd love to see a more consistent behavior for textures in the future.

**Comment by jeremybullock** [comment]
If you are talking about tilesets in the same way that game engines use tile sets, I think that is a feature better left for game engines.
