### ISSUE TITLE
Is there any way to convert an image sequence into a gif?

### ISSUE THREAD

**Issue by Cherryfrin** [tahoma2d/tahoma2d#596]
I imported a folder with 100+ images which were meant to be put together but all the images were on one frame.Is there any way to bring them all together without doing it the hard way?

**Comment by artisteacher** [comment]
You mean into an image sequence? Image sequences are recognized by Tahoma as formatted like: name.001.png or name_0001.tif - where the period or underscore separates the name from the number. 

If your sequence is sequential but not using the correct format - ie. name001.png, name002.png & etc., you can use the Browser room to easily rename the sequence properly:

1. Find the image folder in the Browser room
2. Right-click on the first image in your sequence and choose "rename"
<img width="298" alt="Screen Shot 2021-02-22 at 9 39 55 AM" src="https://user-images.githubusercontent.com/21159116/108723209-00d81180-74f2-11eb-87c0-478ba21f40ce.png">
3. Give the image a name but no number - ie "newname" NOT "new name.001"
<img width="242" alt="Screen Shot 2021-02-22 at 9 40 56 AM" src="https://user-images.githubusercontent.com/21159116/108723369-2c5afc00-74f2-11eb-83d9-3b8672333e59.png">
4. Click on rename
5. Right-click on the new level (notice it will say the number of frames) and choose "Load"
<img width="313" alt="Screen Shot 2021-02-22 at 9 41 16 AM" src="https://user-images.githubusercontent.com/21159116/108723548-63311200-74f2-11eb-9389-c240827b5a21.png">

**Comment by Cherryfrin** [comment]
Ah okay, thanks
