### ISSUE TITLE
Add modifier keys as shortcuts

### ISSUE THREAD

**Issue by AnglesSol** [tahoma2d/tahoma2d#601]
It's a minor detail, but it would be nice to put shift+ space, or ctrl + space (for example) as a shortcut.

With opentoonz you can do this, even exporting the shortcuts from OT to Tahoma won´t make them work.

**Comment by artisteacher** [comment]
With #588, we'll be able to assign shift+space & etc. again. You should see it in the next release.

**Comment by artisteacher** [comment]
Already complete, recommend closing.

**Comment by artisteacher** [comment]
@manongjohn - this can be closed.
