### ISSUE TITLE
Ffmpeg crash on open from Actions Artifact

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#617]
**Describe the bug**
While I was looking into a different crash, I noticed that Ffmpeg is generating 3 crash reports when opening Tahoma2D artifact builds. If you try to use FFmpeg (ie. do a fast render to mp4), there's a notification saying FFmpeg is not found - even though the executables seem to be in the app.

**To Reproduce**
List steps to reproduce the behavior.
1. Download a recent macOS artifact build
2. Open the build
3. Look in Console for the crash reports

**Screenshots, short videos or logs**
If applicable, add screenshots or links to short videos to help explain your problem or provide logs or dmp files if it's a crash.

<img width="1282" alt="Screen Shot 2021-03-15 at 6 01 54 PM" src="https://user-images.githubusercontent.com/21159116/111228567-ce827700-85ba-11eb-8cd0-196a22b48644.png">
<img width="539" alt="Screen Shot 2021-03-15 at 6 21 58 PM" src="https://user-images.githubusercontent.com/21159116/111228919-66806080-85bb-11eb-9a8e-7efb8e6e70eb.png">

**Device Information:**
 - OS: macOS Big Sur
 - Tahoma2D Version: Tested on action artifacts for #610 and #615

**Comment by manongjohn** [comment]
Seems the macOS Action builds of ffmpeg is referencing some shared libraries.  Not sure why it's doing that since these are supposed to be static builds.

My release builds shouldn't have this problem. I'll have to investigate what is causing that in the Action builds.
