### ISSUE TITLE
Problem on painting

### ISSUE THREAD

**Issue by Jorge2d** [tahoma2d/tahoma2d#622]
I'm having a problem with brushes when I paint with two or more brushes/colors in the same level, a brush dont paint over other brush. It dont happen if a create a new level and paint over the brush of the other level. Like this:
![Brushes issue](https://user-images.githubusercontent.com/78383132/111884488-b470dc00-89a0-11eb-94c7-df7ab0b64777.jpg)
Win10 64
Zotac Geforce Graphic Card
Tahoma2d 1.1
obs.: Sorry if a made mistakes in english

**Comment by artisteacher** [comment]
Are you using smart raster levels (green)? The way the smart raster levels are color mapped does cause some interesting effects if you try to paint over existing strokes with the brush tool. They are not really intended for that workflow. Instead, if you want to paint over existing strokes, use the smart raster paint tool when painting over.  

Though I think you may end up preferring how standard raster levels (blue) behave. There's no mapping so you'll see more expected interactions when brushing over. There are also some great blending brushes that only work on raster levels.

**Comment by Jorge2d** [comment]
Thanks!!! It was my problem, I was using smart raster level.
