### ISSUE TITLE
Xsheet & Timeline resize on Tahoma2D start.

### ISSUE THREAD

**Issue by melieconiek** [tahoma2d/tahoma2d#626]
**Describe the bug**
The xsheet and timeline bins resize when Tahoma2D starts. This only affects the layout that is open on startup.

**To Reproduce**
List steps to reproduce the behavior.
1. Set the xsheet or timeline to a certain size.
2. Restart Tahoma2D.

**Device Information:**
 - OS: Windows
 - Tahoma2D Version: https://github.com/tahoma2d/tahoma2d/commit/0d7afaf98a9c2407425128866304ef15e89ecf41

**Comment by artisteacher** [comment]
I'm not seeing this on macOS.

**Comment by artisteacher** [comment]
Are you using the actions artifact?

**Comment by manongjohn** [comment]
Might be just a Windows thing? I see it with my local builds.
