### ISSUE TITLE
Bug in the 1.2 Alpha version related to the Level strip panel 

### ISSUE THREAD

**Issue by JPUser1** [tahoma2d/tahoma2d#647]
Its causes by clicking in the level strip when no level is loaded.

https://user-images.githubusercontent.com/74626650/113613982-1ff8b180-960f-11eb-8ff7-41b205fd3230.mp4

  I am using Windows 10.

**Comment by beeheemooth** [comment]
Confirm this also in windows 8.1

**Comment by artisteacher** [comment]
Confirm on macOS too.
