### ISSUE TITLE
Import Preferences doesn't properly import rooms

### ISSUE THREAD

**Issue by RattusaurusRex** [tahoma2d/tahoma2d#648]
**Describe the bug**
Custom user rooms don't load into Tahoma after using Import Preferences and restarting.  While importing, a pop-up appears asking to reload or restore default rooms (I clicked Yes and No and neither resulted in rooms being loaded).  

![image](https://user-images.githubusercontent.com/60277069/113632511-23486900-9620-11eb-8dd8-d21a0b752262.png)

After restarting, the only rooms are Tahoma's default rooms.  
![image](https://user-images.githubusercontent.com/60277069/113632879-c600e780-9620-11eb-897e-0f1316095be9.png)

If I look in \layouts\Default, it seems to have imported some of my rooms.  Rooms 7 to 11 are mine.  1 - 6 are Tahoma default rooms instead of my rooms.
![image](https://user-images.githubusercontent.com/60277069/113632830-b2ee1780-9620-11eb-8158-490f876a45c8.png)

Layouts.txt doesn't get updated with the new rooms.
![image](https://user-images.githubusercontent.com/60277069/113633028-0fe9cd80-9621-11eb-9369-f5450d5b7efe.png)

Screenshot of what my rooms should look like:
![image](https://user-images.githubusercontent.com/60277069/113633175-53dcd280-9621-11eb-9855-968ceac06a13.png)

**Device Information:**
Tahoma2D Version: Tahoma2D 1.2 alpha
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: Wacom Cintiq Pro 24

**Comment by artisteacher** [comment]
Confirm on macOS.
