### ISSUE TITLE
Missing icons in drop-down lists "Cap" and "Join".

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#652]
![Screen_0193](https://user-images.githubusercontent.com/25724133/113743969-ea39f280-970c-11eb-863d-49a932eb3a7a.jpg)

**Device Information:**
 - OS: [e.g. Windows] Windows 8.1
 - Tahoma2D Version: Tahoma2D 1.2 - Alpha 1

**Comment by beeheemooth** [comment]
The case when the fix appeared earlier than the issue.  :)

**Comment by manongjohn** [comment]
Leaving it open for now. I'll link my PR to it so it closes it when it merges.

This way if someone else comes on to report it, they will see it was already reported
