### ISSUE TITLE
'Project Settings' dialog is missing

### ISSUE THREAD

**Issue by ReturnMinusOne** [tahoma2d/tahoma2d#657]
**Describe the bug**
The 'Project Settings' dialog does not seem to be present in Tahoma2D. I'm not sure why this is, especially since the [user manual](https://tahoma2d.readthedocs.io/en/latest/managing_projects.html#project-default-folders) mentions it explicitly:

> The labels of the default folders you can find in the project settings (i.e. +drawings, +extras, etc.) can be used as aliases in Tahoma.

It's clear the manual is outdated, with the page title referring to Tahoma 1.0.0, but even that version does not have the dialog.

**To Reproduce**
Select File > Project Management.

In OpenToonz there is an option called Project Settings; this button is missing in all versions of Tahoma2D, both for the sandbox and for new projects.

**Screenshots, short videos or logs**
![Tahoma-no_project_settings](https://user-images.githubusercontent.com/35435781/114045734-40ff1380-9856-11eb-8ec6-2f9bf4346b6a.jpg)

**Device Information:**
 - OS: Windows 10 (64-bit)
 - Tahoma2D Version: 1.0 / 1.1 / 1.2 (alpha)
 - GPU: AMD (Gigabyte) Radeon RX 590
 - GPU Driver Version: 20.10.27.05-201027a-360165C-RadeonProEnterprise

**Comment by manongjohn** [comment]
The Project Settings dialog was intentionally removed in 1.0 though the Tahoma on-line document was never updated to reflect this.

I believe that dialog was taken out to simplify Project maintenance.  Is there something or some reason in particular you need that dialog box?

With 1.2, you can set the Default Project Path in the `Preferences -> General tab`.

**Comment by artisteacher** [comment]
Personally, I always found OT more reliable if I didn't mess with the default project settings. If things stay as they are, is there a need to keep the "Save Default Settings" command?

If the project settings are added back, please keep them out of the startup window and new project dialog. It used to be so much more confusing for new users.

I'll update the documentation, if the project settings will stay as is.

**Comment by ReturnMinusOne** [comment]
Thank you for the responses. Folder structure is something that could be expected to vary greatly depending on the goal and scale of a project, as well as the user's habits with other software.

In this instance, I'd much prefer to group all of a scene's assets in a folder named after that scene, in the same directory.

For example, say I have three scenes:

**MyProject/scenes/scene01.tnz**
**MyProject/scenes/scene02.tnz**
**MyProject/scenes/scene03.tnz**

I'd like to have the 'inputs', 'drawings', 'extras' and 'outputs' folders for each scene inside a directory with the same name: 

![FolderStructure](https://user-images.githubusercontent.com/35435781/114059501-6db92800-9862-11eb-83bf-b66cccbab313.jpg)

(As a side note, I would like it better if folders were only created as needed.)

I realise how much emphasis Tahoma places on streamlining the interface, but I feel that the freedom lost by removing the dialog entirely is a rather heavy cost for the reduction in complexity.

It could use a name change though, like 'Default folders', and rather than the three "append $scenepath" checkboxes, I think one or two simple sentences explaining what $scenepath is, its current value, and how it can be added to folder paths would be easier to understand.

**Comment by artisteacher** [comment]
> (As a side note, I would like it better if folders were only created as needed.)

As in, the extras folder is only created upon making/importing the first raster image or etc.?

If project setting are enabled again, rethinking how the dialog is organized and terms used is probably a good idea.

**Comment by manongjohn** [comment]
The bad part about the original Project Settings dialog was that if you changed the dropdown, it changed your current project.  I think that might have caused issues with users who didn't realize that was happening. I think maybe that's why it was changed to `Switch Project`?

As for the settings?  I don't particularly care for the settings either, but I can see how they can be useful for managing your assets/scenes, especially for more advanced users and larger projects.

How about this.  
1. Replace `New Project` with `Choose Project` or `Select Project` where you can chose to create a new project or select an existing one, similar to the Export Current Scene Dialog.
2. Restore `Project Settings` however it will only show the current project's settings.

**Comment by manongjohn** [comment]
Actually, what I should maybe do is replace `Switch Project` to a submenu item and they can just select it from there instead of popping up another dialog box.

**Comment by artisteacher** [comment]
Sure. In the project settings, instead of "append scenepath to drawing" & etc, what about something like "Use(make?) folders for each scene" and then underneath have checkboxes to enable that for drawing, extras & etc.?

**Comment by ReturnMinusOne** [comment]
Speaking for myself, I'm fine with the way Tahoma handles creating and switching projects. I might consider turning the 'Project Management' submenu into a 'Project' button in the top menu bar, but I'm not too concerned with it.

I also wouldn't mind having the Project Settings without the Project field, since changing the default folders for multiple projects, in sequence, sounds like a _very_ specific use case that might be better handled by a file editor going through a set of '_otprj.xml' files. Or maybe the field could just be renamed to "Current Project".

> what about something like "Use(make?) folders for each scene" and then underneath have checkboxes to enable that for drawing, extras & etc.?

The wording is certainly less cryptic than that of OpenToonz, but it still seems somewhat restrictive: would it put the asset folders inside dedicated scene folders like my example above? Or would it be the other way around, as with the "append $scenepath" checkboxes in OT? Either way, some users will be left out.

I'm still leaning towards a simple description of $scenepath and its value, but I agree that it probably shouldn't appear in the 'New Project' window. In the long term, I could see a new category in the Preferences where users could set default behaviour for the folder structure.

**Comment by DarrenTAnims** [comment]
I wouldn't mind a simplified version of those checkboxes, but only 1 checkbox to cover all 3 sub folders. Something like:

- [X] Save scene files separately
- [ ] Save scene files in sub-folders

**Comment by artisteacher** [comment]
I wouldn't use the term "scene files" because that might make people think we mean the .tnz files.

- [ ] Save assets separate from the scene
- [ ] Save assets in scene sub-folders

**Comment by manongjohn** [comment]
How about this: I would have 2 groups in the dialog `Main Folders` (scenes, outputs, palettes, scripts) and `Asset Folders` (drawings, inputs, extras). The asset folders group would have a checkbox: `Separate assets into scene sub-folders`.

I mentioned I wasn't planning on putting in any significant feature changes during Alpha testing, but I think restoring the Project Settings might be worthwhile.  Most of what has been discussed will mostly be restoring and reconfiguring the dialogs. I think I can get this done before Beta testing begins where only bug fixes would be allowed.

Future enhancement: I do like the idea of a scene subdirectory that @ReturnMinusOne proposed, but would need to maintain backwards compatibility with prior Tahoma versions and to some degree with OT.

**Comment by manongjohn** [comment]
I wasn't planning on making an elaborate GUI, at least I don't consider these changes as elaborate.

- `New Project...` is staying as is, I think.
- Creating a `Open Recent Project` sub-menu list for switching projects
- Restoring `Project Settings...` with a few minor GUI tweeks.

Reading the documentation on $scenepath gives me a headache. lol.  Technically you can use $scenepath however/whenever you want. I think the 3 options were added to make separating assets by scene simple as clicking on/off without having to type/copy/paste it yourself.  Always room for typos or misusing.

I would rather simplify this for general users who won't necessarily care about `$scenepath` and give an easy option to separate assets by scene with 1 checkbox.  Can still add a note about `$scenepath` and consult documentation on how to use it if we want.

**Comment by artisteacher** [comment]
I definitely prefer the 1 checkbox route myself.

**Comment by ReturnMinusOne** [comment]
Given my particular use case, I'm glad that Project Settings may be returning. That said, I hope it doesn't cause problems in development.

Earlier I created a new project and tested the $scenepath variable in tahomaproject.xml:
```
...

<folder name="drawings" path="scenes/$scenepath/drawings"/>
<folder name="scenes" path="scenes"/>

...

```
I didn't expect this to work, but to my surprise, it appears to have given me the result I was looking for: level files stored in scene-specific folders.

So even while the Project Settings dialog remains unavailable, thankfully there's still a way to customise the folder hierarchy.

**Comment by DarrenTAnims** [comment]
I use 2 main options here.
1. Tick the 3 boxes and have a sceneName folder in each of the 3 subfolders (Drawings, Extras & Inputs):
2. Manually add the $scenepath into the paths of the new project dialog and have the drawings and extras folders inside the scenename folder.

These are the options I think would be useful for simple project management. But I feel like it might be better to wait for 1.3 to do this. You've enough to do for the 1.2 release. But that's your choice, of course :-)

Screenshots:

1. Tick the 3 boxes and have a sceneName folder in each of the 3 subfolders (Drawings, Extras & Inputs):

![image](https://user-images.githubusercontent.com/28575907/114179270-ac201700-9936-11eb-8cae-f0c543d4fe22.png)

![image](https://user-images.githubusercontent.com/28575907/114178745-079dd500-9936-11eb-9269-90dd2d62b4b8.png)

2. Manually add the $scenepath into the paths of the new project dialog and have the drawings and extras folders inside the scenename folder.

![image](https://user-images.githubusercontent.com/28575907/114179343-c0641400-9936-11eb-8611-3b3b0d36fe20.png)

![image](https://user-images.githubusercontent.com/28575907/114178989-58adc900-9936-11eb-8762-ec7d395e3228.png)
