### ISSUE TITLE
Some shortcuts not working when canvas is maximised (fixed in OpenToonz)

### ISSUE THREAD

**Issue by ReturnMinusOne** [tahoma2d/tahoma2d#684]
**Describe the bug**

When the 'Toggle Maximize Panel' key is pressed and all the panels and bars are hidden, some shortcuts cease to work, namely:

- changing the brush's minimum or maximum size (or Size value for MyPaint brushes)
- changing the mode of a tool, for example the Selection tool (Freehand, Polyline, etc.) and the Eraser (Rectangular, Freehand, etc.)
	
I noticed this a few days ago, but thankfully, it was just fixed in the [May 1st nightly build](https://github.com/opentoonz/opentoonz/commit/5e814d9f345aec619903cd6f16aa5335fb999eb2) of OpenToonz. I hope the fix can make its way to Tahoma before the final 1.2 release.
	
**To Reproduce**

1. Set a shortcut to change the size of the brush, or change the mode of a given tool.
2. Maximise the canvas.
3. Press the relevant shortcut.

**Expected behavior**

I would expect these shortcuts to remain active regardless of what panels are visible.

**Device Information:**

 - OS: Windows 10 64-bit
 - Tahoma2D Version: 1.2 Beta (2021-04-25 nightly release)
 - GPU: AMD (Gigabyte) Radeon RX 590
 - GPU Driver Version: 20.10.27.05-201027a-360165C-RadeonProEnterprise

**Comment by artisteacher** [comment]
It looks like this is all set now.

**Comment by ReturnMinusOne** [comment]
Agreed, the problem is solved; my thanks to the OpenToonz and Tahoma teams.
