### ISSUE TITLE
Cannot change shortcuts on MacOS

### ISSUE THREAD

**Issue by kalebye2** [tahoma2d/tahoma2d#695]
When trying to open the "Configure Shortcuts" menu Tahoma crashes.

List steps to reproduce the behavior.
1. Click on "File->Configure Shortcuts..."

[Tahoma2D_2021-05-11-101439_iMac-Pro-de-Matheus.txt](https://github.com/tahoma2d/tahoma2d/files/6459371/Tahoma2D_2021-05-11-101439_iMac-Pro-de-Matheus.txt)

**Device Information:**
 - OS: MacOS Catalina 10.15.7
 - Tahoma2D Version: 1.2
 - GPU: Radeon Pro Vega 56 8GB
 - GPU Driver Version: Unknown

**Comment by artisteacher** [comment]
I'm getting the crash too, on both Catalina and Mojave with 1.2 and the latest nightly build. I have a build from April  25th that doesn't have this issue.

**Comment by manongjohn** [comment]
I believe it is related to the OT patch #3930 (Fix Shortcut Input).  Will look into it.

Curious if OT has the same issue.

**Comment by manongjohn** [comment]
@kalebye2 I've fixed the issue and updated the release.  Please download v1.2 again as it will have the fix in it.

Let me now if you are still having problems.  Thanks.

**Comment by kalebye2** [comment]
@manongjohn Thanks, it worked.
