### ISSUE TITLE
Fix the bug with the program update

### ISSUE THREAD

**Issue by NyakaMeow** [tahoma2d/tahoma2d#702]
I went into the program and a window popped up asking me to update. I go to the website, and for some reason it opens the OpenToonz website. What

**Comment by manongjohn** [comment]
Unfortunately, that's a bug with the 1.1 release. I disabled the version update check for 1.2 as I didnt think it was working, though i recently discovered the check works under Linux.

What OS are you on?

**Comment by NyakaMeow** [comment]
> Unfortunately, that's a bug with the 1.1 release. I disabled the version update check for 1.2 as I didnt think it was working, though i recently discovered the check works under Linux.
> 
> What OS are you on?

Windows 10

**Comment by manongjohn** [comment]
> Windows 10

Interesting. It didn't work on my system when I was testing it. I got errors when it was trying to verify. I wonder why it works on yours.  

I just confirmed it worked on macOS, so I'm going to have to restore the version check for 1.3 now. 😄
