### ISSUE TITLE
Add Min & Max value sliders for the smart raster paint tool

### ISSUE THREAD

**Issue by DarrenTAnims** [tahoma2d/tahoma2d#708]
To help paint areas on smart raster levels I sometimes use the smart raster paint tool, but it's hard to find the right size with only have 1 size slider. So I often revert to using the standard brush with a range set, so I can paint into the corners of my shapes with a lighter touch and fill larger areas by pressing more firmly.
It'd be a huge help to have 2 sliders for the smart raster paint tool to be able to choose a min and max size, so I could use this brush without having to change the size regularly.

**Comment by artisteacher** [comment]
Yes!
