### ISSUE TITLE
Smart paint brush crashes in finger tool mode

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#711]
**Describe the bug**
Ctrl-Dragging with the smart raster brush (Finger tool mode) and then releasing the Ctrl key while still dragging leads to a crash.

**To Reproduce**
List steps to reproduce the behavior.
1. Create a smart raster level and draw a line with the brush
2. Switch to the smart paint brush and use ctrl+drag (cmd+drag on Mac) to enable finger tool capability
3. Release ctrl (cmd on Mac) while still dragging

**Screenshots, short videos or logs**
[finger_crash.txt](https://github.com/tahoma2d/tahoma2d/files/6633350/finger_crash.txt)

**Device Information:**
 - OS: [macOS 10.15.6]
 - Tahoma2D Version: [e.g. Nightly (June 9th 2021)]
 - GPU: [Radeon Pro Vega 20]

**Comment by beeheemooth** [comment]
Confirmed also in Windows 8.1 The crash happens without pre-drawing the lines (1), you can simply use the tool in the manner described above. Interestingly, this happens more often with a mouse and less often with a stylus.
