### ISSUE TITLE
Recording audio in Windows 10 result in 8Khz quality

### ISSUE THREAD

**Issue by justburner** [tahoma2d/tahoma2d#730]
**Describe the bug**
Recording audio in Windows 10 result in 8Khz quality WAV file which can't be used directly on rhubarb lip sync.
Windows 7 and MacOS is not affected (Verified by me and Artisteacher).
Additionally on my system the devices list have duplicated devices.

**To Reproduce**
1. Panels > Record Audio, pick record device and hit the Record button.
2. "Save and Insert" to save your file into the project.
3. Poor audio quality is very noticeable on playback but is possible to check the exact recording quality on windows file properties or an external editor.

**Screenshots, short videos or logs**
Snapshot of the duplicated devices:
![alt text](https://cdn.discordapp.com/attachments/760345858545156137/839956203751735296/RepeatedTwiceDevices.png)

**Device Information:**
 - OS: Windows 10
 - Tahoma2D Version: 1.2
 - GPU: N/A
 - GPU Driver Version: N/A

**Comment by artisteacher** [comment]
It looks like before #634, which includes https://github.com/opentoonz/opentoonz/pull/3825, Windows and Linux both were set to specifically record with 

> audioSettings.setSampleRate(44100);

However in OT, that caused a crash on Windows 10.

**Comment by artisteacher** [comment]
I believe this was fixed as part of #848, so it should be able to closed.
