### ISSUE TITLE
Macos Mojave Tahoma2d quit after splash screen

### ISSUE THREAD

**Issue by kucharskikucharski** [tahoma2d/tahoma2d#731]
**Describe the bug**
Macos Mojave Tahoma2d quit after splash screen

**To Reproduce**
1.Turn on Tahoma2D.app
2.Splash screen appears
3.Error window appears

![image](https://user-images.githubusercontent.com/45039631/126202221-17ee37ca-febb-4da6-9d4b-c190462ec56a.png)

**Device Information:**
Tahoma2D 64 bits Portable
Model: iMac13,2, Intel Core i7, 3,4 GHz, 32 GB
Graphics: NVIDIA GeForce GTX 680MX

Crash window says:
[Tahoma_Crash_Report.txt](https://github.com/tahoma2d/tahoma2d/files/6846975/Tahoma_Crash_Report.txt)

**Comment by artisteacher** [comment]
It runs for me on Mojave. 

Are you trying to run Tahoma directly from the DMG? Make sure you move Tahoma2D.app from the DMG somewhere onto the computer - ie. Applications, Desktop or etc.

**Comment by artisteacher** [comment]
Also in the future, if you could attach crash reports in a .txt file, that would be helpful. Cuts down on the scrolling!

**Comment by kucharskikucharski** [comment]
Thank you for advices. I'll try it and I'll edit my report with txt file
tomorrow
Cheers!

pon., 19 lip 2021, 21:26 użytkownik artisteacher ***@***.***>
napisał:

**Comment by kucharskikucharski** [comment]
Moving app. file to Aplications helped me and tahoma woking properly
Thank you!
