### ISSUE TITLE
Glitches regarding  PR #733

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#735]
1. When using the Fill Tool (Frame Range) with the Refer Visible option, the first frame is filled as the last (if filled from the first frame to the last).
![ezgif-2-204fa31db869](https://user-images.githubusercontent.com/25724133/127567260-969aae43-7642-46db-b477-d5c2998eabb2.gif)

2. Moving a row of frames of a fill level along the timeline affects the fill process.
![ezgif-2-1689f6a9f04d](https://user-images.githubusercontent.com/25724133/127567273-b2aef273-22c9-44d4-a102-732a17ea7c2c.gif)

3. Applying the feature does not update the Preview window 
![ezgif-2-631d79a71a9f](https://user-images.githubusercontent.com/25724133/127566947-d7ccc9f8-128c-450e-8c76-5b5a3fd0756d.gif)

**Device Information:**
 - OS:  Windows 8.1
 - Tahoma2D Version: latest artifact

**Comment by manongjohn** [comment]
Closing.  I've pushed fixes to PR #733
