### ISSUE TITLE
extend camera's white BG to re-sized levels 

### ISSUE THREAD

**Issue by IgnacioFer** [tahoma2d/tahoma2d#745]
When creating a level larger than the camera size, the level that now extends beyond the camera size has no background, and if you're using a dark theme, like the default 'Dark' (which I love, btw), and a dark ink, it is very hard to see what you're doing.

It would be better if the area of the level extending beyond the camera also had a colour bg like the camera. Maybe the same colour or slightly greyed out to tell the difference.

I would include a screenshot of what I mean but unfortunately T2D crashes when I draw on an level larger than the camera (#742 )

**Comment by IgnacioFer** [comment]
So this turned out my not knowing my way around TD2. To avoid this it is enough to created a BG painted with a solid colour - so not really an issue

**Comment by artisteacher** [comment]
As far as the dark theme contrast issue goes, there's a related issue #496. 

You should be able to draw outside of the camera without a crash. If you could share crash data and information about the operating system, that would be great.

**Comment by artisteacher** [comment]
Sorry - just noticed you already opened a crash report.

**Comment by IgnacioFer** [comment]
The crash was related to the Hardness settings of the brush - see #742

**Comment by IgnacioFer** [comment]
Btw, I just realized you can customize the colour of the Viewer BG in Preferences \> Colors, which is great if you are drawing outside your current camera size with a dark theme. Great feature! and better than what I suggested....
