### ISSUE TITLE
'ignore timing' toggle for navigating x-sheet from drawing to drawing

### ISSUE THREAD

**Issue by IgnacioFer** [tahoma2d/tahoma2d#771]
I'm guessing there has to be an obvious way to do this already, but I'm not finding it...

To be able to navigate the x-sheet (or timeline) with the keyboard arrow keys moving to the next/previous drawing instead of the next/previous cell (i.e. to skip all the cells that do not have a number on them).

This is essential for hand-drawn animation, as you're likely to time your rough keys poses and breakdowns and then 'flip' between using the arrow keys to tighten the drawing and put them on model.

When it's just a few drawings, or to flip between key drawings and avoid the breakdowns inbetween, I set a key on each of those drawings and use the 'next/previous key' function (assigned to  ,  and  .  ) to flip between them, but this is time-consuming to set up and if you change the timing after assigning the keys, the keys of course don't move with the drawings. So in the end I end up retiming the column on 1s, but then you have to re-time it again (and again!) and it's a real pain if the characters are interacting with elements on other columns. 

Is there a way to flip between drawings while skipping the timing cells with the arrow keys (or other assigned keys)? If not, I'd suggest that both Caps Lock and a toggle on the x-sheet give the arrow keys this functionality (the toggle in order to have a visual indicator and in case you're using a controller where Caps Lock is not available)

**Comment by beeheemooth** [comment]
Look in Configure Shortcuts: Next Drawing, Previous Drawing are what you are asking about. Assign shortcuts to them. You can also jump from one key to another (if you have a key animation) with the Next Key, Previous Key commands, these are also useful things.

**Comment by IgnacioFer** [comment]
Thanks! That's it - I still get lost in Configure Shortcuts, can't find anything there unless I know the name.
It works great, the only thing is that the arrow keys don't seem to be assignable as shortcuts. Is there any way to make the arrow keys take on a difference function?
