### ISSUE TITLE
Nightly Build crashes on macOS

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#784]
**Describe the bug**
We started using T2D with my classes today and ran into several issues.
1. If Tahoma2D was installed on another account, it crashes on open due to missing the canon SDK (but opens fine on the original account)
<img width="878" alt="Screen Shot 2021-09-10 at 1 59 57 PM" src="https://user-images.githubusercontent.com/21159116/132898074-ae701692-c53e-4db1-a2a5-4b70faf82c97.png">

2. A crash that might have been related to clicking on the edge of the toolbar while in full screen
[brush-crash.txt](https://github.com/tahoma2d/tahoma2d/files/7145598/brush-crash.txt)

3. A crash that seemed to relate to filling
[fill-crash-2.txt](https://github.com/tahoma2d/tahoma2d/files/7145606/fill-crash-2.txt)

4. A mystery crash
[crash-2.txt](https://github.com/tahoma2d/tahoma2d/files/7145612/crash-2.txt)

**Device Information:**
 - OS: macOS Catalina
 - Tahoma2D Version: [e.g. Nightly (2021-09-05)]

**Comment by manongjohn** [comment]
The ESDK issue is a permissions issue. Not sure why it is completely closed off to the group/world.  I'll have to fix the build scripts to force the appropriate permissions on that folder.

To fix it manually in the meantime, please perform the following in Terminal

1. cd /Applications/Tahoma2D.app/Contents/Frameworks 
2. chmod -R 755 EDSDK.framework

**Comment by manongjohn** [comment]
Reviewing the crash logs and attempting to duplicate on my macOS VM (Catalina)...

2. It appears when the user was just entering the canvas (just hovering into it I think), it crashed trying to get the current style meaning something was wrong with the palette or getting to the palette.  Not enough information to determine why.  I did experiment with maximizing the window and trying to move and click in between the canvas and bordering panes (tool option bar, style editor, etc) but could not reproduce the crash.

3. As I mentioned in #733, there may be something that is causing a crash in fills but I have a hard time reproducing it.  In this particular case, the user was either drag-filling or perhaps using Rectangular mode and creating the fill box when it crashed. I did try a number of different things (normal drag-fill, rectangular fill, gap closing, etc)....I managed to crash 1x but I can't be certain what sequence of events caused it.  I couldn't repeat it despite redoing similar actions.

4. Crash appears to be caused outside of Tahoma2D.  How Tahoma2D might have played into that crash is unknown as all the libraries it shows in the logs were system libraries.  I've encountered similar crashes in the past, even with OT with no apparent cause and also hard to repeat.

How often are these crashes happening with the latest nightly? What version was being used prior to that?

**Comment by artisteacher** [comment]
Thanks  for looking into this so swiftly!

>  meaning something was wrong with the palette or getting to the palette.

I wonder if they had an incompatible style for the level type? This was our first day using T2D and there's always confusion about which styles are compatible with each level.

> there may be something that is causing a crash in fills but I have a hard time reproducing it

I'll keep experimenting on my end & see if I can figure out reproducible steps. The problem is there are so many settings...


The last version we were using was from the Spring, probably the 1.2 release, or something close to it. Crashes happened more often then I'd expected but it's hard to say how much yet - the kids don't always mention it.

**Comment by artisteacher** [comment]
I only had 1 animation class meeting today, but we turned on auto-save this time (to save every 7 minutes) & no one reported any crashes.

**Comment by artisteacher** [comment]
A student today had a fill crash again. They were trying to fill with a mypaint brush style on a smart raster level.

**Comment by artisteacher** [comment]
Of course, I can't get a crash doing that, so the style might not actually matter.

**Comment by artisteacher** [comment]
> First I put the horizontal and vertical grids on then the perspective grid then I drew lines then I started to fill in the spaces then it crashed
[Untitled.txt](https://github.com/tahoma2d/tahoma2d/files/7221514/Untitled.txt)

> Fill tool with perspective lines using opt+left click with some shift+left click and a perspective point.
[fill.txt](https://github.com/tahoma2d/tahoma2d/files/7221532/fill.txt)

This last one doesn't look like a fill crash and didn't come with any notes, but I thought I should pass it on:
[Untitled-2.txt](https://github.com/tahoma2d/tahoma2d/files/7221546/Untitled-2.txt)

Also had a student get a crash while typing with the font tool. Font size was the largest option & they typed as much as they could, as fast as they could 🤨

**Comment by artisteacher** [comment]
Most of the students seem to be using the normal mode of the fill tool. They are filling areas - not sure if the mode has been area or lines/areas.

This student was alternating back and forth between creating new colors/styles and filling.
[crashreport.txt](https://github.com/tahoma2d/tahoma2d/files/7228196/crashreport.txt)

> I believe the reason why it crashed is because I had a raster [style] selected with the color when filling in a space

It looked like the long grass raster style
[crash-924.txt](https://github.com/tahoma2d/tahoma2d/files/7228210/crash-924.txt)

And another one...
[crash-924-2.txt](https://github.com/tahoma2d/tahoma2d/files/7228225/crash-924-2.txt)

**Comment by artisteacher** [comment]
I had a similar crash today but I was helping a student use the "Merge TLV Levels" command. We clicked and dragged across the two layer headers in the Timeline to select both smart raster layers (each layer had 1 smart raster level). Then used the merge command from the Scene menu.
[merge-smart.txt](https://github.com/tahoma2d/tahoma2d/files/7253002/merge-smart.txt)

Could this be the same cause as the fill crash?

**Comment by manongjohn** [comment]
Looks to be a different issue.

**Comment by artisteacher** [comment]
The smart raster fill crash can still happen at random, but never seems to happen if you save all before using the fill tool.

**Comment by artisteacher** [comment]
Closing since the remaining issues aren't easily repeatable. Will open a new issue around filling, once there's a new crash report with the line numbers.
