### ISSUE TITLE
Antialiasing node

### ISSUE THREAD

**Issue by F-Burning** [tahoma2d/tahoma2d#788]
And here we go again 😂

I looked at the search engine and I have not seen that it has opened the topic before, so...

**Is your feature request related to a problem? Please describe**

In the anime post-production, an antialiasing node/fx is very important to smooth lines. This function already exists in Tahoma, but it's not a node, but an option in the level settings

![22](https://user-images.githubusercontent.com/74098734/133094666-6b1bc0db-c204-454c-b91c-b06a7a291a63.jpg)

The problem is that you only can use the antialiasing at the beginning of the process, and not when you need it, because when the line has no smoothness, you can use certain nodes to make interesting effects, but if the line is smooth from the beginning, you can't directly take advantage of the full potential of the nodes, so ideally it would be to be able to smooth them when you need it.

**Describe the solution you'd like**

An Antialiasing node as in other programs like After Effects to work this kind of production.

I have no idea of ​​programming, but I imagine that it could somehow copy the code already existing in the level settings and create a node with this information.

Thank you for reading this far!

**Comment by smudgebun** [comment]
@F-Burning so sorry to bother multiple years after, did this feature end up getting added? It's exactly what I need for my current workflow but I cant find where it is if added.
