### ISSUE TITLE
build error with '-Werror=return-type'

### ISSUE THREAD

**Issue by krop** [tahoma2d/tahoma2d#811]
Using the master branch. The build fails with '-Werror=return-type':

```
toonz/sources/toonz/graphwidget.cpp:318:7: error: control reaches end of non-void function [-Werror=return-type]
[  855s]   318 |     y *= 0.5;
[  855s]       |     ~~^~~~~~

```
The function doesn't return anything if `m_isEnlarged` is true.

**Comment by manongjohn** [comment]
I'll fix these, but I'm curious what you are building on/with.  These apparently aren't preventing builds from being created.

**Comment by manongjohn** [comment]
> Not returning anything in functions supposed to (or the opposite) is bad coding practice that can lead to unexpected issues. That's why our packaging macros have this build flag.

I agree. I usually make sure i have a stand alone return at the end even if i don't think it can ever get there, but somehow overlooked the latest ones.

Anyway, thanks for reporting it. The PR to fix this is available if you want to confirm it's fixed or wait a few days and it'll be merged.

Is this for a Snap/Flatpak?
