### ISSUE TITLE
failed transparancy gif

### ISSUE THREAD

**Issue by stickylabdev** [tahoma2d/tahoma2d#831]
![gaga](https://user-images.githubusercontent.com/13078369/138928694-5a287641-93cc-4180-8971-de617b571ed8.gif)

a streang brush appear

**Comment by artisteacher** [comment]
@manongjohn - I still get ghosting on gifs.

**Comment by manongjohn** [comment]
Have you tried connecting T2D to a different ffmpeg instead of the one it comes packaged with?

I wonder if its something with the way T2D's ffmpeg version is compiled.

**Comment by artisteacher** [comment]
Just tried the most up-to-date release of fmpeg/ffplay. It doesn't seem to have the ghosting so far, at least on the M1 mac. I'll double-check on some older macs, but it does look like this fixes the ghosting, dependent on the ffmpeg version.
