### ISSUE TITLE
saving interface 

### ISSUE THREAD

**Issue by Dixxi0509** [tahoma2d/tahoma2d#838]
when i download tahoma2d i would make the interface how i want it but when i close it. it just resets to the old way i have it how do i fix it [i hit ctrl s but it doesnt work]

**Comment by artisteacher** [comment]
How are you changing the interface? Unless there's a crash on close, changes to preferences and rooms should save.

**Comment by Dixxi0509** [comment]
Theres a lock on the right unlock it and you can change the workplace go
your liking

**Comment by Dixxi0509** [comment]
Im not sure i mean it does crashes because its like opentoonz it can be
random too it is annoying

**Comment by manongjohn** [comment]
What OS are you running on?

It does sound like it's having issues saving the layouts, though typically if you are having problems with that, then you are also likely having problems saving anything like preferences or stuff to the sandbox project.  That could be why it's also crashes.

If you are on Windows, one way to check if it's a permission issue is to run it in Administrator mode.  If that works fine with that, then the permissions on the `tahomastuff` folder  are not correct and are easily correctable.

Another thing to check is to make sure any Antivirus software you are running is not blocking T2D from writing stuff.
