### ISSUE TITLE
Tahoma2d.exe System Error

### ISSUE THREAD

**Issue by akacatu** [tahoma2d/tahoma2d#839]
**Describe the bug**
A message appears at my screen saying the coding could not continue because "Qt5SerialPort.dll" was not found and so the program would be installed again to solve  the issue, but it never does.
**To Reproduce**
List steps to reproduce the behavior.
1. try to open tahoma 2d
2.the message pops up
3.

**Screenshots, short videos or logs**
If applicable, add screenshots or links to short videos to help explain your problem or provide logs or dmp files if it's a crash.

**Device Information:**
 - OS: [e.g. Windows]
 - Tahoma2D Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by manongjohn** [comment]
After downloading, make sure you extract/uncompress the contents of the .zip file onto your machine.  Do not move anything out of the extracted Tahoma2D folder.  You can move the entire folder to where you want to run it from like the Desktop.  To run, enter the Tahoma2D folder and run the Tahoma2d.exe

**Comment by akacatu** [comment]
Thanks for the quick response! It feels kinda odd not having a faster way to access the software, but that seems to have solved mt problem, thanks a lot!

**Comment by manongjohn** [comment]
T2D is built as portables so you can even put it on a flashdrive and run from there if needed.

I normally put mine in C:\Program Files and then create shortcuts to it.
