### ISSUE TITLE
tahoma 2d appimage would not start

### ISSUE THREAD

**Issue by fadi123go** [tahoma2d/tahoma2d#844]
the output for trying to start through the terminal is:
`Illegal instruction (core dumped)`
my system is mageia 8
my processor is Celeron(R) Dual-Core CPU       T3000  @ 1.80GHz
my video card ‎is intel Mobile 4 Series Chipset Integrated Graphics Controller
I can run the latest opentoonz version easily, so I do not think it is a hardware issue. Perhaps it is a python or a compiling issue.

**Comment by artisteacher** [comment]
Did you try 1.2 or a nightly build?

**Comment by fadi123go** [comment]
I did and the same problem exists. I think it may be because of a numpy python dependency or tensorflow which does not exist for mageia.

**Comment by charliemartinez** [comment]
First of all, the file must have execute permissions. Example:

`chmod 775 filename.appimage
`
I have noticed that sometimes some applications do not start. You can try running this command first:

`sudo sudo sysctl kernel.unprivileged_userns_clone=1`

If it still doesn't work, you can try opening the appimage from the terminal, adding the following switch:

[--no-sandbox](url)

example:

[./namefile.appimage --no-sandbox](url)

If you still can't get the appimage to work, I'd like you to know that I made a deb package that should work for you, I clarify that I did it on my own and I'm not part of the development team so it's not an official package. Although I give my word that what is inside is the same program as it is distributed here:

[https://quirinux.ga/repo/pool/main/t/tahoma2d/tahoma2d_1.4_amd64.deb](https://quirinux.ga/repo/pool/main/t/tahoma2d/tahoma2d_1.4_amd64.deb)
