### ISSUE TITLE
adding text/fonts

### ISSUE THREAD

**Issue by Dixxi0509** [tahoma2d/tahoma2d#845]
question 

https://www.dafont.com/

I was really curious if you could add custom text? i wanna use dafont to add some

**Comment by artisteacher** [comment]
Any fonts you put in with your system fonts will load in T2D. There is no option to load fonts from other sources.

**Comment by Dixxi0509** [comment]
Oh ok how do i do that?

**Comment by artisteacher** [comment]
For macOS, usually `Macintosh HD -> Library -> Fonts` or `Username -> Library -> Fonts`. 

I don't have a pc, so I'm not sure for Windows or Linux.

**Comment by Dixxi0509** [comment]
I have like a font download software (I wanna try adding a glitch like font
or a undertale font but I would have to download it is there a easier
alternative to so that without using a different software

**Comment by artisteacher** [comment]
Again, as long as you add the font with the system fonts, you can use it in T2D. If the font is from a reputable source and you are getting it legally, I don't know why you would need a special program to download it.

**Comment by Dixxi0509** [comment]
I recently figure out how to get fonts i would download them from a
software thrn extract them from a folder install the font and close
Tahoma2d then open it again to see the font there

**Comment by artisteacher** [comment]
Fantastic! Sounds like this can be closed then.

**Comment by Dixxi0509** [comment]
Oh ok thanks for letting me know
