### ISSUE TITLE
Adding scene as task segfaults Tahoma

### ISSUE THREAD

**Issue by animationista** [tahoma2d/tahoma2d#850]
In browser adding a (any) scene as a render task immediately crashes Tahoma with a segfault. Both in 1.2 and 1.1.

MXlinux 19.4, 6bit.

System info:
[code]
System:    Host: <filter> Kernel: 5.10.0-5mx-amd64 x86_64 bits: 64 compiler: N/A 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.4_ahs_x64 patito feo March 31  2021 base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Laptop System: PC Specialist product: P7xxDM3_DM3-G v: N/A serial: <filter> 
           Chassis: No Enclosure type: 10 serial: <filter> 
           Mobo: Clevo model: P7xxDM3_DM3-G serial: <filter> UEFI: American Megatrends 
           v: 1.06.11 date: 07/27/2017 
CPU:       Topology: Quad Core model: Intel Core i7-7700K bits: 64 type: MT MCP arch: Kaby Lake 
           family: 6 model-id: 9E (158) stepping: 9 microcode: EA L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 67200 
           Speed: 1140 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 1201 2: 1200 3: 1202 
           4: 1200 5: 1200 6: 1200 7: 1200 8: 1201 
Graphics:  Device-1: NVIDIA GP104BM [GeForce GTX 1080 Mobile] vendor: CLEVO/KAPOK driver: nvidia 
           v: 470.63.01 bus ID: 01:00.0 chip ID: 10de:1be0 
           Display: x11 server: X.Org 1.20.10 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa alternate: nv compositor: compton 
           v: 0.1~beta2+20150922 resolution: 3840x2160~60Hz 
           OpenGL: renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 470.63.01 
           direct render: Yes 
Info:      Processes: 261 Uptime: 15h 16m Memory: 31.19 GiB used: 2.81 GiB (9.0%) Init: SysVinit 
           v: 2.93 runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in 
           running in: quick-system-in inxi: 3.0.36 
[/code]

**Comment by artisteacher** [comment]
Task rendering used to fail on macOS, though T2D itself didn't crash. Since some paths to certain libraries were updated and this PR was ported from OT, it's worked without issue. https://github.com/opentoonz/opentoonz/pull/3767

Is there a crash report you can share?
