### ISSUE TITLE
Bloom fx bug with alfa

### ISSUE THREAD

**Issue by FerrLui** [tahoma2d/tahoma2d#857]
**There is bug with bloom fx**
 The alpha rendering checkbox wouldnt work (( There  is black cube around image.

**To Reproduce**
List steps to reproduce the behavior.
1.simpy create bloom fx

**Screenshots, short videos or logs**
Here is small video https://youtu.be/4YD-4laPzlA

**Device Information:**
 - OS: [. Windows 7]
 - Tahoma2D Version: Last Nightly, but it dont work a long time ago, becouse i update versions 2-3time

**Comment by artisteacher** [comment]
Do you have "alpha rendering" checked?
<img width="230" alt="Screen Shot 2022-01-05 at 2 33 05 PM" src="https://user-images.githubusercontent.com/21159116/148277688-97391218-d5f5-4b43-b76e-adaa882d999b.png">
It's off by default which results in a black background around the drawing.

**Comment by beeheemooth** [comment]
Strange, my Bloom Iwa effect window looks different. Maybe you have an old version?
![Screen_0420](https://user-images.githubusercontent.com/25724133/148288002-b2cf9b28-d349-4319-b3c4-a25ddef688aa.jpg)

**Comment by artisteacher** [comment]
Yeah, looks like it. In the more recent nightly builds you just need to choose "light" or "light and source" as the alpha mode to prevent the black background.

**Comment by FerrLui** [comment]
Im always change "Tahoamstaff" folder with my old folder. Im deleting new folder and drop my old folder. Maybe becouse of that my fx is looking this way?

**Comment by FerrLui** [comment]
Oh, yes, Its becouse, i delete neew "tahomastaff" folder and replace with my old version folder.  Now i download again Tahoma, And open it. And bloom fx is working correctly. I will rename my old folder  and done)) Thank guys !!!! :dancing_women:
