### ISSUE TITLE
Crash on loading another scene when a level from the Scene Cast of the previous scene is loaded into the Flipbook. 

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#859]
I was able to detect a crash when loading different scenes from the browser if you are viewing a level from Scene Cast in Flipbook. The steps are roughly as follows:
1. Load a scene from the browser, and drag a level from Scene Cast to the Flipbook window to view it. (I have my Flipbook window docked in the browser room).
2. Load another scene (also from the browser). In this case, different types of events can occur in the Flipbook window:
a) The Flipbook will display the level you dragged from the previous scene, but you won't be able to scroll through its frames, since for some reason only the first frame will be displayed.
b) Flipbook will switch to one of the levels of the current scene, and if you scrolled the previous level by several frames, then the position of the slider will be the same in this scene.
3. Load the first scene again.
I'm not sure why the crash occurs, but it definitely has something to do with the Flipbook and switching between scenes. Perhaps Flipbook, when switching between levels, if the slider has been moved, refers to a non-existent frame, or it remembers the position of the slider in the previous level and after returning to it, this data conflicts. These are just my assumptions.

The crash dump did not register. 

**Screenshots, short videos or logs**
![ezgif-7-2942d8df53](https://user-images.githubusercontent.com/25724133/148647116-689c2e69-448b-4e86-af7b-4263634eb9c5.gif)

**Device Information:**
 - OS: Windows 8.1
 - Tahoma2D Version: latest Nightly

**Comment by artisteacher** [comment]
I get a crash on macOS too.
[flipbook_scene_crash.txt](https://github.com/tahoma2d/tahoma2d/files/7839686/flipbook_scene_crash.txt)
.
