### ISSUE TITLE
 Tahoma crash working with sound

### ISSUE THREAD

**Issue by Tragustauro** [tahoma2d/tahoma2d#868]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1. Import/Loade sound (mp3/Wav)
2. Scroling in timeline with sound Tahoma crashes.
3.

**Screenshots, short videos or logs**
If applicable, add screenshots or links to short videos to help explain your problem or provide logs or dmp files if it's a crash.

**Device Information:**
 - OS: [e.g. Windows]
 - Tahoma2D Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by artisteacher** [comment]
What version of T2D are you using and what is your OS?

**Comment by Tragustauro** [comment]
Hello.

Win7 pro
Tahoma v.1.2
I am using the stop motion function in connection to pencil animation the most.

Once the wav or mp3 file is loaded into a new layer. I then start to scroll or some other task and the whole thing crash and stall.
Thanks in advance
Tragus.
![001](https://user-images.githubusercontent.com/97757066/149830163-7c18ae3d-7a3c-4d2a-ad4d-59ba27e492a0.JPG)

**Comment by artisteacher** [comment]
There have been some changes to how audio is handled since the 1.2 release.  Give the [latest nightly build](https://github.com/tahoma2d/tahoma2d/releases/tag/nightly) a try, and let us know if it fixes the problem or if you still have an issue. 

Just an FYI, some of the bug fixes and new features may make scenes saved with the latest nightly build incompatible with older versions of T2D. So I would start with a test project/scene in case you aren't ready to move on from 1.2.

If you can share the crash report, that would be helpful too.

**Comment by manongjohn** [comment]
I cannot duplicate this using the official 1.2 release on Win10.  I've tried with a WAV file.  

Does this happen with any WAV/MP3 you load?

If you can get it to crash again, please locate the crash report dump file (C:\Users\yourusername\AppData\Local\Tahoma2D\Tahoma2D\cache\crashrpt\xxxx\crashdump.dmp) and attach it here. You may need to zip or change extension to attach it.  I may be able to see why it's crashing for you.

**Comment by Tragustauro** [comment]
@[manongjohn]
Hello.

Thank you for putting in time to do this. 
I have both Opentoonz and Tahoma as I am trying them both out for my productions. 

Both have issues.

I am actually not 100 sure the crashes is caused by the imported sounds. Both mp3 or wav.

I want to use the softwares primarely as Pencillinetests. And I have been trying many many things and run into issues.
It seems like I have a conflict with OT and Tahoma when connecting to my HD webcam.
I am using the Stopmotin function. 
On the first "call for connecting to the web cam it all seems fine. I used it close the "live view" and move to the drawing desk.
I then come back and wants to turn on the "live view again" and everything freezes up and crashes.

I am on Win7 pro. (Wich I love) and Am using logitech 9000 webcam.
