### ISSUE TITLE
It is not possible to load the scene because it does not belong to any project error

### ISSUE THREAD

**Issue by iriedescented** [tahoma2d/tahoma2d#869]
**Scene won't load**
Whenever I try to load a specific project scene, it just gives me this error that "It is not possible to load the scene filename because it does not belong to any project error.' 
Whenever I try to load the project as well, it says "project not found."

![image](https://user-images.githubusercontent.com/97802451/149631937-96a72b5c-c47c-4bf1-bbfa-f0cc985955c0.png)
![image](https://user-images.githubusercontent.com/97802451/149631953-4a0fa348-98bb-4581-90ea-499a917f5973.png)

Weirdest part is, the other projects load perfectly fine and are shown except the specific one I was uploading, its as if it randomly stopped being a project.
![image](https://user-images.githubusercontent.com/97802451/149632057-95343c60-f995-4690-bfcd-0dda28d4388c.png)
My project is called closeup and is just a regular folder now, closeup2 was me attempting to move the scene to the new project but it still will not open.

Any way to fix this? I'd appreciate all help since I worked hard on the scene, though I'm not too tech smart.
**Device Information:**
 - OS: Windows 10
 - Tahoma2D 1.2

**Comment by manongjohn** [comment]
How did you move the scene to the other project?

Best way to move a scene to another project is to do an `Export Current Scene` then select or create a new project.

**Comment by iriedescented** [comment]
@manongjohn I manually moved it through file explorer since it won't allow me to open.
I didn't know about the export feature though, is there any other way to do it since it doesn't open up?

**Comment by iriedescented** [comment]
@manongjohn I manually moved it through file explorer since it won't allow me to open.
I didn't know about the export feature though, is there any other way to do it since it doesn't open up?

Sorry for the double ping, I accidentally closed this.

**Comment by manongjohn** [comment]
I recommend going to Tahoma2D's Discord (https://discord.gg/uFdhmKQ) to work this out in more real time than over this thread, as I have many more questions to ask to understand what was done.  If going to Discord is an issue, please use the Tahoma2D's Google Group (https://groups.google.com/g/tahoma2d) to discuss.

I will be closing this as this is more a user issue than a bug.

**Comment by iriedescented** [comment]
@manongjohn Thank you so much for the answer! I'll be joining the discord.
