### ISSUE TITLE
Crash when editing the "memo" color. 

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#871]
1. Open the "memo" window.
2. Choose a color for "memo"
3. Try to change it in the Style Editor
4. Crash.

The same actions in OpenToonz do not lead to a crash, the "memo" color changes successfully.

**Device Information:**
 - OS: Windows 8.1
 - Tahoma2D Version: latest Nightly

**Comment by artisteacher** [comment]
I get a crash on macOS too.
[memo-color.txt](https://github.com/tahoma2d/tahoma2d/files/7885151/memo-color.txt)


Is the memo color supposed to change? I hadn't realized that was an option...
