### ISSUE TITLE
Render crashes with some mesh deformed animations

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#889]
**Describe the bug**

Several of my students have been having crashes when rendering scenes that utilize the plastic tool. The version of T2D and the version of FFMPEG (ie. latest release vs. T2D's custom) doesn't seem to make a difference. Render format hasn't made a difference. Task rendering, especially to an image sequence is more likely to be successful but it's not a guarantee.

I have a couple scenes I can share privately that always crash.

**To Reproduce**
List steps to reproduce the behavior.
1. Make an animation with the plastic tool - longer/more complex animations seem more likely to crash (level type does not seem to make a difference)
2. Fast render to MP4 (other render formats and Task rendering can crash too)

**Screenshots, short videos or logs**

[plastic-crash.txt](https://github.com/tahoma2d/tahoma2d/files/7955107/plastic-crash.txt)

**Device Information:**
 - OS: macOS Catalina & Monterey
 - Tahoma2D Version: Nightly builds from early 9/21 and from 1/20/22

**Comment by manongjohn** [comment]
@artisteacher Please send me a scene that always crashes.  Send in DM on Discord and I'll see if I can find what's going on with it.

**Comment by artisteacher** [comment]
Scene has been sent. Thanks so much for taking a look!

I do wonder if part of this could be a caching issue? For a different scene - it crashed every time rendering to video on the student's computer. When I exported the current scene to its own project, moved it to my computer and fast rendered, it rendered just fine.

**Comment by artisteacher** [comment]
I wonder if this is related: https://github.com/opentoonz/opentoonz/issues/4294
