### ISSUE TITLE
Crash on undo operation of deleting a mesh frame in the Level Strip.

### ISSUE THREAD

**Issue by beeheemooth** [tahoma2d/tahoma2d#899]
**To Reproduce**
1. Create a new level and draw two frames in it (for example 1 and 2)
2. Select these two frames with drawings in the Xsheet / Timeline and apply the creation of a plastic mesh to them (Plastic Tool > Create Mesh) and you will get two mesh frames.
3. Delete one of these frames in the Level Strip of the mesh level.
4. Undo this operation.
5. Crash. 

**Device Information:**
 - OS: Windows 8.1
 - Tahoma2D Version: latest Nightly

**Comment by artisteacher** [comment]
I get the same crash on macOS.
[plastic.txt](https://github.com/tahoma2d/tahoma2d/files/7996520/plastic.txt)
