### ISSUE TITLE
Tahoma Crash(And OT)-New knowledge.

### ISSUE THREAD

**Issue by Tragustauro** [tahoma2d/tahoma2d#903]
Hello. Sorry about my ignorance. First time using Github.

I think I found out about the crash. For both OT and Tahoma.

webcam logitech 9000 
Newest driver updated. 
Webcam software works like a charm. Crisp picture .
Tahoma and OT installed.
Everything works like a charm.
On start up I disregard the startup menu where you can name your scene. I close it.
Activate "Stopmotion" control/function.
Webcam activated and no problem.
I test out my scene. (Paper-pencil linetest)
I do either of two things.

1: I save the scene
2: I close down with out saving.

On the next startup I have the option of starting all over again from fresh. Or I can choose 
"Recent Scene"
When I choose start all over agian in a new scene= Noproblem. (As I recall)
When I choose "RecentScene"  Tahoma starts to work on opening the "recent Scene" I chose. And Tahoma freezes/Crashes. For some reason I might get lucky that the scene actually starts up. But as soon as I touch "Stop-motion" it crashes.!???

So to work with out crashes I need not to save anything but start over.

Btw. Once the crash has been done I have no more connection to the webcam even thoug I see it is still installed. Even in The webcams software I can not reach it!!..
Ohh by the way. I like to add.

I can only get in touch with the webcam by psychically removing the USB cord from the PC and plug it in again. (With out restart pc).

I will try tonight to make a video of he problem

_Originally posted by @Tragustauro in https://github.com/tahoma2d/tahoma2d/issues/900#issuecomment-1037314803_

**Comment by artisteacher** [comment]
If this is the same crash as #900, you should continue reporting in that issue, rather than starting a new one. Again, if you can share the crash log, it would be helpful.

**Comment by manongjohn** [comment]
Closing as  duplicate.  Will rename the other issue
