### ISSUE TITLE
Tahoma crash when undo collapse 

### ISSUE THREAD

**Issue by F-Burning** [tahoma2d/tahoma2d#910]
When I collapse some nodes using Scene -> collapse, and then undo the action, tahoma crash.

I have the last nightly built [2022-02-19 22:15:15 UTC]

**Comment by artisteacher** [comment]
I'm not getting a crash on macOS.

Are there any other steps that might have an impact?

**Comment by manongjohn** [comment]
I also cannot duplicate this crash.

If you are one Windows, can you locate the crashdump file and include in the ticket? It may show me why you are crashing.

**Comment by F-Burning** [comment]
Sorry, I was working with many nodes (not too much at all), and then crashes when I undo the collapse, but I can't repeat the issue now.

I will be alert from now on in case it happens again so I can report it properly.

**Comment by F-Burning** [comment]
Sorry, I was working with many nodes (not too much at all), and then crashes when I undo the collapse, but I can't repeat the issue now.

I will be alert from now on in case it happens again so I can report it properly.

**Comment by F-Burning** [comment]
Now crash simply adding effects.

![10](https://user-images.githubusercontent.com/74098734/156071431-5f521deb-8614-49ab-b809-feb56d152c2b.jpg)

Maybe the bug is in the gradient, or in the blending nodes.

**Comment by artisteacher** [comment]
I've gotten random crashes when working with FX for ages - but I haven't been able to nail down the exact cause. Now I always save after adding a new FX and before I open the FX settings. It seems to minimize the crashing.
