### ISSUE TITLE
MP4 exports have encoding problems

### ISSUE THREAD

**Issue by ddigii** [tahoma2d/tahoma2d#917]
Found a bug with the MP4 exporting while trying to upload a finished animation to my Carrd-based portfolio - It appears to be a problem with h.264 encoding, as re-saving the file through Premiere Pro as h.264 solved the issue.

**To Reproduce**
1. Render scene as MP4.
2. Attempt to send via Discord, open through a browser, or upload to carrd.co.

**Comment by manongjohn** [comment]
The ffmpeg packaged with the release has been updated to correct this issue.  Please download the latest nightly to get the updated T2D and ffmpeg package.

You can get the latest nightly from here: https://github.com/tahoma2d/tahoma2d/releases/tag/nightly

FYI:  The latest nightly has a lot of new changes, the biggest one being Implict Holds.  For scenes created in the official T2D 1.2 or older, you should turn off Implicit Holds (in Preferences, Quick Toolbar options, timeline context menu) or convert the scene from Explicit Holds to Implicit Holds (Scene menu options) before rendering.
