### ISSUE TITLE
Convenience Request

### ISSUE THREAD

**Issue by KiroYusay** [tahoma2d/tahoma2d#922]
It gets annoying to scroll down for the brushes in the "Raster" tab.  I would appreciate a "Bookmark" or "Favorite" feature so that don't have to go searching for what Kind of brush stroke I need.

![Untitled](https://user-images.githubusercontent.com/101161372/157162930-c176d5ce-be7f-41c3-9760-c1d326278197.png)

**Comment by manongjohn** [comment]
Download the latest nightly from here: https://github.com/tahoma2d/tahoma2d/releases/tag/nightly

It has a new feature which will be in the next release for managing brush sets.  You can create/collapse/hide sets and configure your My Favorite set.  Read PR #789 for more information.
