### ISSUE TITLE
Opacity slider lost (Little bug)

### ISSUE THREAD

**Issue by F-Burning** [tahoma2d/tahoma2d#924]
This one

![01](https://user-images.githubusercontent.com/74098734/157503549-611b4709-818e-42f7-925d-050e61464f86.jpg)

**Comment by artisteacher** [comment]
It looks like it's a problem for a couple languages:
<img width="252" alt="Screen Shot 2022-03-09 at 4 03 01 PM" src="https://user-images.githubusercontent.com/21159116/157535817-dfba09cc-f20b-4c74-a55e-d21f9015d018.png">
<img width="226" alt="Screen Shot 2022-03-09 at 4 03 44 PM" src="https://user-images.githubusercontent.com/21159116/157535823-3835cfa3-651d-4d2e-821f-b19484ed3028.png">

Not a problem in English.
