### ISSUE TITLE
Crash when using Segment Erase on edge of level canvas

### ISSUE THREAD

**Issue by RattusaurusRex** [tahoma2d/tahoma2d#926]
Tahoma crashes if you use Segment Erase to attempt to erase a line that touches the edge of the canvas.

**To Reproduce**
1.  Draw a line that touches the edge of the level canvas
2.  Use Eraser set to Segment to try to erase the line
3.  Tahoma crashes

**Screenshots, short videos or logs**
![segerasebug](https://user-images.githubusercontent.com/60277069/158038120-a4dd2718-3e82-4586-96c3-d6773de5ec43.gif)

No crash log is created

**Device Information:**
    OS: Windows 10 Pro 64-bit
    Tahoma2D Version: Nightly build 2022-02-19 22:15:15 UTC
    CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor
    GPU: NVIDIA GeForce RTX 3070 Ti
    Graphics Tablet: Wacom Cintiq Pro 24

**Comment by artisteacher** [comment]
I don't get this crash every time, but I was able to trigger it once. Here's the crash report
[segment-crash.txt](https://github.com/tahoma2d/tahoma2d/files/8246629/segment-crash.txt)
.
