### ISSUE TITLE
Camera DSLR detection in linux

### ISSUE THREAD

**Issue by charliemartinez** [tahoma2d/tahoma2d#927]
Hello! Does Tahoma2d for Linux use the gphoto2 library to detect DSLR cameras? I ask this because I have a Canon PowerShot S5 IS which is detected by Entangle but not by Tahoma.

 - OS: Debian 11 (Bullseye)
 - Tahoma2D Version: stable 1.2
 - GPU: intel hd graphics onboard
 - intel i5 8 gb RAM

**Comment by manongjohn** [comment]
T2D uses the Canon ESDK for Canon DSLR support. Unfortunately there is no Linux support. It only works for Windows/OSX.

Due to license restrictions, I cannot use the gphoto2 library.

**Comment by quirinux-so** [comment]
Oh, this is terrible if you want to use Tahoma2D as a free professional alternative on GNU/Linux... most animators don't use webcams.

According to the FSF, while the original BSD license is incompatible with the GPL, **there is no incompatibility** with the "new" or "revised" BSD license.

If I'm not mistaken, Tahoma2D adopts the revised clause.

Sources:

- https://www.gnu.org/licenses/gpl-faq.html#OrigBSD
- https://github.com/tahoma2d/tahoma2d/blob/master/LICENSE.txt

**Comment by manongjohn** [comment]
There is no real incompatibility betweeb BSD and GPL but GPL requires some things that are limiting to the eyes of Dwango/Digital Video, the owners of OpenToonz.

As Tahoma2D, a fork of OpenToonz, regularly shares code with OT, I need to adhere to the same license restritctions that OT has adopted.

**Comment by quirinux-so** [comment]
traductor ingles español


I understand, although it is too great a limitation when it comes to competing with proprietary tools. I think Tahoma2D is the most professional program out there for animators out there for stop motion animators working on gnu/Linux. 

Do you think it would be possible, in the not too distant future, for the Tahoma team to write something like a **plug-in** that implements gphoto2? Audacity did not implement the LAME plugin when the mp3 format had an incompatible license.

**Comment by manongjohn** [comment]
Wait....I just checked https://github.com/gphoto/libgphoto2 and it's LGPL licensed.  When I went to the site (gphoto.org) to find any licensing information, and a page that I went to referenced it was licensed under GPL which is why I thought I couldn't use it.

Seems the libgphoto2 is LGPL but the other gphoto programs that were mentioned are available are GPL.  I mistakenly took that as libphoto2 was GPL.  This means  I can use the libgphoto2 in T2D, as far as I can tell.

Only I have to 2 problems....I don't have a Linux system (I have a virtual Ubuntu environment I use to test some stuff on) and I don't have a DSLR.  I can try and get it to compile with the library but I'd have problems verifying and bug fixing.  Additionally, our code, because we use Canon's EDSDK for Windows/OSX builds is Canon-centric so I would likely need to build a whole new set of interfaces for this library.

I can take a stab at it, even though I don't have proper equipment to check it.  However, if you know a linux developer with a DSLR who willing to incorporate libphoto2 into T2D, they would most certainly be welcomed.

**Comment by artisteacher** [comment]
Will this expand the variety of supported DSLR? If so & this works on macOS, in I have access to a Canon SL2, a Nikon D3300 & some kind of Panasonic DSLR that I could test with.

**Comment by manongjohn** [comment]
There is a long list of supported camera found [here](http://gphoto.org/proj/libgphoto2/support.php) ...i just found out that I have a Nikon D50 which is supposedly supported, though no live view capabilities.

I need to see how my camera would be recognized in my VM as a way to do some simple testing. Developing on my VM is very slow and the VM on my new laptop acts strangely so any development i would do will take me a bit of time.

If it works on macs, i'd either replace the Canon EDSDK for mac builds or make it smart and use one or the other depending on the camera and which library supports it.

Makes me wonder if I should convert my old Win7 laptop that i barely use into a Linux (Ubuntu) machine. 🙂

Many possibilities.

**Comment by artisteacher** [comment]
Looks like my Panasonic is too old - too bad! Despite that, more supported cameras would definitely be helpful.

**Comment by jeremybullock** [comment]
Originally, I had hoped to use libgphoto2 for the DSLR stuff because it supports so many more cameras.  I think on Mac and Linux it makes sense to use it if you can, but on Windows, it requires a change of USB driver which actually borks many systems (including mine when I tried it).

**Comment by manongjohn** [comment]
Hey @jeremybullock. Wasnt sure you were still around. Good to hear from you.

I was able to get my Ubuntu VM to recognize my Nikon DSLR and tested it with gtkam. Worked though i bugged out gtkam every time i snapped an image. Was also having quite a few issues with the VM on this new laptop.

My camera doesn't support Live View so not sure i can fully test libgphoto2 integration using it. I think Live View is needed for Stop Motion stuff to work properly?

**Comment by jeremybullock** [comment]
Hey @manongjohn!  I still lurk around from time to time.  I'm really proud of all you've done and continue to do with Tahoma.  

Regarding stop motion, without live view it is really challenging.  It can be done, but live view makes things so much easier.  

About using libgphoto2 on Mac, I would make sure that libgphoto2 can support all the functions Tahoma supports currently with Canon cameras before making the leap.

**Comment by manongjohn** [comment]
Thanks. 🙂

My intention is to first get libgphoto2 working on Linux and at some point later, look into switching macs to it.  To my knowledge, libgphoto2 hasn't been ported to Windows systems.

Not counting the VM issue i have, i think the biggest hurdle is not having a camera with live view support.  I can use it to start work on integrating the interface to the lib but will need to somehow borrow a live view supported camera.

Will be looking more into this after 1.3 release.

**Comment by artisteacher** [comment]
It looks like there are some [Windows ports](https://github.com/gphoto/gphoto2/issues/85).

I hope you and your family are doing well @jeremybullock - it's nice to hear from you!

**Comment by charliemartinez** [comment]
Hello! You have no idea how happy I am about the LGPL! A great hope opens up.

Your motion path tool is PERFECT. 

As for testing, I had the same problem for many years, so now that I was able to get a camera I can help you! I also have a real machine with Debian to do the tests. I will love to do the tests that you indicate me.

**Comment by charliemartinez** [comment]
Today I have tested my canon t3i dslr with the following code that allowed me to capture the live image as if it were a webcam:

`gphoto2 --stdout autofocusdrive=1 --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0`

![canon t3i on tahoma2d](https://www.fpcharlie.ga/files/canontahoma.png)

However, there are two things that need to be fixed:

- Although the resolution indicates 1920x1080, the captured image is smaller
- The photographs are not shot by the camera, it is only emulating the operation of a webcam, and when capturing an image Tahoma behaves _-logically-_ as if it were in front of a web cam, and captures the liveview frame, so the quality It is less than if the photo were taken by the camera itself, as is the case with other software such as Entangle and qstopmotion.

**More comparative information:**

**qstopmotion** is the only one that featured native gphoto2 support and I didn't have to release the code I posted though is extremely slow and the program becomes heavy in itself, I have a feeling that it would be difficult to shoot a complete take.

![canon t3i on tahoma2d](https://www.fpcharlie.ga/files/canonqstopmotion.png)

**TupiTube,** another animation program, accomplishes the same thing by displaying the full 1920x1080 resolution, although it also fails to shoot the pictures from the camera.

![canon t3i on tahoma2d](https://www.fpcharlie.ga/files/canontupi.png)

The only program that worked perfectly was **Entangle**: liveview ok, smooth image, low resource consumption, shots from the camera itself, correct resolution and full control of all camera parameters from the same software.

![canon t3i on tahoma2d](https://www.fpcharlie.ga/files/canonentangle.png)

**Comment by manongjohn** [comment]
Small update...I have been slowly working on this recently and and managed to get libgphoto2 compiled into T2D. I was able to detect a connected Nikon camera in Windows and Linux! I didnt try on macOS, yet, but it should work. Sadly the Nikon I was using isn't supported well in libgphoto2.

Due to the limitation of my Nikon and my tiny progress with libgphoto2, I was inspired to buy may own Canon DSLR which is better supported in the lib.

Currently reviewing existing stopmotion code and planning next steps. Integrating libgphoto2 into T2D is a bit of a challenge atm. I can't really look at GPL licensed code as I may inadvertantly copy it, so I need to figure out how to do this from examples provided with the lib as well as pure trial and effort.

At any rate...it is slowly being worked on. 🙂

**Comment by charliemartinez** [comment]
Wonderful, you are a genius!!! yes, my canon T3i works fine in Entangle. I thought I read here that gphoto's code was LGPL. Please, any tests you think I can do that will help you with your work, I will be happy to do it. 

Cheers:-)

**Comment by manongjohn** [comment]
@charliemartinez  FYI, I just submitted a PR #1027 for libgphoto2 integration into T2D. I still need to verify the build/packaging through github so there might be some additional changes needed before you can actually start test it.

**Comment by charliemartinez** [comment]
I am very happy with this news. I'm not good at compiling T2D, if at some point you can create an appimage with this new feature, I'll be happy to try it out. Thank you miles.

> @charliemartinez FYI, I just submitted a PR #1027 for libgphoto2 integration into T2D. I still need to verify the build/packaging through github so there might be some additional changes needed before you can actually start test it.

**Comment by manongjohn** [comment]
A successful PR builds artifacts which you can download and test.  It's how people test new features/changes before it is merged into the master. 

To get to the artifacts...
1. Click on the PR link I mentioned above
2. Just above the description of the PR, click the `Checks` tab
3. On the Left side, click on `Tahma2D Linux Build`

This should take you to the `Summary` for the build and the artifacts will be on the bottom right.

**Comment by manongjohn** [comment]
@charliemartinez Not sure if you've gotten the chance to download the PR Artifact.  In case you are having trouble getting to it, here's a link to the `Checks` tab of the PR: https://github.com/tahoma2d/tahoma2d/pull/1027/checks  Click on the Tahoma2D `Linux Build`, on the left then choose `Summary`.

Let me know how it goes.

**Comment by charliemartinez** [comment]
Hello,

First of all THANK YOU VERY MUCH.
I have tried the new functionality and couldn't be happier with how well Tahoma now **recognizes my Canon T3i**. However, I couldn't animate :-(

 I'm surprised, since with the webcam in the stable version I could. 

The thing is that I turn on the preview, everything works fine, I take the first picture and then the timeline doesn't advance. Also, the photograph I took did not appear. 

I did a video, maybe I'm doing something wrong or maybe it's an expected behavior at this point in development.

[Video demostration](https://www.quirinux.ga/img/demo.tahoma.webm)

**Comment by charliemartinez** [comment]
What I mentioned before happened the first time I tried the appimage. The second time something weirder happened: the stopmotion tab appeared empty. I restarted the computer and it was still blank.
It was only restored when I deleted the unzipped folder containing the appimage and re-extracted the appimage from tar.gz
Then it didn't happen again, maybe it was circumstantial.

![demo stopmo](https://www.quirinux.ga/img/tahomademo2.jpg )

**Comment by charliemartinez** [comment]
IT WORKED!!!
I'll tell you what I did: I reset my camera settings to the default ones (with an option from its own settings menu) and now it works perfectly. I am amazed at this new functionality. I will release the definitive version of Quirinux OS soon, with Tahoma2D pre-installed. THEY HAVE DONE A GREAT JOB.
