### ISSUE TITLE
Stop Motion: Improvements to Motion Path and DSLR support for GNU/Linux (essential for professional animation)

### ISSUE THREAD

**Issue by charliemartinez** [tahoma2d/tahoma2d#931]
For us stop motion animators currently using the Linux version of Dragon Frame to start using Tahoma2D, we need 2 things:

**1) Improve the motin path:**

> -Make it allow to set the amount of steps in the Motion Path
> 
> -Make it possible to graduate (if it is better automatically) the acceleration and deceleration of those steps.
> 
> I made this new video to show what I say, with a demo of what we expect the tool to do:
> 
> https://www.fpcharlie.ga/files/animation_feature_request.mp4

**2) DSLR support on GNU/Linux.** (Now available on qstopmotion)

_The day that Tahoma, Tupi, qstopmotion, boats animator or other software achieve these TWO THINGS TOGETHER (both) for GNU/Linux achieves this, that software  will undoubtedly be accepted in **professional stop motion animation schools**.__ 

Thanks !!

IMPORTANT UPDATE!:

@manongjohn com just told me that the tool to scale the steps and spacing in the tahoma motion path ALREADY EXISTS. This is wonderful, I was able to locate it thanks to your indications (panels / motion path). MANY THANKS

![Motion path](https://www.fpcharlie.ga/files/motion-path.png
)

**Comment by manongjohn** [comment]
@charliemartinez  Thanks for this information.

1) The `Motion Paths` panel found under `Panels` menu, already allows you to create the motion paths, define the number of Steps and adjust the spacing.  Does this not meet the need or am I missing something?

2) I really wish there was an LGPL licensed library or one with a more open license that I could use for detecting DSLR cameras.  Just cannot be GPL licensed or anything more restrictive. If there is one, I would do that in a heartbeat.

**Comment by charliemartinez** [comment]
Thanks for your answer. What you say is great!! How can I do that? If you look at the video that I put, you will see that I did not find the way. I am really very happy to know that this is possible, since it is something that I have been waiting for for years. Is there any video or documentation about it? I mean the number of steps and the spacing.

Regarding the licenses, unfortunately it is very rare to find people adopting alternatives to GPLv3. I myself tend to adopt GPLv2. Keep in mind that if I am leaving this message in the animation softwares githubs that I have tried, it is in case at some point they are read by a developer who is working on something like this.

All the best

**Comment by manongjohn** [comment]
Unfortunately I don't believe it's documented, at least not the panel itself.

Here's a quick gif on how to use it: ![motionpaths](https://user-images.githubusercontent.com/19245851/158688225-ad554908-8682-46fc-a91d-eac4f47f3649.gif)

You can define multiple motion paths, make stroke modifcations as needed, control even color and width of the line.   You can control which one is visible by clicking on the "eye" icon.

**Comment by charliemartinez** [comment]
This is wonderful. I will share your GIF on the Quirinux GNU/Linux page. Many thanks.
