### ISSUE TITLE
Multiple Displays Break Viewer

### ISSUE THREAD

**Issue by gitbugr** [tahoma2d/tahoma2d#941]
**Describe the bug**

When I connect my Macbook to an external display + my Cintiq, (Totalling 3 displays) it creates a strange issue where it appears that I cannot draw on the Viewer panel anymore. If I close my Macbook and reduce the displays to 2, this works as expected, but I'd like the be able to make use of all 3. 

**To Reproduce**
List steps to reproduce the behavior.
1. Have a total of 3 displays
2. Open Tahoma
3. Try to draw on cel

**Device Information:**
 - Device: Macbook Pro 13.inch, 2018
 - OS: Mac OS 12.3
 - Graphics Tablet: Cintiq 13 HD
 - Tahoma2D Version: 1.2

**Comment by manongjohn** [comment]
A fix for multi monitor display issue (a very old bug) was recently corrected and will be in the next release.

Please download the latest nightly and see if it fixes the issue.

**Comment by gitbugr** [comment]
@manongjohn It does fix it!
