### ISSUE TITLE
PSD import issues

### ISSUE THREAD

**Issue by artistlibre** [tahoma2d/tahoma2d#982]
### Bug Description

Hi,
Tried to import PSD exported from Photoshop and Krita respectively. But, show only error warnings like "layer ID not exists". I try to export each layer as separate PNG files every time and aligning their positions. But, it drags my working time by huge margin. Having been a user of OpenToonz from the version 1.3. Hope, it gets resolved in the future. Also, is there a possibility to open file formats like OpenRaster (.ora) in the future.? Thanks in advance!

### Steps to reproduce

Just trying to load PSD layers as X-Sheet columns will showcase the problem. I have attempted it numerous times, with various PSD outputs from GIMP, Krita and even the Photoshop itself.

### Relevant logs/screenshots

![image](https://user-images.githubusercontent.com/103920849/163765452-75263844-30bd-493c-9c4b-62368eb6acaf.png)

![image](https://user-images.githubusercontent.com/103920849/163764388-38696ab2-64df-436f-8e70-04f0a1e2a146.png)

This is how it looks when loading the file exported from Photoshop (Similar thing happens when opening the PSD exported from Krita and GIMP).

### Software Version

1.3

### Operating System

Windows 7 (Also, it is the same case with Windows 10 as well)

**Comment by manongjohn** [comment]
I have imported PSDs layers as columns but I know this issue pops up from time to time and somewhat depends on what software created the PSD file and perhaps whatever options were chosen.

In order for me to look into this more efficiently, can you attach a problematic PSD file I can use to debug with?

**Comment by artistlibre** [comment]
[Tree2.zip](https://github.com/tahoma2d/tahoma2d/files/8504218/Tree2.zip)
Hi, thanks for asking. Have zipped the problematic PSD.

**Comment by manongjohn** [comment]
I found the issue and have submitted a fix.  The fix will be included in 1.3.

Thanks for providing the file. It was definitely helpful in identifying the issue!

**Comment by artistlibre** [comment]
Thanks a lot! This is going to be a huge improvement.
