### ISSUE TITLE
Add your Default Project Path into the list of root folders

### ISSUE THREAD

**Issue by DarrenTAnims** [tahoma2d/tahoma2d#996]
It would make using Tahoma so much easier if my Default Project path (that I setup in the Preferences dialog) was added to the list of root folders in the Load Scene (and other dialogs)?

![Root Folders](https://user-images.githubusercontent.com/28575907/167686433-fedff667-015f-4261-b88e-910a789d9be4.png)

**Comment by hennj20** [comment]
Great idea, actually have thought about this a few times but I never put in a request.
